export { materializeBiome, materializeBiomePrefix } from './biome';
export { BiomeMaterializationContractError, selectedBatchContinuation } from './batch';
export {
  fieldsBatchFacts,
  fieldsBatchOwnsCageOutcome,
  targetContinuation,
  type FieldsBatchFacts,
} from './decision-facts';
export { HubMaterializationContractError, materializeHubDecision } from './hub';
export { materializeShipCombatState, type MaterializedShipCombatState } from './rooms';
export type {
  CanonicalAuthoredRoom,
  CanonicalAdditionalContinuation,
  CanonicalBatch,
  CanonicalBatchState,
  CanonicalBatchRewardStore,
  CanonicalBiomeState,
  CanonicalBiome,
  CanonicalDecision,
  BiomeMaterialization,
  MaterializedBiomePrefix,
  MaterializedExitDecisionFrontier,
  MaterializedHubContinuationFrontier,
  MaterializedHubDecisionFrontier,
  MaterializedHubVisitFrontier,
  CanonicalHubBoard,
  CanonicalHubDecision,
  CanonicalHubRoom,
  CanonicalHubRoomReference,
  CanonicalHubTarget,
  CanonicalHubVisit,
  CanonicalLocalVisitRoom,
  CanonicalFieldsOptionalReward,
  CanonicalLocalReward,
  CanonicalRewardWheel,
  CanonicalRewardWheelOffer,
  CanonicalPhysicalExit,
  CanonicalResolvedIncomingReward,
  CanonicalRoom,
  CanonicalRoomReference,
  CanonicalRoomRestore,
  CanonicalShopEntryState,
  CanonicalShopOffer,
  CanonicalSelectedBatchContinuation,
  CanonicalTarget,
  CanonicalTargetContinuation,
} from './model';
