import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Arachne's Story-room costume choices. Armor depletion is intentionally
 * collapsed: the selected costume remains in the equipped-trait ledger. */
export const arachneTraits = [
  {
    key: 'AgilityCostume',
    label: 'Lavender Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ManaCostume',
    label: 'Azure Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'VitalityCostume',
    label: 'Emerald Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'HighArmorCostume',
    label: 'Onyx Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'CastDamageCostume',
    label: 'Fuchsia Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'IncomeCostume',
    label: 'Gilded Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SpellCostume',
    label: 'Moonlight Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'EscalatingCostume',
    label: 'Crimson Dress',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const arachneGiver = {
  key: 'Arachne',
  label: 'Arachne',
  providerKind: 'npc',
  priorityTraitKeys: [],
  traitKeys: [
    'AgilityCostume',
    'ManaCostume',
    'VitalityCostume',
    'HighArmorCostume',
    'CastDamageCostume',
    'IncomeCostume',
    'SpellCostume',
    'EscalatingCostume',
  ],
  rarityPolicy: { kind: 'fixed', rarity: 'Common' },
  defaultOffer: {
    options: [
      { traitKey: 'AgilityCostume', rarity: 'Common' },
      { traitKey: 'ManaCostume', rarity: 'Common' },
      { traitKey: 'VitalityCostume', rarity: 'Common' },
    ],
    selectedOption: 0,
  },
} as const satisfies RawTraitGiverDeclaration;
