import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Artemis' field-NPC pool and its source-owned default offer. */
export const artemisTraits = [
  {
    key: 'SupportingFireBoon',
    label: 'Support Fire',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Air: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'CritBonusBoon',
    label: 'Pressure Points',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Earth: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'DashOmegaBuffBoon',
    label: 'Shadow Pounce',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Air: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'HighHealthCritBoon',
    label: 'Vital Signs',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Earth: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'InsideCastCritBoon',
    label: 'Lethal Snare',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Earth: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'OmegaCastVolleyBoon',
    label: 'Easy Shot',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Air: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'TimedCritVulnerabilityBoon',
    label: 'Death Warrant',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Earth: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'FocusCritBoon',
    label: 'Killing Stroke',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Air: 1 },
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SorceryCritBoon',
    label: 'Whispered Prayer',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'SpellLaserTrait',
          'SpellLeapTrait',
          'SpellSummonTrait',
          'SpellMeteorTrait',
          'SpellTransformTrait',
          'SpellMoonBeamTrait',
          'SpellPolymorphTrait',
        ],
      },
    ],
    elementContributions: { Air: 1 },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const artemisGiver = {
  key: 'Artemis',
  label: 'Artemis',
  providerKind: 'npc',
  shopAwareGodTrait: true,
  priorityTraitKeys: [],
  traitKeys: [
    'SupportingFireBoon',
    'CritBonusBoon',
    'DashOmegaBuffBoon',
    'HighHealthCritBoon',
    'InsideCastCritBoon',
    'OmegaCastVolleyBoon',
    'TimedCritVulnerabilityBoon',
    'FocusCritBoon',
    'SorceryCritBoon',
  ],
  rarityPolicy: {
    kind: 'selectable',
    rarities: ['Common', 'Rare', 'Epic'],
  },
} as const satisfies RawTraitGiverDeclaration;
