import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Athena's field-NPC pool and its source-owned default offer. */
export const athenaTraits = [
  {
    key: 'InvulnerabilityDashBoon',
    label: 'Divine Dash',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'RetaliateInvulnerabilityBoon',
    label: 'Defensive Posture',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'FocusLastStandBoon',
    label: 'Stalwart Stand',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'DeathDefianceRefillBoon',
    label: 'Renewed Faith',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'offerContext',
        context: 'deathDefianceConditionMet',
        required: true,
      },
    ],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'AthenaProjectileBoon',
    label: 'Phalanx Shot',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'InvulnerabilityCastBoon',
    label: 'Mental Block',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ManaSpearBoon',
    label: 'Righteous Pike',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'OlympianSpellCountBoon',
    label: 'Task Force',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'PolymorphZeusTalent',
          'MeteorHestiaTalent',
          'TransformAphroditeTalent',
          'LeapHephaestusTalent',
          'LaserApolloTalent',
          'SummonHeraTalent',
          'TimeSlowDemeterTalent',
          'PotionPoseidonTalent',
          'MoonBeamAresTalent',
        ],
      },
    ],
    elementContributions: { Fire: 1 },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const athenaGiver = {
  key: 'Athena',
  label: 'Athena',
  providerKind: 'npc',
  priorityTraitKeys: [],
  traitKeys: [
    'InvulnerabilityDashBoon',
    'RetaliateInvulnerabilityBoon',
    'FocusLastStandBoon',
    'DeathDefianceRefillBoon',
    'AthenaProjectileBoon',
    'InvulnerabilityCastBoon',
    'ManaSpearBoon',
    'OlympianSpellCountBoon',
  ],
  rarityPolicy: {
    kind: 'selectable',
    rarities: ['Common', 'Rare', 'Epic'],
  },
  defaultOffer: {
    options: [
      { traitKey: 'InvulnerabilityDashBoon', rarity: 'Common' },
      { traitKey: 'RetaliateInvulnerabilityBoon', rarity: 'Common' },
      { traitKey: 'FocusLastStandBoon', rarity: 'Common' },
    ],
    selectedOption: 0,
  },
} as const satisfies RawTraitGiverDeclaration;
