import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Source-closed trait declarations. Giver membership remains separate below. */
export const hermesTraits = [
  {
    key: 'HermesWeaponBoon',
    label: 'Nimble Limbs',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Earth: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'HermesSpecialBoon',
    label: 'Racing Thoughts',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Earth: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'HermesCastDiscountBoon',
    label: "Winner's Circle",
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Earth: 1,
    },
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SprintShieldBoon',
    label: 'Nitro Boost',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Fire: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SorcerySpeedBoon',
    label: 'Stutter Step',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Earth: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'DodgeChanceBoon',
    label: 'Hasty Retreat',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SlowProjectileBoon',
    label: 'Hard Target',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'MoneyMultiplierBoon',
    label: 'Quick Buck',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'offerContext',
        context: 'blockGiftBoons',
        required: false,
      },
    ],
    elementContributions: {
      Air: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'TimedKillBuffBoon',
    label: 'Mean Streak',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'RestockBoon',
    label: 'Travel Deal',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Fire: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    selectedDisposition: {
      kind: 'worldShopRestock',
      refillCount: 1,
      discountByRarity: { Common: 0.05, Rare: 0.1, Epic: 0.15, Heroic: 0.2 },
    },
  },
  {
    key: 'LuckyBoon',
    label: 'Success Rate',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'DoubleRewardBoon',
          'PoseidonCastBoon',
          'PoseidonStatusBoon',
          'BoltRetaliateBoon',
          'DoubleBoltBoon',
          'SpawnKillBoon',
          'BlindChanceBoon',
          'DoubleStrikeChanceBoon',
          'CritBonusBoon',
          'HighHealthCritBoon',
          'InsideCastCritBoon',
          'TimedCritVulnerabilityBoon',
          'FocusCritBoon',
          'DashOmegaBuffBoon',
          'SorceryCritBoon',
          'AresManaBoon',
          'BloodDropRevengeBoon',
          'MissingHealthCritBoon',
          'AresStatusDoubleDamageBoon',
          'DoubleSplashBoon',
          'BloodManaBurstBoon',
          'MoneyDamageBoon',
        ],
      },
    ],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ElementalUnifiedBoon',
    label: 'Tall Order',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic'],
    offerRequirements: [
      {
        kind: 'highestBaseElementCount',
        minimum: 4,
      },
    ],
    elementContributions: {},
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: true,
    excludeFromRarityCount: true,
  },
  {
    key: 'TimeStopLastStandBoon',
    label: 'Paid Dues',
    freshOfferRarities: ['Legendary'],
    equippedRarities: ['Legendary'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'HermesWeaponBoon',
          'HermesSpecialBoon',
          'HermesCastDiscountBoon',
          'SprintShieldBoon',
          'SorcerySpeedBoon',
          'DodgeChanceBoon',
          'SlowProjectileBoon',
          'MoneyMultiplierBoon',
          'TimedKillBuffBoon',
          'RestockBoon',
          'LuckyBoon',
        ],
      },
    ],
    elementContributions: {
      Air: 1,
    },
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const hermesGiver = {
  key: 'Hermes',
  label: 'Hermes',
  providerKind: 'hermes',
  denialParticipates: true,
  priorityTraitKeys: [],
  traitKeys: [
    'HermesWeaponBoon',
    'HermesSpecialBoon',
    'HermesCastDiscountBoon',
    'SprintShieldBoon',
    'SorcerySpeedBoon',
    'DodgeChanceBoon',
    'SlowProjectileBoon',
    'MoneyMultiplierBoon',
    'TimedKillBuffBoon',
    'RestockBoon',
    'LuckyBoon',
    'ElementalUnifiedBoon',
    'TimeStopLastStandBoon',
  ],
  rarityPolicy: {
    kind: 'selectable',
    rarities: ['Common', 'Rare', 'Epic'],
  },
} as const satisfies RawTraitGiverDeclaration;
