import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Icarus' fixed-Common field-NPC pool under the supported normal-run baseline. */
export const icarusTraits = [
  {
    key: 'FocusAttackDamageTrait',
    label: 'Ingenious Strike',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [{ kind: 'ordinaryBoonSlotOccupied', slot: 'Melee' }],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'FocusSpecialDamageTrait',
    label: 'Ingenious Flourish',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [{ kind: 'ordinaryBoonSlotOccupied', slot: 'Secondary' }],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'OmegaExplodeBoon',
    label: 'Explosive Intent',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'CastHazardBoon',
    label: 'Hazard Boom',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'BreakInvincibleArmorBoon',
    label: 'Protective Coating',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'BreakExplosiveArmorBoon',
    label: 'Volatile Coating',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SupplyDropBoon',
    label: 'Supply Chain',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'UpgradeHammerBoon',
    label: 'Latest Model',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {},
    isPersistentGodTrait: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    targetedAcquisition: {
      kind: 'upgradeHammerToRank2',
      target: 'upgradableHammer',
    },
  },
] as const satisfies readonly RawTraitDeclaration[];

export const icarusGiver = {
  key: 'Icarus',
  label: 'Icarus',
  providerKind: 'fieldNpc',
  priorityTraitKeys: [],
  traitKeys: [
    'FocusAttackDamageTrait',
    'FocusSpecialDamageTrait',
    'OmegaExplodeBoon',
    'CastHazardBoon',
    'BreakInvincibleArmorBoon',
    'BreakExplosiveArmorBoon',
    'SupplyDropBoon',
    'UpgradeHammerBoon',
  ],
  rarityPolicy: { kind: 'fixed', rarity: 'Common' },
  defaultOffer: {
    options: [
      { traitKey: 'FocusAttackDamageTrait', rarity: 'Common' },
      { traitKey: 'FocusSpecialDamageTrait', rarity: 'Common' },
      { traitKey: 'OmegaExplodeBoon', rarity: 'Common' },
    ],
    selectedOption: 0,
  },
} as const satisfies RawTraitGiverDeclaration;
