import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Medea's fixed-Common Story-room curse choices. */
export const medeaTraits = [
  {
    key: 'HealingOnDeathCurse',
    label: 'Life from the Dead',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'MoneyOnDeathCurse',
    label: 'Wealth from the Dead',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ManaOverTimeCurse',
    label: 'Traces of Spirit',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SpawnDamageCurse',
    label: 'Suffering on Sight',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ArmorPenaltyCurse',
    label: 'Corrosion on Sight',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SlowProjectileCurse',
    label: 'Enfeeblement of Cowards',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'DeathDefianceRetaliateCurse',
    label: 'Malice in Kind',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [
      {
        kind: 'offerContext',
        context: 'deathDefianceConditionMet',
        required: true,
      },
    ],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'NewStatusDamage',
    label: 'Harm for the Afflicted',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const medeaGiver = {
  key: 'Medea',
  label: 'Medea',
  providerKind: 'npc',
  priorityTraitKeys: [],
  traitKeys: [
    'HealingOnDeathCurse',
    'MoneyOnDeathCurse',
    'ManaOverTimeCurse',
    'SpawnDamageCurse',
    'ArmorPenaltyCurse',
    'SlowProjectileCurse',
    'DeathDefianceRetaliateCurse',
    'NewStatusDamage',
  ],
  rarityPolicy: { kind: 'fixed', rarity: 'Common' },
  defaultOffer: {
    options: [
      { traitKey: 'HealingOnDeathCurse', rarity: 'Common' },
      { traitKey: 'MoneyOnDeathCurse', rarity: 'Common' },
      { traitKey: 'ManaOverTimeCurse', rarity: 'Common' },
    ],
    selectedOption: 0,
  },
} as const satisfies RawTraitGiverDeclaration;
