import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Source-closed trait declarations. Giver membership remains separate below. */
export const poseidonTraits = [
  {
    key: 'PoseidonWeaponBoon',
    label: 'Wave Strike',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    equipmentSlot: 'Melee',
  },
  {
    key: 'PoseidonSpecialBoon',
    label: 'Wave Flourish',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    equipmentSlot: 'Secondary',
  },
  {
    key: 'PoseidonCastBoon',
    label: 'Tidal Ring',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    equipmentSlot: 'Ranged',
  },
  {
    key: 'PoseidonSprintBoon',
    label: 'Breaker Rush',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    equipmentSlot: 'Rush',
  },
  {
    key: 'PoseidonManaBoon',
    label: 'Flood Gain',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    equipmentSlot: 'Mana',
  },
  {
    key: 'EncounterStartOffenseBuffBoon',
    label: 'Hydraulic Might',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'RoomRewardBonusBoon',
    label: 'Buried Treasure',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'offerContext',
        context: 'blockGiftBoons',
        required: false,
      },
    ],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: true,
    blockOfferIfPreviouslyPicked: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'FocusDamageShaveBoon',
    label: 'High Surf',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'DoubleRewardBoon',
    label: 'Sea Star',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'PoseidonStatusBoon',
    label: 'Slippery Slope',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: ['PoseidonWeaponBoon', 'PoseidonSpecialBoon'],
      },
    ],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'PoseidonExCastBoon',
    label: 'Geyser Spout',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'AphroditeCastBoon',
          'ApolloCastBoon',
          'DemeterCastBoon',
          'HephaestusCastBoon',
          'HeraCastBoon',
          'HestiaCastBoon',
          'PoseidonCastBoon',
          'ZeusCastBoon',
          'AresCastBoon',
        ],
      },
    ],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'OmegaPoseidonProjectileBoon',
    label: 'Ocean Swell',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ElementalHealthBoon',
    label: 'Water Fitness',
    freshOfferRarities: ['Common'],
    equippedRarities: ['Common'],
    offerRequirements: [
      {
        kind: 'elementCount',
        element: 'Water',
        minimum: 2,
      },
    ],
    elementContributions: {},
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: true,
    excludeFromRarityCount: true,
  },
  {
    key: 'AmplifyConeBoon',
    label: 'King Tide',
    freshOfferRarities: ['Legendary'],
    equippedRarities: ['Legendary'],
    offerRequirements: [
      {
        kind: 'all',
        requirements: [
          {
            kind: 'anyEquippedTrait',
            traitKeys: ['PoseidonWeaponBoon', 'PoseidonSpecialBoon'],
          },
          {
            kind: 'anyEquippedTrait',
            traitKeys: ['PoseidonSprintBoon', 'PoseidonManaBoon', 'PoseidonExCastBoon'],
          },
          {
            kind: 'anyEquippedTrait',
            traitKeys: [
              'EncounterStartOffenseBuffBoon',
              'OmegaPoseidonProjectileBoon',
              'PoseidonStatusBoon',
              'FocusDamageShaveBoon',
            ],
          },
        ],
      },
    ],
    elementContributions: {
      Water: 1,
    },
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'LightningVulnerabilityBoon',
    label: 'Killer Current',
    freshOfferRarities: ['Duo'],
    equippedRarities: ['Duo'],
    offerRequirements: [
      {
        kind: 'all',
        requirements: [
          {
            kind: 'anyEquippedTrait',
            traitKeys: ['PoseidonCastBoon', 'PoseidonStatusBoon'],
          },
          {
            kind: 'anyEquippedTrait',
            traitKeys: [
              'ZeusWeaponBoon',
              'ZeusSpecialBoon',
              'ZeusCastBoon',
              'ZeusSprintBoon',
              'BoltRetaliateBoon',
              'CastAnywhereBoon',
            ],
          },
        ],
      },
    ],
    elementContributions: {
      Aether: 1,
    },
    usesBoonRarity: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const poseidonGiver = {
  key: 'Poseidon',
  label: 'Poseidon',
  providerKind: 'olympian',
  denialParticipates: true,
  priorityTraitKeys: [
    'PoseidonWeaponBoon',
    'PoseidonSpecialBoon',
    'PoseidonCastBoon',
    'PoseidonSprintBoon',
    'PoseidonManaBoon',
  ],
  traitKeys: [
    'PoseidonWeaponBoon',
    'PoseidonSpecialBoon',
    'PoseidonCastBoon',
    'PoseidonSprintBoon',
    'PoseidonManaBoon',
    'EncounterStartOffenseBuffBoon',
    'RoomRewardBonusBoon',
    'FocusDamageShaveBoon',
    'DoubleRewardBoon',
    'PoseidonStatusBoon',
    'PoseidonExCastBoon',
    'OmegaPoseidonProjectileBoon',
    'ElementalHealthBoon',
    'AmplifyConeBoon',
    'LightningVulnerabilityBoon',
    'MoneyDamageBoon',
    'GoodStuffBoon',
    'PoseidonSplashSprintBoon',
    'AllCloseBoon',
    'SteamBoon',
    'MassiveCastBoon',
    'DoubleSplashBoon',
  ],
  rarityPolicy: {
    kind: 'selectable',
    rarities: ['Common', 'Rare', 'Epic'],
  },
} as const satisfies RawTraitGiverDeclaration;
