import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Source-closed trait declarations. Giver membership remains separate below. */
const baseWeaponUpgradeTraits = [
  {
    key: 'StaffDoubleAttackTrait',
    label: 'Wicked Thrasher',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffLongAttackTrait',
    label: 'Extending Wallop',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffDashAttackTrait',
    label: 'Melting Swipe',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffTripleShotTrait',
    label: 'Dual Moonshot',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffJumpSpecialTrait',
    label: 'Shimmering Moonshot',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffExAoETrait',
    label: 'Cross Cataclysm',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffAttackRecoveryTrait',
    label: 'Rapid Thrasher',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffFastSpecialTrait',
    label: 'Rapid Moonshot',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffExHealTrait',
    label: 'Vampiric Cataclysm',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffSecondStageTrait',
    label: 'Giga Moonburst',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffPowershotTrait',
    label: 'Aetheric Moonburst',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffOneWayAttackTrait',
    label: 'Mirrored Thrasher',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffRaiseDeadBigTrait',
    label: 'Soulfilled Ankh',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'StaffRaiseDeadDoubleTrait',
    label: 'Mirrored Ankh',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'StaffLoneShadeRespawnTrait',
    label: 'Scarab Etchings',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'StaffLoneShadeRallyTrait',
    label: 'Pharaoh Etchings',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'DaggerBlinkAoETrait',
    label: 'Sweeping Ambush',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialJumpTrait',
    label: 'Dancing Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialLineTrait',
    label: 'Sureshot Flurry',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerRapidAttackTrait',
    label: 'Rapid Onslaught',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialConsecutiveTrait',
    label: 'Melting Sickle',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerBackstabTrait',
    label: 'Skulking Onslaught',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialReturnTrait',
    label: 'Reaper Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialFanTrait',
    label: 'Hidden Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerAttackFinisherTrait',
    label: 'Final Slice',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerFinalHitTrait',
    label: 'Wicked Onslaught',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerChargeStageSkipTrait',
    label: 'Sudden Flurry',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerDashAttackTripleTrait',
    label: 'Trick Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerBackstabAspect', 'DaggerHomingThrowAspect', 'DaggerBlockAspect'],
    },
  },
  {
    key: 'DaggerTripleBuffTrait',
    label: 'Phantom Brand',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerTripleAspect'],
    },
  },
  {
    key: 'DaggerTripleRepeatWomboTrait',
    label: 'Banshee Brand',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerTripleAspect'],
    },
  },
  {
    key: 'DaggerTripleHomingSpecialTrait',
    label: 'Sinister Pinion',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerTripleAspect'],
    },
  },
  {
    key: 'AxeSpinSpeedTrait',
    label: 'Furious Whirlwind',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeChargedSpecialTrait',
    label: 'Sudden Cleaver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeAttackRecoveryTrait',
    label: 'Rapid Hack',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeMassiveThirdStrikeTrait',
    label: "Executioner's Chop",
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRecoveryAspect', 'AxeArmCastAspect', 'AxePerfectCriticalAspect'],
    },
  },
  {
    key: 'AxeThirdStrikeTrait',
    label: 'Hell Splitter',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRecoveryAspect', 'AxeArmCastAspect', 'AxePerfectCriticalAspect'],
    },
  },
  {
    key: 'AxeRangedWhirlwindTrait',
    label: 'Seething Marauder',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeFreeSpinTrait',
    label: 'Psychic Whirlwind',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeArmorTrait',
    label: 'Melting Shredder',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeBlockEmpowerTrait',
    label: 'Siege Shredder',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeSecondStageTrait',
    label: 'Giga Cleaver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeDashAttackTrait',
    label: 'Dashing Heave',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeSturdyTrait',
    label: 'Colossus Slash',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeRallyFrenzyTrait',
    label: 'Iron Core',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRallyAspect'],
    },
  },
  {
    key: 'AxeRallyFirstStrikeTrait',
    label: 'Heaven Splitter',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRallyAspect'],
    },
  },
  {
    key: 'TorchExSpecialCountTrait',
    label: 'Hidden Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchDetonateAspect', 'TorchAutofireAspect'],
    },
  },
  {
    key: 'TorchSpecialSpeedTrait',
    label: 'Clean Coil',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchAttackSpeedTrait',
    label: 'Furious Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchSprintRecallAspect', 'TorchDetonateAspect'],
    },
  },
  {
    key: 'TorchSpecialLineTrait',
    label: 'Melting Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchSpecialImpactTrait',
    label: 'Enduring Coil',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchMoveSpeedTrait',
    label: 'Mega Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchSplitAttackTrait',
    label: 'Dividing Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchAutofireAspect'],
    },
  },
  {
    key: 'TorchEnhancedAttackTrait',
    label: 'Inverted Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchDiscountExAttackTrait',
    label: 'Sudden Burst',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchSprintRecallAspect', 'TorchDetonateAspect'],
    },
  },
  {
    key: 'TorchLongevityTrait',
    label: 'Rising Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchSprintRecallAspect', 'TorchDetonateAspect'],
    },
  },
  {
    key: 'TorchOrbitPointTrait',
    label: 'Whirling Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchSpinAttackTrait',
    label: 'Leaden Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchAutofireSprintTrait',
    label: 'Demonic Cell',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchAutofireAspect'],
    },
  },
  {
    key: 'LobAmmoTrait',
    label: 'Bolstered Array',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobAmmoMagnetismTrait',
    label: 'Fetching Array',
    offerRequirements: [
      {
        kind: 'notEquippedTrait',
        traitKeys: ['LobPulseAmmoTrait'],
      },
    ],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobRushArmorTrait',
    label: 'Melting Break',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobSpreadShotTrait',
    label: 'Wide Grin',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobSpecialSpeedTrait',
    label: 'Rapid Driver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobSturdySpecialTrait',
    label: 'Colossus Driver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobOneSideTrait',
    label: 'Mega Driver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobInOutSpecialExTrait',
    label: 'Twisting Crash',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobStraightShotTrait',
    label: 'Boosted Ignition',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobPulseAmmoTrait',
    label: 'Volatile Array',
    offerRequirements: [
      {
        kind: 'notEquippedTrait',
        traitKeys: ['LobAmmoMagnetismTrait'],
      },
    ],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobPulseAmmoCollectTrait',
    label: 'Possessed Array',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobGrowthTrait',
    label: 'Looming Ignition',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobGunOverheatTrait',
    label: 'Venerated Relic',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunBounceTrait',
    label: 'Leering Glance',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunSpecialBounceTrait',
    label: 'Runic Driver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunAttackRangeTrait',
    label: 'Garmr Gaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunAttackDoublerTrait',
    label: 'Helheim Charge',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'SuitArmorTrait',
    label: 'Melting Cross',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitAttackSpeedTrait',
    label: 'Rapid Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitAttackSizeTrait',
    label: 'Reaper Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitAttackRangeTrait',
    label: 'Siege Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitFullChargeTrait',
    label: 'World Collider',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitDashAttackTrait',
    label: 'Exhaust Riser',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialJumpTrait',
    label: 'Shimmering Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialStartUpTrait',
    label: 'Furious Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialAutoTrait',
    label: 'Launcher Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialBlockTrait',
    label: 'Counter Barrage',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialDiscountTrait',
    label: 'Sudden Salvo',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialConsecutiveHitTrait',
    label: 'Ripper Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitComboForwardRocketTrait',
    label: 'Elephant Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitComboBlockBuffTrait',
    label: 'Counter Supreme',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitComboDoubleSpecialTrait',
    label: 'Awakened Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitComboDashAttackTrait',
    label: 'Mooncrest Riser',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitPowershotTrait',
    label: 'Chakra Collider',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
] as const satisfies readonly RawTraitDeclaration[];

/**
 * Exact source inventory with a Legendary level. These 65 of the 92 modeled
 * Hammers are the only player-facing Rank II targets for Icarus' Latest Model.
 */
const rankIIHammerTraitKeys: ReadonlySet<string> = new Set([
  'StaffDoubleAttackTrait',
  'StaffLongAttackTrait',
  'StaffJumpSpecialTrait',
  'StaffExAoETrait',
  'StaffAttackRecoveryTrait',
  'StaffFastSpecialTrait',
  'StaffExHealTrait',
  'StaffSecondStageTrait',
  'StaffPowershotTrait',
  'StaffRaiseDeadBigTrait',
  'StaffLoneShadeRespawnTrait',
  'StaffLoneShadeRallyTrait',
  'DaggerBlinkAoETrait',
  'DaggerSpecialJumpTrait',
  'DaggerSpecialLineTrait',
  'DaggerRapidAttackTrait',
  'DaggerBackstabTrait',
  'DaggerSpecialReturnTrait',
  'DaggerSpecialFanTrait',
  'DaggerAttackFinisherTrait',
  'DaggerFinalHitTrait',
  'DaggerChargeStageSkipTrait',
  'DaggerTripleBuffTrait',
  'DaggerTripleRepeatWomboTrait',
  'DaggerTripleHomingSpecialTrait',
  'AxeSpinSpeedTrait',
  'AxeChargedSpecialTrait',
  'AxeAttackRecoveryTrait',
  'AxeThirdStrikeTrait',
  'AxeRangedWhirlwindTrait',
  'AxeBlockEmpowerTrait',
  'AxeSturdyTrait',
  'TorchAttackSpeedTrait',
  'TorchSpecialImpactTrait',
  'TorchMoveSpeedTrait',
  'TorchLongevityTrait',
  'TorchOrbitPointTrait',
  'TorchSpinAttackTrait',
  'TorchAutofireSprintTrait',
  'LobAmmoTrait',
  'LobAmmoMagnetismTrait',
  'LobSpecialSpeedTrait',
  'LobSturdySpecialTrait',
  'LobOneSideTrait',
  'LobStraightShotTrait',
  'LobPulseAmmoTrait',
  'LobPulseAmmoCollectTrait',
  'LobGrowthTrait',
  'LobGunOverheatTrait',
  'LobGunBounceTrait',
  'LobGunSpecialBounceTrait',
  'LobGunAttackRangeTrait',
  'SuitAttackSpeedTrait',
  'SuitAttackSizeTrait',
  'SuitAttackRangeTrait',
  'SuitFullChargeTrait',
  'SuitSpecialJumpTrait',
  'SuitSpecialAutoTrait',
  'SuitSpecialDiscountTrait',
  'SuitSpecialConsecutiveHitTrait',
  'SuitComboForwardRocketTrait',
  'SuitComboBlockBuffTrait',
  'SuitComboDoubleSpecialTrait',
  'SuitComboDashAttackTrait',
  'SuitPowershotTrait',
] as const);

export const weaponUpgradeTraits = baseWeaponUpgradeTraits.map((trait) =>
  Object.freeze({
    ...trait,
    hammerCompatibility: Object.freeze({
      ...trait.hammerCompatibility,
      supportsRankII: rankIIHammerTraitKeys.has(trait.key),
    }),
  }),
) satisfies readonly RawTraitDeclaration[];

export const weaponUpgradeGiver = {
  key: 'WeaponUpgrade',
  label: 'Daedalus Hammer',
  providerKind: 'hammer',
  priorityTraitKeys: [],
  traitKeys: [
    'StaffDoubleAttackTrait',
    'StaffLongAttackTrait',
    'StaffDashAttackTrait',
    'StaffTripleShotTrait',
    'StaffJumpSpecialTrait',
    'StaffExAoETrait',
    'StaffAttackRecoveryTrait',
    'StaffFastSpecialTrait',
    'StaffExHealTrait',
    'StaffSecondStageTrait',
    'StaffPowershotTrait',
    'StaffOneWayAttackTrait',
    'StaffRaiseDeadBigTrait',
    'StaffRaiseDeadDoubleTrait',
    'StaffLoneShadeRespawnTrait',
    'StaffLoneShadeRallyTrait',
    'DaggerBlinkAoETrait',
    'DaggerSpecialJumpTrait',
    'DaggerSpecialLineTrait',
    'DaggerRapidAttackTrait',
    'DaggerSpecialConsecutiveTrait',
    'DaggerBackstabTrait',
    'DaggerSpecialReturnTrait',
    'DaggerSpecialFanTrait',
    'DaggerAttackFinisherTrait',
    'DaggerFinalHitTrait',
    'DaggerChargeStageSkipTrait',
    'DaggerDashAttackTripleTrait',
    'DaggerTripleBuffTrait',
    'DaggerTripleRepeatWomboTrait',
    'DaggerTripleHomingSpecialTrait',
    'AxeSpinSpeedTrait',
    'AxeChargedSpecialTrait',
    'AxeAttackRecoveryTrait',
    'AxeMassiveThirdStrikeTrait',
    'AxeThirdStrikeTrait',
    'AxeRangedWhirlwindTrait',
    'AxeFreeSpinTrait',
    'AxeArmorTrait',
    'AxeBlockEmpowerTrait',
    'AxeSecondStageTrait',
    'AxeDashAttackTrait',
    'AxeSturdyTrait',
    'AxeRallyFrenzyTrait',
    'AxeRallyFirstStrikeTrait',
    'TorchExSpecialCountTrait',
    'TorchSpecialSpeedTrait',
    'TorchAttackSpeedTrait',
    'TorchSpecialLineTrait',
    'TorchSpecialImpactTrait',
    'TorchMoveSpeedTrait',
    'TorchSplitAttackTrait',
    'TorchEnhancedAttackTrait',
    'TorchDiscountExAttackTrait',
    'TorchLongevityTrait',
    'TorchOrbitPointTrait',
    'TorchSpinAttackTrait',
    'TorchAutofireSprintTrait',
    'LobAmmoTrait',
    'LobAmmoMagnetismTrait',
    'LobRushArmorTrait',
    'LobSpreadShotTrait',
    'LobSpecialSpeedTrait',
    'LobSturdySpecialTrait',
    'LobOneSideTrait',
    'LobInOutSpecialExTrait',
    'LobStraightShotTrait',
    'LobPulseAmmoTrait',
    'LobPulseAmmoCollectTrait',
    'LobGrowthTrait',
    'LobGunOverheatTrait',
    'LobGunBounceTrait',
    'LobGunSpecialBounceTrait',
    'LobGunAttackRangeTrait',
    'LobGunAttackDoublerTrait',
    'SuitArmorTrait',
    'SuitAttackSpeedTrait',
    'SuitAttackSizeTrait',
    'SuitAttackRangeTrait',
    'SuitFullChargeTrait',
    'SuitDashAttackTrait',
    'SuitSpecialJumpTrait',
    'SuitSpecialStartUpTrait',
    'SuitSpecialAutoTrait',
    'SuitSpecialBlockTrait',
    'SuitSpecialDiscountTrait',
    'SuitSpecialConsecutiveHitTrait',
    'SuitComboForwardRocketTrait',
    'SuitComboBlockBuffTrait',
    'SuitComboDoubleSpecialTrait',
    'SuitComboDashAttackTrait',
    'SuitPowershotTrait',
  ],
  rarityPolicy: {
    kind: 'none',
  },
} as const satisfies RawTraitGiverDeclaration;
