import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';
import { staffWeaponUpgradeTraits } from './weapon-upgrade-staff';
import { daggerWeaponUpgradeTraits } from './weapon-upgrade-dagger';
import { axeWeaponUpgradeTraits } from './weapon-upgrade-axe';
import { torchWeaponUpgradeTraits } from './weapon-upgrade-torch';
import { lobWeaponUpgradeTraits } from './weapon-upgrade-lob';
import { suitWeaponUpgradeTraits } from './weapon-upgrade-suit';

const weaponUpgradeTraitDeclarations = [
  ...staffWeaponUpgradeTraits,
  ...daggerWeaponUpgradeTraits,
  ...axeWeaponUpgradeTraits,
  ...torchWeaponUpgradeTraits,
  ...lobWeaponUpgradeTraits,
  ...suitWeaponUpgradeTraits,
] satisfies readonly RawTraitDeclaration[];

/**
 * Exact source inventory with a Legendary level. These 65 of the 92 modeled
 * Hammers are the only player-facing Rank II targets for Icarus' Latest Model.
 */
const rankIIHammerTraitKeys: ReadonlySet<string> = new Set([
  'StaffDoubleAttackTrait',
  'StaffLongAttackTrait',
  'StaffJumpSpecialTrait',
  'StaffExAoETrait',
  'StaffAttackRecoveryTrait',
  'StaffFastSpecialTrait',
  'StaffExHealTrait',
  'StaffSecondStageTrait',
  'StaffPowershotTrait',
  'StaffRaiseDeadBigTrait',
  'StaffLoneShadeRespawnTrait',
  'StaffLoneShadeRallyTrait',
  'DaggerBlinkAoETrait',
  'DaggerSpecialJumpTrait',
  'DaggerSpecialLineTrait',
  'DaggerRapidAttackTrait',
  'DaggerBackstabTrait',
  'DaggerSpecialReturnTrait',
  'DaggerSpecialFanTrait',
  'DaggerAttackFinisherTrait',
  'DaggerFinalHitTrait',
  'DaggerChargeStageSkipTrait',
  'DaggerTripleBuffTrait',
  'DaggerTripleRepeatWomboTrait',
  'DaggerTripleHomingSpecialTrait',
  'AxeSpinSpeedTrait',
  'AxeChargedSpecialTrait',
  'AxeAttackRecoveryTrait',
  'AxeThirdStrikeTrait',
  'AxeRangedWhirlwindTrait',
  'AxeBlockEmpowerTrait',
  'AxeSturdyTrait',
  'TorchAttackSpeedTrait',
  'TorchSpecialImpactTrait',
  'TorchMoveSpeedTrait',
  'TorchLongevityTrait',
  'TorchOrbitPointTrait',
  'TorchSpinAttackTrait',
  'TorchAutofireSprintTrait',
  'LobAmmoTrait',
  'LobAmmoMagnetismTrait',
  'LobSpecialSpeedTrait',
  'LobSturdySpecialTrait',
  'LobOneSideTrait',
  'LobStraightShotTrait',
  'LobPulseAmmoTrait',
  'LobPulseAmmoCollectTrait',
  'LobGrowthTrait',
  'LobGunOverheatTrait',
  'LobGunBounceTrait',
  'LobGunSpecialBounceTrait',
  'LobGunAttackRangeTrait',
  'SuitAttackSpeedTrait',
  'SuitAttackSizeTrait',
  'SuitAttackRangeTrait',
  'SuitFullChargeTrait',
  'SuitSpecialJumpTrait',
  'SuitSpecialAutoTrait',
  'SuitSpecialDiscountTrait',
  'SuitSpecialConsecutiveHitTrait',
  'SuitComboForwardRocketTrait',
  'SuitComboBlockBuffTrait',
  'SuitComboDoubleSpecialTrait',
  'SuitComboDashAttackTrait',
  'SuitPowershotTrait',
] as const);

export const weaponUpgradeTraits = weaponUpgradeTraitDeclarations.map((trait) =>
  Object.freeze({
    ...trait,
    hammerCompatibility: Object.freeze({
      ...trait.hammerCompatibility,
      supportsRankII: rankIIHammerTraitKeys.has(trait.key),
    }),
  }),
) satisfies readonly RawTraitDeclaration[];

export const weaponUpgradeGiver = {
  key: 'WeaponUpgrade',
  label: 'Daedalus Hammer',
  providerKind: 'hammer',
  priorityTraitKeys: [],
  traitKeys: [
    'StaffDoubleAttackTrait',
    'StaffLongAttackTrait',
    'StaffDashAttackTrait',
    'StaffTripleShotTrait',
    'StaffJumpSpecialTrait',
    'StaffExAoETrait',
    'StaffAttackRecoveryTrait',
    'StaffFastSpecialTrait',
    'StaffExHealTrait',
    'StaffSecondStageTrait',
    'StaffPowershotTrait',
    'StaffOneWayAttackTrait',
    'StaffRaiseDeadBigTrait',
    'StaffRaiseDeadDoubleTrait',
    'StaffLoneShadeRespawnTrait',
    'StaffLoneShadeRallyTrait',
    'DaggerBlinkAoETrait',
    'DaggerSpecialJumpTrait',
    'DaggerSpecialLineTrait',
    'DaggerRapidAttackTrait',
    'DaggerSpecialConsecutiveTrait',
    'DaggerBackstabTrait',
    'DaggerSpecialReturnTrait',
    'DaggerSpecialFanTrait',
    'DaggerAttackFinisherTrait',
    'DaggerFinalHitTrait',
    'DaggerChargeStageSkipTrait',
    'DaggerDashAttackTripleTrait',
    'DaggerTripleBuffTrait',
    'DaggerTripleRepeatWomboTrait',
    'DaggerTripleHomingSpecialTrait',
    'AxeSpinSpeedTrait',
    'AxeChargedSpecialTrait',
    'AxeAttackRecoveryTrait',
    'AxeMassiveThirdStrikeTrait',
    'AxeThirdStrikeTrait',
    'AxeRangedWhirlwindTrait',
    'AxeFreeSpinTrait',
    'AxeArmorTrait',
    'AxeBlockEmpowerTrait',
    'AxeSecondStageTrait',
    'AxeDashAttackTrait',
    'AxeSturdyTrait',
    'AxeRallyFrenzyTrait',
    'AxeRallyFirstStrikeTrait',
    'TorchExSpecialCountTrait',
    'TorchSpecialSpeedTrait',
    'TorchAttackSpeedTrait',
    'TorchSpecialLineTrait',
    'TorchSpecialImpactTrait',
    'TorchMoveSpeedTrait',
    'TorchSplitAttackTrait',
    'TorchEnhancedAttackTrait',
    'TorchDiscountExAttackTrait',
    'TorchLongevityTrait',
    'TorchOrbitPointTrait',
    'TorchSpinAttackTrait',
    'TorchAutofireSprintTrait',
    'LobAmmoTrait',
    'LobAmmoMagnetismTrait',
    'LobRushArmorTrait',
    'LobSpreadShotTrait',
    'LobSpecialSpeedTrait',
    'LobSturdySpecialTrait',
    'LobOneSideTrait',
    'LobInOutSpecialExTrait',
    'LobStraightShotTrait',
    'LobPulseAmmoTrait',
    'LobPulseAmmoCollectTrait',
    'LobGrowthTrait',
    'LobGunOverheatTrait',
    'LobGunBounceTrait',
    'LobGunSpecialBounceTrait',
    'LobGunAttackRangeTrait',
    'LobGunAttackDoublerTrait',
    'SuitArmorTrait',
    'SuitAttackSpeedTrait',
    'SuitAttackSizeTrait',
    'SuitAttackRangeTrait',
    'SuitFullChargeTrait',
    'SuitDashAttackTrait',
    'SuitSpecialJumpTrait',
    'SuitSpecialStartUpTrait',
    'SuitSpecialAutoTrait',
    'SuitSpecialBlockTrait',
    'SuitSpecialDiscountTrait',
    'SuitSpecialConsecutiveHitTrait',
    'SuitComboForwardRocketTrait',
    'SuitComboBlockBuffTrait',
    'SuitComboDoubleSpecialTrait',
    'SuitComboDashAttackTrait',
    'SuitPowershotTrait',
  ],
  rarityPolicy: {
    kind: 'none',
  },
} as const satisfies RawTraitGiverDeclaration;
