import type { RawTraitDeclaration } from '../traits';

export const axeWeaponUpgradeTraits = [
  {
    key: 'AxeSpinSpeedTrait',
    label: 'Furious Whirlwind',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeChargedSpecialTrait',
    label: 'Sudden Cleaver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeAttackRecoveryTrait',
    label: 'Rapid Hack',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeMassiveThirdStrikeTrait',
    label: "Executioner's Chop",
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRecoveryAspect', 'AxeArmCastAspect', 'AxePerfectCriticalAspect'],
    },
  },
  {
    key: 'AxeThirdStrikeTrait',
    label: 'Hell Splitter',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRecoveryAspect', 'AxeArmCastAspect', 'AxePerfectCriticalAspect'],
    },
  },
  {
    key: 'AxeRangedWhirlwindTrait',
    label: 'Seething Marauder',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeFreeSpinTrait',
    label: 'Psychic Whirlwind',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeArmorTrait',
    label: 'Melting Shredder',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeBlockEmpowerTrait',
    label: 'Siege Shredder',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeSecondStageTrait',
    label: 'Giga Cleaver',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeDashAttackTrait',
    label: 'Dashing Heave',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeSturdyTrait',
    label: 'Colossus Slash',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: [
        'AxeRecoveryAspect',
        'AxeArmCastAspect',
        'AxePerfectCriticalAspect',
        'AxeRallyAspect',
      ],
    },
  },
  {
    key: 'AxeRallyFrenzyTrait',
    label: 'Iron Core',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRallyAspect'],
    },
  },
  {
    key: 'AxeRallyFirstStrikeTrait',
    label: 'Heaven Splitter',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponAxe',
      aspectKeys: ['AxeRallyAspect'],
    },
  },
] satisfies readonly RawTraitDeclaration[];
