import type { RawTraitDeclaration, RawTraitGiverDeclaration } from '../traits';

/** Source-closed trait declarations. Giver membership remains separate below. */
export const zeusTraits = [
  {
    key: 'ZeusWeaponBoon',
    label: 'Heaven Strike',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    ordinaryBoonSlot: 'Melee',
  },
  {
    key: 'ZeusSpecialBoon',
    label: 'Heaven Flourish',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    ordinaryBoonSlot: 'Secondary',
  },
  {
    key: 'ZeusCastBoon',
    label: 'Storm Ring',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    ordinaryBoonSlot: 'Ranged',
  },
  {
    key: 'ZeusSprintBoon',
    label: 'Thunder Rush',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    ordinaryBoonSlot: 'Rush',
  },
  {
    key: 'ZeusManaBoon',
    label: 'Ionic Gain',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    ordinaryBoonSlot: 'Mana',
  },
  {
    key: 'ZeusManaBoltBoon',
    label: 'Power Surge',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'BoltRetaliateBoon',
    label: 'Divine Vengeance',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'CastAnywhereBoon',
    label: 'Lightning Lance',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'AphroditeCastBoon',
          'ApolloCastBoon',
          'DemeterCastBoon',
          'HephaestusCastBoon',
          'HeraCastBoon',
          'HestiaCastBoon',
          'PoseidonCastBoon',
          'ZeusCastBoon',
          'AresCastBoon',
        ],
      },
      {
        kind: 'notEquippedTrait',
        traitKeys: ['CastProjectileBoon', 'HadesCastProjectileBoon', 'CastLobBoon', 'SelfCastBoon'],
      },
    ],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'FocusLightningBoon',
    label: 'Static Shock',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'DoubleBoltBoon',
    label: 'Double Strike',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: [
          'ZeusWeaponBoon',
          'ZeusSpecialBoon',
          'ZeusCastBoon',
          'ZeusSprintBoon',
          'ZeusManaBoltBoon',
          'BoltRetaliateBoon',
          'CastAnywhereBoon',
        ],
      },
    ],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'EchoExpirationBoon',
    label: 'Arc Flash',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: ['ZeusWeaponBoon', 'ZeusSpecialBoon'],
      },
    ],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'LightningDebuffGeneratorBoon',
    label: 'Electric Overload',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic', 'Heroic'],
    offerRequirements: [
      {
        kind: 'anyEquippedTrait',
        traitKeys: ['FocusLightningBoon'],
      },
    ],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'ElementalDamageFloorBoon',
    label: 'Air Quality',
    freshOfferRarities: ['Common', 'Rare', 'Epic'],
    equippedRarities: ['Common', 'Rare', 'Epic'],
    offerRequirements: [
      {
        kind: 'elementCount',
        element: 'Air',
        minimum: 3,
      },
    ],
    elementContributions: {},
    isPersistentGodTrait: true,
    blockStacking: true,
    blockInRunRarify: true,
    excludeFromRarityCount: true,
  },
  {
    key: 'SpawnKillBoon',
    label: 'Shocking Loss',
    freshOfferRarities: ['Legendary'],
    equippedRarities: ['Legendary'],
    offerRequirements: [
      {
        kind: 'all',
        requirements: [
          {
            kind: 'anyEquippedTrait',
            traitKeys: [
              'ZeusWeaponBoon',
              'ZeusSpecialBoon',
              'ZeusCastBoon',
              'ZeusSprintBoon',
              'ZeusManaBoon',
            ],
          },
          {
            kind: 'anyEquippedTrait',
            traitKeys: [
              'FocusLightningBoon',
              'ZeusManaBoltBoon',
              'CastAnywhereBoon',
              'BoltRetaliateBoon',
            ],
          },
          {
            kind: 'anyEquippedTrait',
            traitKeys: ['EchoExpirationBoon', 'DoubleBoltBoon', 'LightningDebuffGeneratorBoon'],
          },
        ],
      },
    ],
    elementContributions: {
      Air: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
  {
    key: 'SuperSacrificeBoonZeus',
    label: "King's Ransom",
    freshOfferRarities: ['Duo'],
    equippedRarities: ['Duo'],
    offerRequirements: [
      {
        kind: 'all',
        requirements: [
          {
            kind: 'anyEquippedTrait',
            traitKeys: ['HeraCastBoon', 'HeraManaBoon', 'HeraSprintBoon'],
          },
          {
            kind: 'anyEquippedTrait',
            traitKeys: [
              'ZeusWeaponBoon',
              'ZeusSpecialBoon',
              'ZeusCastBoon',
              'ZeusSprintBoon',
              'ZeusManaBoon',
            ],
          },
        ],
      },
    ],
    elementContributions: {
      Aether: 1,
    },
    isPersistentGodTrait: true,
    blockStacking: true,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
  },
] as const satisfies readonly RawTraitDeclaration[];

export const zeusGiver = {
  key: 'Zeus',
  label: 'Zeus',
  providerKind: 'olympian',
  priorityTraitKeys: [
    'ZeusWeaponBoon',
    'ZeusSpecialBoon',
    'ZeusCastBoon',
    'ZeusSprintBoon',
    'ZeusManaBoon',
  ],
  traitKeys: [
    'ZeusWeaponBoon',
    'ZeusSpecialBoon',
    'ZeusCastBoon',
    'ZeusSprintBoon',
    'ZeusManaBoon',
    'ZeusManaBoltBoon',
    'BoltRetaliateBoon',
    'CastAnywhereBoon',
    'FocusLightningBoon',
    'DoubleBoltBoon',
    'EchoExpirationBoon',
    'LightningDebuffGeneratorBoon',
    'ElementalDamageFloorBoon',
    'SpawnKillBoon',
    'SuperSacrificeBoonZeus',
    'LightningVulnerabilityBoon',
    'RootStrikeBoon',
    'ApolloSecondStageCastBoon',
    'SprintEchoBoon',
    'EchoBurnBoon',
    'ReboundingSparkBoon',
    'AutoRevengeBoon',
  ],
  rarityPolicy: {
    kind: 'selectable',
    rarities: ['Common', 'Rare', 'Epic'],
  },
  defaultOffer: {
    options: [
      {
        traitKey: 'ZeusWeaponBoon',
        rarity: 'Common',
      },
      {
        traitKey: 'ZeusSpecialBoon',
        rarity: 'Common',
      },
      {
        traitKey: 'ZeusCastBoon',
        rarity: 'Common',
      },
    ],
    selectedOption: 0,
  },
} as const satisfies RawTraitGiverDeclaration;
