export {
  CompletenessContractError,
  evaluateFCompleteness,
  type CompleteFCompletenessResult,
  type FCompletenessResult,
  type IncompleteFCompletenessResult,
} from './completeness';
export {
  executeRoomLifecycle,
  LifecycleExecutionContractError,
  type RoomHistoryFragment,
  type RoomHistoryOrigin,
  type RoomLifecycleEvent,
  type RoomLifecycleExecutionInput,
  type RoomLifecycleProducerInput,
} from './lifecycle';
export {
  composeFHistory,
  FHistoryCompositionContractError,
  FHistoryFoldContractError,
  foldFHistoryEvents,
  type BiomeCompletedHistoryEvent,
  type BiomeCounterResetHistoryEvent,
  type BiomeStartedHistoryEvent,
  type CanonicalFHistory,
  type EncounterHistoryEntry,
  type EnteredRewardStoreHistoryEntry,
  type FHistoryCounters,
  type FHistoryEvent,
  type FHistoryLedgers,
  type FHistoryStateView,
  type FRoomHistoryViews,
  type FTargetGenerationView,
  type RoomAppearanceHistoryEntry,
  type RoomCreatedHistoryEvent,
  type RoomCreationSource,
  type TargetGenerationCompletedHistoryEvent,
} from './history';
export {
  evaluateFRoomGeneration,
  FRoomGenerationContractError,
  type FForcePressureLedgerEntry,
  type FGenerationExclusionReason,
  type FRoomGenerationValidation,
} from './generation';
export {
  evaluateFRewards,
  FRewardSimulationContractError,
  type FRewardBranch,
  type FRewardEvent,
  type FRewardSimulation,
  type FRewardStoreSupportEntry,
} from './rewards';
export {
  LinearMaterializationContractError,
  materializeLinearBiome,
  type CanonicalAuthoredRoom,
  type CanonicalBatch,
  type CanonicalBatchRewardStore,
  type CanonicalBiomeState,
  type CanonicalCompletionRoom,
  type CanonicalLinearBiome,
  type CanonicalPhysicalExit,
  type CanonicalResolvedIncomingReward,
  type CanonicalRoom,
  type CanonicalRoomReference,
  type CanonicalShopEntryState,
  type CanonicalShopOffer,
  type CanonicalTarget,
  type CanonicalTargetContinuation,
  type CanonicalTerminalEntry,
} from './materialization';
export {
  type BiomeEvaluation,
  type CompletenessFindingCode,
  type CompleteBiomeEvaluation,
  type FindingCode,
  type FindingEvidence,
  type FindingEvidenceValue,
  type FindingSeverity,
  type RoomGenerationFindingCode,
  type RewardGenerationFindingCode,
  type IncompleteBiomeEvaluation,
  type SemanticFinding,
  type SimulationPhase,
} from './model';
export {
  ProjectSimulationContractError,
  simulateProject,
  type CompleteFProjectEvaluation,
  type FProjectEvaluation,
  type IncompleteFProjectEvaluation,
  type ProjectEvaluation,
  type ProjectEvaluationSummary,
  type ProjectRouteEvaluation,
  type RouteEvaluationSummary,
  type RouteProcessingHorizon,
} from './project';
