use serde::{Deserialize, Serialize};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::sync::OnceLock;

use crate::game_module_assembly::{AssembledFile, MANIFEST_FILE};

pub struct BundledFile {
    path: &'static str,
    sha256: &'static str,
    bytes: &'static [u8],
}

// Generated by build.rs from game-module/ and stamped with the planner version.
include!(concat!(env!("OUT_DIR"), "/game_module_package.rs"));

#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum PackageSource {
    Bundled,
    Checkout,
}

pub struct PackageFile {
    pub path: String,
    pub sha256: String,
    pub bytes: Cow<'static, [u8]>,
}

pub struct ModulePackage {
    pub version: String,
    pub source: PackageSource,
    pub files: Vec<PackageFile>,
    pub dependencies: Vec<String>,
}

#[derive(Deserialize)]
struct PackageManifest {
    version_number: String,
    #[serde(default)]
    dependencies: Vec<String>,
}

impl ModulePackage {
    fn new(version: &str, source: PackageSource, files: Vec<PackageFile>) -> Result<Self, String> {
        let manifest = files
            .iter()
            .find(|file| file.path == MANIFEST_FILE)
            .ok_or("the game module package has no manifest")?;
        let manifest: PackageManifest = serde_json::from_slice(&manifest.bytes)
            .map_err(|error| format!("the game module manifest is malformed: {error}"))?;
        if manifest.version_number != version {
            return Err("the game module manifest is not stamped with the planner version".into());
        }
        Ok(Self {
            version: version.to_owned(),
            source,
            files,
            dependencies: manifest.dependencies,
        })
    }

    pub fn bundled() -> &'static ModulePackage {
        static PACKAGE: OnceLock<ModulePackage> = OnceLock::new();
        PACKAGE.get_or_init(|| {
            let files = BUNDLED_FILES
                .iter()
                .map(|file| PackageFile {
                    path: file.path.to_owned(),
                    sha256: file.sha256.to_owned(),
                    bytes: Cow::Borrowed(file.bytes),
                })
                .collect();
            ModulePackage::new(BUNDLED_VERSION, PackageSource::Bundled, files)
                .expect("build.rs embeds a valid game module package")
        })
    }

    pub fn from_assembly(
        version: &str,
        source: PackageSource,
        files: Vec<AssembledFile>,
    ) -> Result<Self, String> {
        let files = files
            .into_iter()
            .map(|file| PackageFile {
                path: file.path,
                sha256: file.sha256,
                bytes: Cow::Owned(file.bytes),
            })
            .collect();
        Self::new(version, source, files)
    }

    pub fn hashes(&self) -> BTreeMap<String, String> {
        self.files
            .iter()
            .map(|file| (file.path.clone(), file.sha256.clone()))
            .collect()
    }
}

/// Assembles the module from this build's `game-module/` checkout.
#[cfg(debug_assertions)]
pub fn checkout_package() -> Result<ModulePackage, String> {
    let module_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../../game-module");
    ModulePackage::from_assembly(
        BUNDLED_VERSION,
        PackageSource::Checkout,
        crate::game_module_assembly::assemble(&module_dir, BUNDLED_VERSION)?,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::game_module_assembly;
    use std::fs;
    use std::path::Path;

    fn write(path: &Path, bytes: &[u8]) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, bytes).unwrap();
    }

    fn module_checkout(root: &Path) {
        write(
            &root.join("manifest.template.json"),
            br#"{"namespace":"adamantRunPlanner","name":"Run_Planner","description":"d","dependencies":["adamant-ModpackLib-4.1.0"],"website_url":"https://example.invalid","FullName":"adamantRunPlanner-Run_Planner"}"#,
        );
        for name in ["icon.png", "LICENSE", "README.md"] {
            write(&root.join(name), name.as_bytes());
        }
        write(&root.join("src/main.lua"), b"return true\n");
        write(&root.join("src/mods/a.lua"), b"return 1\n");
        write(&root.join("src/execution-compatibility.json"), b"{}");
    }

    #[test]
    fn assembly_is_deterministic_flattened_and_version_stamped() {
        let root =
            std::env::temp_dir().join(format!("run-planner-assembly-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        module_checkout(&root);
        let first = game_module_assembly::assemble(&root, "2.3.4").unwrap();
        let second = game_module_assembly::assemble(&root, "2.3.4").unwrap();
        let paths: Vec<&str> = first.iter().map(|file| file.path.as_str()).collect();
        assert_eq!(
            paths,
            [
                "LICENSE",
                "README.md",
                "execution-compatibility.json",
                "icon.png",
                "main.lua",
                "manifest.json",
                "mods/a.lua"
            ]
        );
        for (left, right) in first.iter().zip(&second) {
            assert_eq!(left.bytes, right.bytes);
            assert_eq!(left.sha256, game_module_assembly::sha256_hex(&left.bytes));
        }
        let package =
            ModulePackage::from_assembly("2.3.4", PackageSource::Checkout, first).unwrap();
        assert_eq!(package.dependencies, ["adamant-ModpackLib-4.1.0"]);
        assert!(game_module_assembly::assemble(&root, "2.3").is_err());
        write(&root.join("src/LICENSE"), b"collision");
        assert!(game_module_assembly::assemble(&root, "2.3.4").is_err());
        fs::remove_dir_all(&root).unwrap();
    }

    #[test]
    fn embedded_package_is_the_stamped_plugin_folder() {
        let package = ModulePackage::bundled();
        assert_eq!(package.version, BUNDLED_VERSION);
        let manifest: serde_json::Value = serde_json::from_slice(
            &package
                .files
                .iter()
                .find(|file| file.path == MANIFEST_FILE)
                .unwrap()
                .bytes,
        )
        .unwrap();
        assert_eq!(manifest["version_number"], BUNDLED_VERSION);
        assert_eq!(manifest["FullName"], "adamantRunPlanner-Run_Planner");
        for required in [
            "main.lua",
            "execution-compatibility.json",
            "icon.png",
            "LICENSE",
        ] {
            assert!(package.files.iter().any(|file| file.path == required));
        }
        let mut paths: Vec<&str> = package
            .files
            .iter()
            .map(|file| file.path.as_str())
            .collect();
        let listed = paths.clone();
        paths.sort_unstable();
        assert_eq!(paths, listed);
        for file in &package.files {
            assert_eq!(file.sha256, game_module_assembly::sha256_hex(&file.bytes));
        }
        assert!(package
            .dependencies
            .iter()
            .any(|dependency| dependency.starts_with("adamant-ModpackLib-")));
    }
}
