import type { RawEncounterDefinitionDeclaration, RawEncounterSetDeclaration } from '../types';
import {
  athenaEncounterKeys,
  fieldNpcIncomingRewardExclusions,
  heraclesEncounterKeys,
  heraclesIncomingRewardExclusions,
  icarusEncounterKeys,
  supportedFieldNpcEncounterKeys,
} from './shared';

function nonCountingCombat(key: string, label: string) {
  return { key, label, kind: 'combat' as const, countsEncounterDepth: false };
}

export const pEncounterDefinitions = [
  nonCountingCombat('PIntroCombat01', 'Opening combat 01'),
  nonCountingCombat('PIntroCombat02', 'Opening combat 02'),
  nonCountingCombat('PIntroCombat03', 'Opening combat 03'),
  nonCountingCombat('PIntroCombat04', 'Opening combat 04'),
  nonCountingCombat('PIntroCombat05', 'Opening combat 05'),
  nonCountingCombat('PIntroCombat06', 'Opening combat 06'),
  nonCountingCombat('PIntroCombat07', 'Opening combat 07'),
  nonCountingCombat('PIntroCombat08', 'Opening combat 08'),
  nonCountingCombat('PIntroCombat09', 'Opening combat 09'),
  nonCountingCombat('PIntroCombat_DragonQuad', 'Opening dragon combat'),
  nonCountingCombat('PIntroCombat_ZombieFishing', 'Opening fishing combat'),
  nonCountingCombat('PIntroCombat_ZombieQuad', 'Opening zombie combat'),
  nonCountingCombat('PIntroCombat_SapperGate', 'Opening sapper gate combat'),
  nonCountingCombat('PIntroCombat_CrossbowStatues', 'Opening crossbow statues combat'),
  nonCountingCombat('PIntroCombat_SapperOverlook', 'Opening sapper overlook combat'),
  nonCountingCombat('GeneratedP_PreCombat', 'Pre-combat'),
  nonCountingCombat('P_Combat01_PreCombat01', 'Combat 01 pre-combat 01'),
  nonCountingCombat('P_Combat01_PreCombat02', 'Combat 01 pre-combat 02'),
  nonCountingCombat('P_Combat01_PreCombat03', 'Combat 01 pre-combat 03'),
  nonCountingCombat('P_Combat01_PreCombat04', 'Combat 01 pre-combat 04'),
  nonCountingCombat('P_Combat02_PreCombat01', 'Combat 02 pre-combat 01'),
  nonCountingCombat('P_Combat02_PreCombat02', 'Combat 02 pre-combat 02'),
  nonCountingCombat('P_Combat02_PreCombat03', 'Combat 02 pre-combat 03'),
  nonCountingCombat('P_Combat03_PreCombat01', 'Combat 03 pre-combat 01'),
  nonCountingCombat('P_Combat03_PreCombat02', 'Combat 03 pre-combat 02'),
  nonCountingCombat('P_Combat03_PreCombat03', 'Combat 03 pre-combat 03'),
  nonCountingCombat('P_Combat04_PreCombat01', 'Combat 04 pre-combat 01'),
  nonCountingCombat('P_Combat04_PreCombat02', 'Combat 04 pre-combat 02'),
  nonCountingCombat('P_Combat04_PreCombat03', 'Combat 04 pre-combat 03'),
  nonCountingCombat('P_Combat05_PreCombat01', 'Combat 05 pre-combat 01'),
  nonCountingCombat('P_Combat05_PreCombat02', 'Combat 05 pre-combat 02'),
  nonCountingCombat('P_Combat05_PreCombat03', 'Combat 05 pre-combat 03'),
  nonCountingCombat('P_Combat06_PreCombat01', 'Combat 06 pre-combat 01'),
  nonCountingCombat('P_Combat06_PreCombat02', 'Combat 06 pre-combat 02'),
  nonCountingCombat('P_Combat06_PreCombat03', 'Combat 06 pre-combat 03'),
  nonCountingCombat('P_Combat06_PreCombat04', 'Combat 06 pre-combat 04'),
  nonCountingCombat('P_Combat07_PreCombat01', 'Combat 07 pre-combat 01'),
  nonCountingCombat('P_Combat07_PreCombat02', 'Combat 07 pre-combat 02'),
  nonCountingCombat('P_Combat07_PreCombat03', 'Combat 07 pre-combat 03'),
  nonCountingCombat('P_Combat08_PreCombat01', 'Combat 08 pre-combat 01'),
  nonCountingCombat('P_Combat08_PreCombat02', 'Combat 08 pre-combat 02'),
  nonCountingCombat('P_Combat08_PreCombat03', 'Combat 08 pre-combat 03'),
  nonCountingCombat('P_Combat09_PreCombat01', 'Combat 09 pre-combat 01'),
  nonCountingCombat('P_Combat09_PreCombat02', 'Combat 09 pre-combat 02'),
  nonCountingCombat('P_Combat09_PreCombat03', 'Combat 09 pre-combat 03'),
  nonCountingCombat('P_Combat10_PreCombat01', 'Combat 10 pre-combat 01'),
  nonCountingCombat('P_Combat10_PreCombat02', 'Combat 10 pre-combat 02'),
  nonCountingCombat('P_Combat10_PreCombat03', 'Combat 10 pre-combat 03'),
  nonCountingCombat('P_Combat11_PreCombat01', 'Combat 11 pre-combat 01'),
  nonCountingCombat('P_Combat11_PreCombat02', 'Combat 11 pre-combat 02'),
  nonCountingCombat('P_Combat11_PreCombat03', 'Combat 11 pre-combat 03'),
  nonCountingCombat('P_Combat11_PreCombat04', 'Combat 11 pre-combat 04'),
  nonCountingCombat('P_Combat12_PreCombat01', 'Combat 12 pre-combat 01'),
  nonCountingCombat('P_Combat12_PreCombat02', 'Combat 12 pre-combat 02'),
  nonCountingCombat('P_Combat12_PreCombat03', 'Combat 12 pre-combat 03'),
  nonCountingCombat('P_Combat13_PreCombat01', 'Combat 13 pre-combat 01'),
  nonCountingCombat('P_Combat13_PreCombat02', 'Combat 13 pre-combat 02'),
  nonCountingCombat('P_Combat13_PreCombat03', 'Combat 13 pre-combat 03'),
  nonCountingCombat('P_Combat14_PreCombat01', 'Combat 14 pre-combat 01'),
  nonCountingCombat('P_Combat14_PreCombat02', 'Combat 14 pre-combat 02'),
  nonCountingCombat('P_Combat14_PreCombat03', 'Combat 14 pre-combat 03'),
  nonCountingCombat('P_Combat15_PreCombat01', 'Combat 15 pre-combat 01'),
  nonCountingCombat('P_Combat15_PreCombat02', 'Combat 15 pre-combat 02'),
  nonCountingCombat('P_Combat15_PreCombat03', 'Combat 15 pre-combat 03'),
  nonCountingCombat('P_Combat15_PreCombat04', 'Combat 15 pre-combat 04'),
  nonCountingCombat('P_Combat16_PreCombat01', 'Combat 16 pre-combat 01'),
  nonCountingCombat('P_Combat16_PreCombat02', 'Combat 16 pre-combat 02'),
  nonCountingCombat('P_Combat16_PreCombat03', 'Combat 16 pre-combat 03'),
  {
    key: 'GeneratedP',
    label: 'Combat',
    kind: 'combat',
    countsEncounterDepth: true,
    requirements: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 9 } },
  },
  {
    key: 'GeneratedP_Large',
    label: 'Large combat',
    kind: 'combat',
    countsEncounterDepth: true,
    requirements: { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 9 } },
  },
  {
    key: 'HeraclesCombatP',
    label: 'Heracles combat',
    kind: 'combat',
    countsEncounterDepth: true,
    sequenceEffect: { kind: 'terminateSuffix' },
    npcPresentationKey: 'Heracles',
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'currentRoomStructuralTagsInclude', tags: ['Indoor'] },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: heraclesIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: heraclesEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: heraclesEncounterKeys,
          roomWindow: 20,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'IcarusCombatP',
    label: 'Icarus combat',
    kind: 'combat',
    countsEncounterDepth: true,
    npcPresentationKey: 'Icarus',
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        { kind: 'currentRoomStructuralTagsInclude', tags: ['Outdoor'] },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: fieldNpcIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: icarusEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'AthenaCombatP',
    label: 'Athena combat',
    kind: 'combat',
    countsEncounterDepth: true,
    npcPresentationKey: 'Athena',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Athena' },
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: fieldNpcIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: athenaEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'Story_Dionysus_01',
    label: 'Dionysus story',
    kind: 'story',
    countsEncounterDepth: false,
  },
  {
    key: 'MiniBossTalos',
    label: 'Talos',
    kind: 'miniboss',
    countsEncounterDepth: false,
  },
  {
    key: 'MiniBossDragon',
    label: 'Dragon',
    kind: 'miniboss',
    countsEncounterDepth: true,
  },
  {
    key: 'BossPrometheus01',
    label: 'Prometheus',
    kind: 'boss',
    countsEncounterDepth: false,
  },
] as const satisfies readonly RawEncounterDefinitionDeclaration[];

export const pEncounterSets = [
  {
    key: 'POpeningEncounters',
    encounterDefinitionKeys: [
      'PIntroCombat01',
      'PIntroCombat02',
      'PIntroCombat03',
      'PIntroCombat04',
      'PIntroCombat05',
      'PIntroCombat06',
      'PIntroCombat07',
      'PIntroCombat08',
      'PIntroCombat09',
      'PIntroCombat_DragonQuad',
      'PIntroCombat_ZombieFishing',
      'PIntroCombat_ZombieQuad',
      'PIntroCombat_SapperGate',
      'PIntroCombat_CrossbowStatues',
      'Empty',
      'PIntroCombat_SapperOverlook',
    ],
    defaultEncounterDefinitionKey: 'PIntroCombat01',
  },
  {
    key: 'PEncountersIntros',
    encounterDefinitionKeys: ['GeneratedP_PreCombat', 'HeraclesCombatP'],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat01IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat01_PreCombat01',
      'P_Combat01_PreCombat02',
      'P_Combat01_PreCombat03',
      'P_Combat01_PreCombat04',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat02IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat02_PreCombat01',
      'P_Combat02_PreCombat02',
      'P_Combat02_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat03IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat03_PreCombat01',
      'P_Combat03_PreCombat02',
      'P_Combat03_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat04IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat04_PreCombat01',
      'P_Combat04_PreCombat02',
      'P_Combat04_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat05IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat05_PreCombat01',
      'P_Combat05_PreCombat02',
      'P_Combat05_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat06IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat06_PreCombat01',
      'P_Combat06_PreCombat02',
      'P_Combat06_PreCombat03',
      'P_Combat06_PreCombat04',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat07IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat07_PreCombat01',
      'P_Combat07_PreCombat02',
      'P_Combat07_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat08IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat08_PreCombat01',
      'P_Combat08_PreCombat02',
      'P_Combat08_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat09IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat09_PreCombat01',
      'P_Combat09_PreCombat02',
      'P_Combat09_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat10IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat10_PreCombat01',
      'P_Combat10_PreCombat02',
      'P_Combat10_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat11IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat11_PreCombat01',
      'P_Combat11_PreCombat02',
      'P_Combat11_PreCombat03',
      'P_Combat11_PreCombat04',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat12IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat12_PreCombat01',
      'P_Combat12_PreCombat02',
      'P_Combat12_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat13IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat13_PreCombat01',
      'P_Combat13_PreCombat02',
      'P_Combat13_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat14IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat14_PreCombat01',
      'P_Combat14_PreCombat02',
      'P_Combat14_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat15IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat15_PreCombat01',
      'P_Combat15_PreCombat02',
      'P_Combat15_PreCombat03',
      'P_Combat15_PreCombat04',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat16IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat16_PreCombat01',
      'P_Combat16_PreCombat02',
      'P_Combat16_PreCombat03',
    ],
    defaultEncounterDefinitionKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PEncountersDefault',
    encounterDefinitionKeys: ['GeneratedP', 'GeneratedP_Large', 'AthenaCombatP', 'IcarusCombatP'],
    defaultEncounterDefinitionKey: 'GeneratedP',
  },
] as const satisfies readonly RawEncounterSetDeclaration[];
