import { generatedEncounterChoices } from './generated/policies';
import type { RawEncounterDefinitionDeclaration } from './types';
import {
  athenaEncounterKeys,
  fieldNpcIncomingRewardExclusions,
  heraclesEncounterKeys,
  heraclesIncomingRewardExclusions,
  icarusEncounterKeys,
  spawn,
  supportedFieldNpcEncounterKeys,
} from './shared';

export const pEncounterDefinitions = [
  {
    // EncounterData_Opening.lua:982.
    key: 'PIntroCombat01',
    label: 'Opening combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('SentryBot', 3), spawn('ZombieOlympus', 1)]],
  },
  {
    // EncounterData_Opening.lua:1011.
    key: 'PIntroCombat02',
    label: 'Opening combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('SentryBot', 3), spawn('SatyrLancer2', 2)]],
  },
  {
    // EncounterData_Opening.lua:1035.
    key: 'PIntroCombat03',
    label: 'Opening combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('AutomatonEnforcer', 1), spawn('SatyrCrossbow2', 1)]],
  },
  {
    // EncounterData_Opening.lua:1064.
    key: 'PIntroCombat04',
    label: 'Opening combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('AutomatonBeamer', 1), spawn('ZombieOlympus', 7)]],
  },
  {
    // EncounterData_Opening.lua:1093.
    key: 'PIntroCombat05',
    label: 'Opening combat 05',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('AutomatonEnforcer', 2), spawn('HarpyDropper', 3)]],
  },
  {
    // EncounterData_Opening.lua:1122.
    key: 'PIntroCombat06',
    label: 'Opening combat 06',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('Dragon_Elite', 1), spawn('SentryBot', 5)]],
  },
  {
    // EncounterData_Opening.lua:1152.
    key: 'PIntroCombat07',
    label: 'Opening combat 07',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('AutomatonBeamer_Elite', 1), spawn('SatyrLancer2', 3)]],
  },
  {
    // EncounterData_Opening.lua:1181.
    key: 'PIntroCombat08',
    label: 'Opening combat 08',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('SatyrCrossbow2_Elite', 1), spawn('AutomatonEnforcer_Elite', 1)]],
  },
  {
    // EncounterData_Opening.lua:1204.
    key: 'PIntroCombat09',
    label: 'Opening combat 09',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [
      [
        spawn('SatyrSapper', 1),
        spawn('SatyrLancer2', 2),
        spawn('AutomatonBeamer', 1),
        spawn('SentryBot', 2),
      ],
    ],
  },
  {
    // EncounterData_Opening.lua:1287.
    key: 'PIntroCombat_DragonQuad',
    label: 'Opening dragon combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('Dragon', 2)]],
  },
  {
    // EncounterData_Opening.lua:1243.
    key: 'PIntroCombat_ZombieFishing',
    label: 'Opening fishing combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('ZombieOlympus', 1)]],
  },
  {
    // EncounterData_Opening.lua:1265.
    key: 'PIntroCombat_ZombieQuad',
    label: 'Opening zombie combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('ZombieOlympus', 5)]],
  },
  {
    // EncounterData_Opening.lua:1349.
    key: 'PIntroCombat_SapperGate',
    label: 'Opening sapper gate combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('SatyrSapper', 3)]],
  },
  {
    // EncounterData_Opening.lua:1383.
    key: 'PIntroCombat_CrossbowStatues',
    label: 'Opening crossbow statues combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('SatyrCrossbow2', 3)]],
  },
  {
    // EncounterData_Opening.lua:1420.
    key: 'PIntroCombat_SapperOverlook',
    label: 'Opening sapper overlook combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: false,
    skipEndEncounterEffects: false,
    blocksGorgon: false,
    fixedRoster: [[spawn('SatyrSapper', 3)]],
  },
  {
    key: 'GeneratedP_PreCombat',
    customization: [generatedEncounterChoices.GeneratedP_PreCombat],
    label: 'Pre-combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  // Each vignette inherits GeneratedP_PreCombat (P_BaseVignette,
  // EncounterData_Opening.lua:1517); its one fixed wave fills MinWaves = MaxWaves = 1
  // (EncounterData_Generated.lua:1199-1200).
  {
    // EncounterData_Opening.lua:1527.
    key: 'P_Combat01_PreCombat01',
    label: 'Combat 01 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 1), spawn('ZombieOlympus', 4)]],
  },
  {
    // EncounterData_Opening.lua:1559.
    key: 'P_Combat01_PreCombat02',
    label: 'Combat 01 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrLancer2', 3)]],
  },
  {
    // EncounterData_Opening.lua:1606.
    key: 'P_Combat01_PreCombat03',
    label: 'Combat 01 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SentryBot', 8), spawn('ZombieOlympus', 8)]],
  },
  {
    // EncounterData_Opening.lua:1630.
    key: 'P_Combat01_PreCombat04',
    label: 'Combat 01 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('HarpyDropper', 3), spawn('AutomatonBeamer_Elite', 1)]],
  },
  {
    // EncounterData_Opening.lua:1654.
    key: 'P_Combat02_PreCombat01',
    label: 'Combat 02 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SentryBot', 6), spawn('SatyrLancer2', 2)]],
  },
  {
    // EncounterData_Opening.lua:1678.
    key: 'P_Combat02_PreCombat02',
    label: 'Combat 02 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 2), spawn('SatyrLancer2', 2)]],
  },
  {
    // EncounterData_Opening.lua:1710.
    key: 'P_Combat02_PreCombat03',
    label: 'Combat 02 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonBeamer_Elite', 1), spawn('SatyrCrossbow2', 3)]],
  },
  {
    // EncounterData_Opening.lua:1734.
    key: 'P_Combat03_PreCombat01',
    label: 'Combat 03 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 3), spawn('SentryBot', 9)]],
  },
  {
    // EncounterData_Opening.lua:1764.
    key: 'P_Combat03_PreCombat02',
    label: 'Combat 03 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrCrossbow2', 3)]],
  },
  {
    // EncounterData_Opening.lua:1793.
    key: 'P_Combat03_PreCombat03',
    label: 'Combat 03 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrLancer2_Elite', 3)]],
  },
  {
    // EncounterData_Opening.lua:1822.
    key: 'P_Combat04_PreCombat01',
    label: 'Combat 04 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 3)]],
  },
  {
    // EncounterData_Opening.lua:1846.
    key: 'P_Combat04_PreCombat02',
    label: 'Combat 04 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonEnforcer', 3), spawn('ZombieOlympus_Elite', 8)]],
  },
  {
    // EncounterData_Opening.lua:1872.
    key: 'P_Combat04_PreCombat03',
    label: 'Combat 04 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SentryBot', 4), spawn('HarpyDropper', 2)]],
  },
  {
    // EncounterData_Opening.lua:1898.
    key: 'P_Combat05_PreCombat01',
    label: 'Combat 05 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrCrossbow2', 3)]],
  },
  {
    // EncounterData_Opening.lua:1928.
    key: 'P_Combat05_PreCombat02',
    label: 'Combat 05 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon', 1)]],
  },
  {
    // EncounterData_Opening.lua:1958.
    key: 'P_Combat05_PreCombat03',
    label: 'Combat 05 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonBeamer', 2), spawn('SatyrLancer2', 3), spawn('SatyrSapper', 1)]],
  },
  {
    // EncounterData_Opening.lua:1994.
    key: 'P_Combat06_PreCombat01',
    label: 'Combat 06 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonBeamer', 3), spawn('SatyrLancer2', 6)]],
  },
  {
    // EncounterData_Opening.lua:2018.
    key: 'P_Combat06_PreCombat02',
    label: 'Combat 06 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('HarpyDropper', 6)]],
  },
  {
    // EncounterData_Opening.lua:2041.
    key: 'P_Combat06_PreCombat03',
    label: 'Combat 06 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon_Elite', 1), spawn('SentryBot', 1)]],
  },
  {
    // EncounterData_Opening.lua:2072.
    key: 'P_Combat06_PreCombat04',
    label: 'Combat 06 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonEnforcer_Elite', 2), spawn('SatyrLancer2', 3)]],
  },
  {
    // EncounterData_Opening.lua:2096.
    key: 'P_Combat07_PreCombat01',
    label: 'Combat 07 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [
      [spawn('SatyrSapper', 1), spawn('SatyrLancer2', 2), spawn('AutomatonEnforcer_Elite', 1)],
    ],
  },
  {
    // EncounterData_Opening.lua:2125.
    key: 'P_Combat07_PreCombat02',
    label: 'Combat 07 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonBeamer', 2), spawn('ZombieOlympus_Elite', 8)]],
  },
  {
    // EncounterData_Opening.lua:2149.
    key: 'P_Combat07_PreCombat03',
    label: 'Combat 07 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 3)]],
  },
  {
    // EncounterData_Opening.lua:2172.
    key: 'P_Combat08_PreCombat01',
    label: 'Combat 08 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('ZombieOlympus', 10)]],
  },
  {
    // EncounterData_Opening.lua:2195.
    key: 'P_Combat08_PreCombat02',
    label: 'Combat 08 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('HarpyDropper', 3)]],
  },
  {
    // EncounterData_Opening.lua:2218.
    key: 'P_Combat08_PreCombat03',
    label: 'Combat 08 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonEnforcer_Elite', 1), spawn('SatyrLancer2', 4)]],
  },
  {
    // EncounterData_Opening.lua:2242.
    key: 'P_Combat09_PreCombat01',
    label: 'Combat 09 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonEnforcer_Elite', 1), spawn('SatyrLancer2', 3)]],
  },
  {
    // EncounterData_Opening.lua:2266.
    key: 'P_Combat09_PreCombat02',
    label: 'Combat 09 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper_Elite', 2)]],
  },
  {
    // EncounterData_Opening.lua:2289.
    key: 'P_Combat09_PreCombat03',
    label: 'Combat 09 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrCrossbow2', 3)]],
  },
  {
    // EncounterData_Opening.lua:2312.
    key: 'P_Combat10_PreCombat01',
    label: 'Combat 10 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('HarpyDropper', 2), spawn('SatyrSapper', 1)]],
  },
  {
    // EncounterData_Opening.lua:2344.
    key: 'P_Combat10_PreCombat02',
    label: 'Combat 10 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonEnforcer', 3), spawn('ZombieOlympus', 7)]],
  },
  {
    // EncounterData_Opening.lua:2368.
    key: 'P_Combat10_PreCombat03',
    label: 'Combat 10 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 2), spawn('SentryBot_Elite', 7)]],
  },
  {
    // EncounterData_Opening.lua:2392.
    key: 'P_Combat11_PreCombat01',
    label: 'Combat 11 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon_Elite', 1)]],
  },
  {
    // EncounterData_Opening.lua:2422.
    key: 'P_Combat11_PreCombat02',
    label: 'Combat 11 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 1)]],
  },
  {
    // EncounterData_Opening.lua:2445.
    key: 'P_Combat11_PreCombat03',
    label: 'Combat 11 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [
      [spawn('AutomatonBeamer', 1), spawn('SentryBot_Elite', 3), spawn('SatyrLancer2', 3)],
    ],
  },
  {
    // EncounterData_Opening.lua:2474.
    key: 'P_Combat11_PreCombat04',
    label: 'Combat 11 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon_Elite', 1), spawn('SentryBot', 6)]],
  },
  {
    // EncounterData_Opening.lua:2505.
    key: 'P_Combat12_PreCombat01',
    label: 'Combat 12 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SentryBot', 6), spawn('ZombieOlympus', 10)]],
  },
  {
    // EncounterData_Opening.lua:2529.
    key: 'P_Combat12_PreCombat02',
    label: 'Combat 12 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('ZombieOlympus', 10)]],
  },
  {
    // EncounterData_Opening.lua:2577.
    key: 'P_Combat12_PreCombat03',
    label: 'Combat 12 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonEnforcer', 2), spawn('SatyrLancer2_Elite', 3)]],
  },
  {
    // EncounterData_Opening.lua:2601.
    key: 'P_Combat13_PreCombat01',
    label: 'Combat 13 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [
      [spawn('AutomatonBeamer', 2), spawn('AutomatonEnforcer', 2), spawn('SatyrCrossbow2', 3)],
    ],
  },
  {
    // EncounterData_Opening.lua:2630.
    key: 'P_Combat13_PreCombat02',
    label: 'Combat 13 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon', 2)]],
  },
  {
    // EncounterData_Opening.lua:2660.
    key: 'P_Combat13_PreCombat03',
    label: 'Combat 13 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrCrossbow2', 2)]],
  },
  {
    // EncounterData_Opening.lua:2706.
    key: 'P_Combat14_PreCombat01',
    label: 'Combat 14 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [
      [spawn('SentryBot', 6), spawn('AutomatonEnforcer', 1), spawn('ZombieOlympus_Elite', 8)],
    ],
  },
  {
    // EncounterData_Opening.lua:2735.
    key: 'P_Combat14_PreCombat02',
    label: 'Combat 14 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon_Elite', 1)]],
  },
  {
    // EncounterData_Opening.lua:2765.
    key: 'P_Combat14_PreCombat03',
    label: 'Combat 14 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [
      [spawn('AutomatonEnforcer_Elite', 1), spawn('SentryBot', 4), spawn('HarpyDropper_Elite', 3)],
    ],
  },
  {
    // EncounterData_Opening.lua:2794.
    key: 'P_Combat15_PreCombat01',
    label: 'Combat 15 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon', 1)]],
  },
  {
    // EncounterData_Opening.lua:2824.
    key: 'P_Combat15_PreCombat02',
    label: 'Combat 15 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrCrossbow2', 1)]],
  },
  {
    // EncounterData_Opening.lua:2847.
    key: 'P_Combat15_PreCombat03',
    label: 'Combat 15 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('ZombieOlympus', 8), spawn('AutomatonEnforcer', 2)]],
  },
  {
    // EncounterData_Opening.lua:2871.
    key: 'P_Combat15_PreCombat04',
    label: 'Combat 15 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrSapper', 3), spawn('SentryBot_Elite', 5)]],
  },
  {
    // EncounterData_Opening.lua:2895.
    key: 'P_Combat16_PreCombat01',
    label: 'Combat 16 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('SatyrCrossbow2', 2), spawn('SatyrSapper_Elite', 2)]],
  },
  {
    // EncounterData_Opening.lua:2927.
    key: 'P_Combat16_PreCombat02',
    label: 'Combat 16 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('AutomatonBeamer', 2), spawn('SatyrLancer2', 4)]],
  },
  {
    // EncounterData_Opening.lua:2951.
    key: 'P_Combat16_PreCombat03',
    label: 'Combat 16 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
    fixedRoster: [[spawn('Dragon', 2), spawn('SentryBot', 6)]],
  },
  {
    key: 'GeneratedP',
    aetosWaves: [2],
    customization: [generatedEncounterChoices.GeneratedP],
    label: 'Combat',
    kind: 'combat',
    countsEncounterDepth: true,
    hostsGorgon: true,
    canEncounterSkip: false,
    requirements: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 9 } },
  },
  {
    key: 'GeneratedP_Large',
    aetosWaves: [2, 3],
    customization: [generatedEncounterChoices.GeneratedP_Large],
    label: 'Large combat',
    kind: 'combat',
    countsEncounterDepth: true,
    hostsGorgon: true,
    canEncounterSkip: false,
    requirements: { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 9 } },
  },
  {
    key: 'HeraclesCombatP',
    customization: [generatedEncounterChoices.HeraclesCombatP],
    label: 'Heracles combat',
    kind: 'combat',
    countsEncounterDepth: true,
    blocksGorgon: true,
    sequenceEffect: { kind: 'terminateSuffix' },
    npcPresentationKey: 'Heracles',
    npcShoppingProtection: { family: 'Heracles', roomWindow: 10 },
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'currentRoomStructuralTagsInclude', tags: ['Indoor'] },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: heraclesIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: heraclesEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: heraclesEncounterKeys,
          roomWindow: 20,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'IcarusCombatP',
    customization: [generatedEncounterChoices.IcarusCombatP],
    label: 'Icarus combat',
    kind: 'combat',
    countsEncounterDepth: true,
    blocksGorgon: true,
    npcPresentationKey: 'Icarus',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Icarus' },
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        { kind: 'currentRoomStructuralTagsInclude', tags: ['Outdoor'] },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: fieldNpcIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: icarusEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'AthenaCombatP',
    customization: [generatedEncounterChoices.AthenaCombatP],
    label: 'Athena combat',
    kind: 'combat',
    countsEncounterDepth: true,
    blocksGorgon: true,
    canEncounterSkip: false,
    blocksFigLeaf: true,
    blocksKeepsakeSelectionKeys: ['AthenaEncounterKeepsake'],
    npcPresentationKey: 'Athena',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Athena' },
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: fieldNpcIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: athenaEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'Story_Dionysus_01',
    label: 'Dionysus story',
    kind: 'story',
    countsEncounterDepth: false,
    npcPresentationKey: 'Dionysus',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Dionysus' },
  },
  {
    key: 'MiniBossTalos',
    label: 'Talos',
    kind: 'miniboss',
    countsEncounterDepth: false,
    blocksGorgon: true,
  },
  {
    key: 'MiniBossDragon',
    label: 'Dragon',
    kind: 'miniboss',
    countsEncounterDepth: true,
    blocksGorgon: true,
    canEncounterSkip: true,
    blocksFigLeaf: true,
  },
  {
    key: 'BossPrometheus01',
    label: 'Prometheus',
    kind: 'boss',
    countsEncounterDepth: false,
    blocksGorgon: true,
  },
  {
    key: 'BossPrometheus02',
    label: 'Prometheus',
    kind: 'boss',
    countsEncounterDepth: false,
    blocksGorgon: true,
  },
] as const satisfies readonly RawEncounterDefinitionDeclaration[];
