import type { RawEncounterDefinitionDeclaration } from './types';
import {
  athenaEncounterKeys,
  fieldNpcIncomingRewardExclusions,
  heraclesEncounterKeys,
  heraclesIncomingRewardExclusions,
  icarusEncounterKeys,
  supportedFieldNpcEncounterKeys,
} from './shared';

export const pEncounterDefinitions = [
  {
    key: 'PIntroCombat01',
    label: 'Opening combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat02',
    label: 'Opening combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat03',
    label: 'Opening combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat04',
    label: 'Opening combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat05',
    label: 'Opening combat 05',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat06',
    label: 'Opening combat 06',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat07',
    label: 'Opening combat 07',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat08',
    label: 'Opening combat 08',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat09',
    label: 'Opening combat 09',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat_DragonQuad',
    label: 'Opening dragon combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat_ZombieFishing',
    label: 'Opening fishing combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat_ZombieQuad',
    label: 'Opening zombie combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat_SapperGate',
    label: 'Opening sapper gate combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat_CrossbowStatues',
    label: 'Opening crossbow statues combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'PIntroCombat_SapperOverlook',
    label: 'Opening sapper overlook combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'GeneratedP_PreCombat',
    label: 'Pre-combat',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat01_PreCombat01',
    label: 'Combat 01 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat01_PreCombat02',
    label: 'Combat 01 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat01_PreCombat03',
    label: 'Combat 01 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat01_PreCombat04',
    label: 'Combat 01 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat02_PreCombat01',
    label: 'Combat 02 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat02_PreCombat02',
    label: 'Combat 02 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat02_PreCombat03',
    label: 'Combat 02 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat03_PreCombat01',
    label: 'Combat 03 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat03_PreCombat02',
    label: 'Combat 03 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat03_PreCombat03',
    label: 'Combat 03 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat04_PreCombat01',
    label: 'Combat 04 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat04_PreCombat02',
    label: 'Combat 04 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat04_PreCombat03',
    label: 'Combat 04 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat05_PreCombat01',
    label: 'Combat 05 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat05_PreCombat02',
    label: 'Combat 05 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat05_PreCombat03',
    label: 'Combat 05 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat06_PreCombat01',
    label: 'Combat 06 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat06_PreCombat02',
    label: 'Combat 06 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat06_PreCombat03',
    label: 'Combat 06 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat06_PreCombat04',
    label: 'Combat 06 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat07_PreCombat01',
    label: 'Combat 07 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat07_PreCombat02',
    label: 'Combat 07 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat07_PreCombat03',
    label: 'Combat 07 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat08_PreCombat01',
    label: 'Combat 08 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat08_PreCombat02',
    label: 'Combat 08 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat08_PreCombat03',
    label: 'Combat 08 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat09_PreCombat01',
    label: 'Combat 09 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat09_PreCombat02',
    label: 'Combat 09 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat09_PreCombat03',
    label: 'Combat 09 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat10_PreCombat01',
    label: 'Combat 10 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat10_PreCombat02',
    label: 'Combat 10 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat10_PreCombat03',
    label: 'Combat 10 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat11_PreCombat01',
    label: 'Combat 11 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat11_PreCombat02',
    label: 'Combat 11 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat11_PreCombat03',
    label: 'Combat 11 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat11_PreCombat04',
    label: 'Combat 11 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat12_PreCombat01',
    label: 'Combat 12 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat12_PreCombat02',
    label: 'Combat 12 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat12_PreCombat03',
    label: 'Combat 12 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat13_PreCombat01',
    label: 'Combat 13 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat13_PreCombat02',
    label: 'Combat 13 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat13_PreCombat03',
    label: 'Combat 13 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat14_PreCombat01',
    label: 'Combat 14 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat14_PreCombat02',
    label: 'Combat 14 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat14_PreCombat03',
    label: 'Combat 14 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat15_PreCombat01',
    label: 'Combat 15 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat15_PreCombat02',
    label: 'Combat 15 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat15_PreCombat03',
    label: 'Combat 15 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat15_PreCombat04',
    label: 'Combat 15 pre-combat 04',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat16_PreCombat01',
    label: 'Combat 16 pre-combat 01',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat16_PreCombat02',
    label: 'Combat 16 pre-combat 02',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'P_Combat16_PreCombat03',
    label: 'Combat 16 pre-combat 03',
    kind: 'combat',
    countsEncounterDepth: false,
    canEncounterSkip: true,
    skipEndEncounterEffects: true,
    blocksGorgon: true,
  },
  {
    key: 'GeneratedP',
    label: 'Combat',
    kind: 'combat',
    countsEncounterDepth: true,
    hostsGorgon: true,
    canEncounterSkip: false,
    requirements: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 9 } },
  },
  {
    key: 'GeneratedP_Large',
    label: 'Large combat',
    kind: 'combat',
    countsEncounterDepth: true,
    hostsGorgon: true,
    canEncounterSkip: false,
    requirements: { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 9 } },
  },
  {
    key: 'HeraclesCombatP',
    label: 'Heracles combat',
    kind: 'combat',
    countsEncounterDepth: true,
    blocksGorgon: true,
    sequenceEffect: { kind: 'terminateSuffix' },
    npcPresentationKey: 'Heracles',
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'currentRoomStructuralTagsInclude', tags: ['Indoor'] },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: heraclesIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: heraclesEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: heraclesEncounterKeys,
          roomWindow: 20,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'IcarusCombatP',
    label: 'Icarus combat',
    kind: 'combat',
    countsEncounterDepth: true,
    blocksGorgon: true,
    npcPresentationKey: 'Icarus',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Icarus' },
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        { kind: 'currentRoomStructuralTagsInclude', tags: ['Outdoor'] },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: fieldNpcIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: icarusEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'AthenaCombatP',
    label: 'Athena combat',
    kind: 'combat',
    countsEncounterDepth: true,
    blocksGorgon: true,
    canEncounterSkip: false,
    blocksFigLeaf: true,
    blocksKeepsakeSelectionKeys: ['AthenaEncounterKeepsake'],
    npcPresentationKey: 'Athena',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Athena' },
    requirements: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'currentRoomRewardExcludes',
          rewardTypes: fieldNpcIncomingRewardExclusions,
        },
        {
          kind: 'encounterKeyCount',
          scope: 'route',
          encounterKeys: athenaEncounterKeys,
          range: { max: 0 },
        },
        {
          kind: 'previousRoomEncounterKeyCount',
          encounterKeys: supportedFieldNpcEncounterKeys,
          roomWindow: 6,
          range: { max: 0 },
        },
      ],
    },
  },
  {
    key: 'Story_Dionysus_01',
    label: 'Dionysus story',
    kind: 'story',
    countsEncounterDepth: false,
    npcPresentationKey: 'Dionysus',
    traitOfferProducer: { kind: 'traitOffer', giverKey: 'Dionysus' },
  },
  {
    key: 'MiniBossTalos',
    label: 'Talos',
    kind: 'miniboss',
    countsEncounterDepth: false,
    blocksGorgon: true,
  },
  {
    key: 'MiniBossDragon',
    label: 'Dragon',
    kind: 'miniboss',
    countsEncounterDepth: true,
    blocksGorgon: true,
    canEncounterSkip: true,
    blocksFigLeaf: true,
  },
  {
    key: 'BossPrometheus01',
    label: 'Prometheus',
    kind: 'boss',
    countsEncounterDepth: false,
    blocksGorgon: true,
  },
] as const satisfies readonly RawEncounterDefinitionDeclaration[];
