import type { RawEncounterSetDeclaration } from './types';

export const pEncounterSets = [
  {
    key: 'POpeningEncounters',
    encounterDefinitionKeys: [
      'PIntroCombat01',
      'PIntroCombat02',
      'PIntroCombat03',
      'PIntroCombat04',
      'PIntroCombat05',
      'PIntroCombat06',
      'PIntroCombat07',
      'PIntroCombat08',
      'PIntroCombat09',
      'PIntroCombat_DragonQuad',
      'PIntroCombat_ZombieFishing',
      'PIntroCombat_ZombieQuad',
      'PIntroCombat_SapperGate',
      'PIntroCombat_CrossbowStatues',
      'Empty',
      'PIntroCombat_SapperOverlook',
    ],
    defaultAuthoringProfileKey: 'PIntroCombat01',
  },
  {
    key: 'PEncountersIntros',
    encounterDefinitionKeys: ['GeneratedP_PreCombat', 'HeraclesCombatP'],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat01IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat01_PreCombat01',
      'P_Combat01_PreCombat02',
      'P_Combat01_PreCombat03',
      'P_Combat01_PreCombat04',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat02IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat02_PreCombat01',
      'P_Combat02_PreCombat02',
      'P_Combat02_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat03IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat03_PreCombat01',
      'P_Combat03_PreCombat02',
      'P_Combat03_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat04IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat04_PreCombat01',
      'P_Combat04_PreCombat02',
      'P_Combat04_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat05IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat05_PreCombat01',
      'P_Combat05_PreCombat02',
      'P_Combat05_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat06IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat06_PreCombat01',
      'P_Combat06_PreCombat02',
      'P_Combat06_PreCombat03',
      'P_Combat06_PreCombat04',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat07IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat07_PreCombat01',
      'P_Combat07_PreCombat02',
      'P_Combat07_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat08IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat08_PreCombat01',
      'P_Combat08_PreCombat02',
      'P_Combat08_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat09IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat09_PreCombat01',
      'P_Combat09_PreCombat02',
      'P_Combat09_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat10IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat10_PreCombat01',
      'P_Combat10_PreCombat02',
      'P_Combat10_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat11IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat11_PreCombat01',
      'P_Combat11_PreCombat02',
      'P_Combat11_PreCombat03',
      'P_Combat11_PreCombat04',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat12IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat12_PreCombat01',
      'P_Combat12_PreCombat02',
      'P_Combat12_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat13IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat13_PreCombat01',
      'P_Combat13_PreCombat02',
      'P_Combat13_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat14IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat14_PreCombat01',
      'P_Combat14_PreCombat02',
      'P_Combat14_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat15IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat15_PreCombat01',
      'P_Combat15_PreCombat02',
      'P_Combat15_PreCombat03',
      'P_Combat15_PreCombat04',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PCombat16IntroEncounters',
    encounterDefinitionKeys: [
      'GeneratedP_PreCombat',
      'HeraclesCombatP',
      'P_Combat16_PreCombat01',
      'P_Combat16_PreCombat02',
      'P_Combat16_PreCombat03',
    ],
    defaultAuthoringProfileKey: 'GeneratedP_PreCombat',
  },
  {
    key: 'PEncountersDefault',
    encounterDefinitionKeys: ['GeneratedP', 'GeneratedP_Large', 'AthenaCombatP', 'IcarusCombatP'],
    defaultAuthoringProfileKey: 'GeneratedP',
  },
] as const satisfies readonly RawEncounterSetDeclaration[];
