import type { RawRoomDeclaration } from '../types';

export const fRooms = [
  {
    gameName: 'F_Opening01',
    label: 'Opening 01',
    biomeKey: 'F',
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'F_Opening',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Opening02',
    label: 'Opening 02',
    biomeKey: 'F',
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'F_Opening',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Opening03',
    label: 'Opening 03',
    biomeKey: 'F',
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'F_Opening',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat01',
    label: 'Combat 01',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat02',
    label: 'Combat 02',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat03',
    label: 'Combat 03',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat04',
    label: 'Combat 04',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat05',
    label: 'Combat 05',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat06',
    label: 'Combat 06',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat07',
    label: 'Combat 07',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat08',
    label: 'Combat 08',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat09',
    label: 'Combat 09',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 4 },
    },
  },
  {
    gameName: 'F_Combat10',
    label: 'Combat 10',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat11',
    label: 'Combat 11',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat12',
    label: 'Combat 12',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat13',
    label: 'Combat 13',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat14',
    label: 'Combat 14',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat15',
    label: 'Combat 15',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat16',
    label: 'Combat 16',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat17',
    label: 'Combat 17',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat18',
    label: 'Combat 18',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat19',
    label: 'Combat 19',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat20',
    label: 'Combat 20',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat21',
    label: 'Combat 21',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat22',
    label: 'Combat 22',
    biomeKey: 'F',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_MiniBoss01',
    label: 'Root-Stalker',
    biomeKey: 'F',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'F_MiniBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['F_MiniBoss02', 'F_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_MiniBoss02',
    label: 'Shadow-Spiller',
    biomeKey: 'F',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'F_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['F_MiniBoss01', 'F_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_MiniBoss03',
    label: 'Phantom',
    biomeKey: 'F',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'F_MiniBoss03',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['F_MiniBoss01', 'F_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_Story01',
    label: 'Arachne',
    biomeKey: 'F',
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: { kind: 'fixed', rewardType: 'Story', producerLifecycleKey: 'RoomReward' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Story',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 8 },
    },
  },
  {
    gameName: 'F_Reprieve01',
    label: 'Fountain',
    biomeKey: 'F',
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'HealthRestore',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 8 },
    },
  },
  {
    gameName: 'F_Shop01',
    label: 'Midshop',
    biomeKey: 'F',
    kind: 'Shop',
    mode: { kind: 'authored', templateKey: 'Shop' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Shop',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4, max: 6 } },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_PreBoss01',
    label: 'Preboss',
    biomeKey: 'F',
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'ForkedPreboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    entryOfferPolicy: {
      kind: 'shopThenFillRemainingExits',
      freeReward: {
        kind: 'countedChoice',
        storeKeys: ['RunProgress'],
        eligibleRewardTypes: [],
        ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
        producerLifecycleKey: 'RoomReward',
      },
      maxFreeRewards: 1,
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Preboss',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 10 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 10, deadline: 10 },
  },
  {
    gameName: 'F_Boss01',
    label: 'Hecate',
    biomeKey: 'F',
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'F_Boss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_PostBoss01',
    label: 'Postboss',
    biomeKey: 'F',
    kind: 'PostBoss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'F_PostBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
