import type { RawRoomDeclaration } from '../types';

export const gRooms = [
  {
    gameName: 'G_Intro',
    label: 'Entrance',
    biomeStepKey: 'Underworld_G',
    kind: 'Intro',
    templateKey: 'FixedIntro',
    exits: [{ index: 1, targetMode: 'generated', type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'none' },
    encounterProfileKey: 'FixedIntro',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 0, deadline: 1 },
  },
  {
    gameName: 'G_Combat01',
    label: 'Combat 01',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat02',
    label: 'Combat 02',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'G_Combat03',
    label: 'Combat 03',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat04',
    label: 'Combat 04',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat05',
    label: 'Combat 05',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat06',
    label: 'Combat 06',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat07',
    label: 'Combat 07',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat08',
    label: 'Combat 08',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat09',
    label: 'Combat 09',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat10',
    label: 'Combat 10',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat11',
    label: 'Combat 11',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat12',
    label: 'Combat 12',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat13',
    label: 'Combat 13',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat14',
    label: 'Combat 14',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat15',
    label: 'Combat 15',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat16',
    label: 'Combat 16',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat17',
    label: 'Combat 17',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat18',
    label: 'Combat 18',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 3 } },
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { max: 2 } },
      ],
    },
  },
  {
    gameName: 'G_Combat19',
    label: 'Combat 19',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat20',
    label: 'Combat 20',
    biomeStepKey: 'Underworld_G',
    kind: 'Combat',
    templateKey: 'StandardCombat',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 3, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'StandardCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_MiniBoss01',
    label: 'Deep Serpent',
    biomeStepKey: 'Underworld_G',
    kind: 'Miniboss',
    templateKey: 'Miniboss',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'G_MiniBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['G_MiniBoss02', 'G_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'G_MiniBoss02',
    label: 'King Vermin',
    biomeStepKey: 'Underworld_G',
    kind: 'Miniboss',
    templateKey: 'Miniboss',
    exits: [{ index: 1, targetMode: 'generated', type: 'OceanusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'G_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['G_MiniBoss01', 'G_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'G_MiniBoss03',
    label: 'Hellifish',
    biomeStepKey: 'Underworld_G',
    kind: 'Miniboss',
    templateKey: 'Miniboss',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
    },
    encounterProfileKey: 'G_MiniBoss03',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['G_MiniBoss01', 'G_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'G_Story01',
    label: 'Narcissus',
    biomeStepKey: 'Underworld_G',
    kind: 'Story',
    templateKey: 'Story',
    exits: [{ index: 1, targetMode: 'generated', type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'fixed', rewardType: 'Story' },
    encounterProfileKey: 'Story',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 3, max: 6 },
    },
  },
  {
    gameName: 'G_Reprieve01',
    label: 'Fountain',
    biomeStepKey: 'Underworld_G',
    kind: 'Reprieve',
    templateKey: 'Fountain',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      defaultStoreKey: 'RunProgress',
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
    },
    encounterProfileKey: 'HealthRestore',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 6 },
    },
  },
  {
    gameName: 'G_Shop01',
    label: 'Midshop',
    biomeStepKey: 'Underworld_G',
    kind: 'Shop',
    templateKey: 'Shop',
    exits: [
      { index: 1, targetMode: 'generated', type: 'OceanusExitDoor' },
      { index: 2, targetMode: 'generated', type: 'OceanusExitDoor' },
    ],
    incomingReward: { kind: 'shop', shopProfileKey: 'WorldShop' },
    encounterProfileKey: 'Shop',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3, max: 5 } },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 6 },
  },
  {
    gameName: 'G_PreBoss01',
    label: 'Preboss',
    biomeStepKey: 'Underworld_G',
    kind: 'Preboss',
    templateKey: 'ForkedPreboss',
    exits: [{ index: 1, targetMode: 'fixedBoss', type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'shop', shopProfileKey: 'WorldShop' },
    entryOfferPolicy: {
      kind: 'shopThenFillRemainingExits',
      freeReward: {
        kind: 'countedChoice',
        storeKeys: ['RunProgress'],
        eligibleRewardTypes: [],
        ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
      },
      maxFreeRewards: 2,
    },
    encounterProfileKey: 'Preboss',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 8 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 8, deadline: 8 },
  },
] as const satisfies readonly RawRoomDeclaration[];
