import type { RawRoomDeclaration } from '../types';

export const iRooms = [
  {
    gameName: 'I_Intro',
    label: 'Entrance',
    biomeKey: 'I',
    kind: 'Intro',
    mode: { kind: 'derived', classification: 'fixedEntry' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'FixedIntro',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Story01',
    label: 'Hades',
    biomeKey: 'I',
    kind: 'Story',
    mode: { kind: 'derived', classification: 'fixedEntry' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'fixed', rewardType: 'Story', producerLifecycleKey: 'RoomReward' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'I_Story01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
  },
  {
    gameName: 'I_Combat01',
    label: 'Combat 01',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat02',
    label: 'Combat 02',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat03',
    label: 'Combat 03',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat04',
    label: 'Combat 04',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat05',
    label: 'Combat 05',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat06',
    label: 'Combat 06',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat07',
    label: 'Combat 07',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat08',
    label: 'Combat 08',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat09',
    label: 'Combat 09',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat10',
    label: 'Combat 10',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat11',
    label: 'Combat 11',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat12',
    label: 'Combat 12',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat13',
    label: 'Combat 13',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat14',
    label: 'Combat 14',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat15',
    label: 'Combat 15',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat16',
    label: 'Combat 16',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat17',
    label: 'Combat 17',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat18',
    label: 'Combat 18',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat19',
    label: 'Combat 19',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat20',
    label: 'Combat 20',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat21',
    label: 'Combat 21',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat22',
    label: 'Combat 22',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat23',
    label: 'Combat 23',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat24',
    label: 'Combat 24',
    biomeKey: 'I',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'ClockworkCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 5 } },
  },

  {
    gameName: 'I_Reprieve01',
    label: 'Fountain',
    biomeKey: 'I',
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'HealthRestore',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        { kind: 'clockworkNonGoalCapacity', reserve: 1 },
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
  },
  {
    gameName: 'I_MiniBoss01',
    label: 'The Verminancer',
    biomeKey: 'I',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      defaultRewardTypesByStore: { TartarusRewards: 'Boon' },
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'I_MiniBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['I_MiniBoss02'],
          range: { max: 0 },
        },
        { kind: 'clockworkNonGoalCapacity', reserve: 1 },
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 7 },
  },
  {
    gameName: 'I_MiniBoss02',
    label: 'Goldwrath',
    biomeKey: 'I',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      defaultRewardTypesByStore: { TartarusRewards: 'Boon' },
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'I_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['I_MiniBoss01'],
          range: { max: 0 },
        },
        { kind: 'clockworkNonGoalCapacity', reserve: 1 },
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 7 },
  },
  {
    gameName: 'I_PreBoss02',
    label: 'Preboss',
    biomeKey: 'I',
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'ShopPreboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'I_WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'Preboss',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsPerRoom: 1 },
    eligibility: { kind: 'clockworkGoalsRemaining', range: { max: 0 } },
    force: { kind: 'always' },
  },
  {
    gameName: 'I_Boss01',
    label: 'Chronos',
    biomeKey: 'I',
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'I_Boss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_PostBoss01',
    label: 'Postboss',
    biomeKey: 'I',
    kind: 'PostBoss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'I_PostBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
