import type { RawRoomDeclaration } from '../types';

const soulPylon = {
  key: 'SoulPylon',
  spawnTiming: 'roomEntry',
  completionRequirement: 'destroyBeforeExit',
} as const;

export const nRooms = [
  {
    gameName: 'N_Opening01',
    label: 'Opening',
    biomeKey: 'N',
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    structuralTags: [],
    exits: [{ index: 1, type: 'N_OpeningDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'N_Opening',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_PreHub01',
    label: 'Pre-Hub',
    biomeKey: 'N',
    kind: 'PreHub',
    mode: { kind: 'authored', templateKey: 'FixedPreHub' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'N_PreHub',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Hub',
    label: 'Ephyra Hub',
    biomeKey: 'N',
    kind: 'Hub',
    mode: { kind: 'derived', classification: 'hub' },
    structuralTags: [],
    exits: [],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'FixedIntro',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Combat01',
    label: 'Combat 01',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat02',
    label: 'Combat 02',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub01',
            physicalDoorId: 558353,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub03',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat03',
    label: 'Combat 03',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub04',
            physicalDoorId: 558353,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat04',
    label: 'Combat 04',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub02',
            physicalDoorId: 558834,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub06',
            physicalDoorId: 558410,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat05',
    label: 'Combat 05',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub02',
            physicalDoorId: 558354,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub07',
            physicalDoorId: 558378,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub03',
            physicalDoorId: 558379,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat06',
    label: 'Combat 06',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub10',
            physicalDoorId: 558378,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub05',
            physicalDoorId: 560794,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat07',
    label: 'Combat 07',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat08',
    label: 'Combat 08',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat09',
    label: 'Combat 09',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub11',
            physicalDoorId: 566392,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub08',
            physicalDoorId: 566536,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub14',
            physicalDoorId: 566394,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat10',
    label: 'Combat 10',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub05',
            physicalDoorId: 558352,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub09',
            physicalDoorId: 567015,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat11',
    label: 'Combat 11',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub01',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat12',
    label: 'Combat 12',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['WeaponUpgrade', 'HermesUpgrade'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub09',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub10',
            physicalDoorId: 566544,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub07',
            physicalDoorId: 566545,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat13',
    label: 'Combat 13',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat14',
    label: 'Combat 14',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat15',
    label: 'Combat 15',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub03',
            physicalDoorId: 657623,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat16',
    label: 'Combat 16',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub04',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat17',
    label: 'Combat 17',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['WeaponUpgrade', 'HermesUpgrade'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub11',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat18',
    label: 'Combat 18',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub12',
            physicalDoorId: 658853,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat19',
    label: 'Combat 19',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat20',
    label: 'Combat 20',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub06',
            physicalDoorId: 659508,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat21',
    label: 'Combat 21',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat22',
    label: 'Combat 22',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub14',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub02',
            physicalDoorId: 661338,
            availabilityRank: 2,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat23',
    label: 'Combat 23',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub12',
            physicalDoorId: 755971,
            availabilityRank: 3,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub13',
            physicalDoorId: 755184,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub15',
            physicalDoorId: 755185,
            availabilityRank: 2,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_MiniBoss01',
    label: 'Satyr Champion',
    biomeKey: 'N',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      defaultRewardTypesByStore: { RunProgress: 'Boon' },
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'N_MiniBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_MiniBoss02',
    label: 'Erymanthian Boar',
    biomeKey: 'N',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      defaultRewardTypesByStore: { RunProgress: 'Boon' },
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'N_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Sub01',
    label: 'Side Room 01',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub02',
    label: 'Side Room 02',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub03',
    label: 'Side Room 03',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub04',
    label: 'Side Room 04',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub05',
    label: 'Side Room 05',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub06',
    label: 'Side Room 06',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub07',
    label: 'Side Room 07',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub08',
    label: 'Side Room 08',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub09',
    label: 'Side Room 09',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoomHard',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub10',
    label: 'Side Room 10',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoomHard',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub11',
    label: 'Side Room 11',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoomHard',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub12',
    label: 'Side Room 12',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub13',
    label: 'Side Room 13',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub14',
    label: 'Side Room 14',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoomHard',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub15',
    label: 'Side Room 15',
    biomeKey: 'N',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'EphyraSideRoom',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_PreBoss01',
    label: 'Preboss',
    biomeKey: 'N',
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'ShopPreboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
      additionalOptionRequirements: {
        WeaponUpgradeDropEarly: {
          kind: 'rewardLookupExcludes',
          lookupKey: 'hubRewardLookup',
          rewardType: 'WeaponUpgrade',
        },
        SpellDrop: {
          kind: 'rewardLookupExcludes',
          lookupKey: 'hubRewardLookup',
          rewardType: 'SpellDrop',
        },
      },
    },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'Preboss',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Boss01',
    label: 'Polyphemus',
    biomeKey: 'N',
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'N_Boss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_PostBoss01',
    label: 'Postboss',
    biomeKey: 'N',
    kind: 'PostBoss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'N_PostBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] satisfies readonly RawRoomDeclaration[];
