import type { RawRoomDeclaration } from '../types';

export const pRooms = [
  {
    gameName: 'P_Intro',
    label: 'Entrance',
    biomeKey: 'P',
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusOutdoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'FixedIntro',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat01',
    label: 'Combat 01',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'P_Combat02',
    label: 'Combat 02',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat03',
    label: 'Combat 03',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 4 },
    },
  },
  {
    gameName: 'P_Combat04',
    label: 'Combat 04',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat05',
    label: 'Combat 05',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat06',
    label: 'Combat 06',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat07',
    label: 'Combat 07',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat08',
    label: 'Combat 08',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat09',
    label: 'Combat 09',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat10',
    label: 'Combat 10',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat11',
    label: 'Combat 11',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat12',
    label: 'Combat 12',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat13',
    label: 'Combat 13',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat14',
    label: 'Combat 14',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat15',
    label: 'Combat 15',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat16',
    label: 'Combat 16',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat17',
    label: 'Combat 17',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'P_Combat18',
    label: 'Combat 18',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'P_Combat19',
    label: 'Combat 19',
    biomeKey: 'P',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'OlympusCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Story01',
    label: 'Dionysus',
    biomeKey: 'P',
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Story',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 3 } },
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 7 } },
      ],
    },
  },
  {
    gameName: 'P_Reprieve01',
    label: 'Fountain',
    biomeKey: 'P',
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'HealthRestore',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 7 },
    },
  },
  {
    gameName: 'P_Shop01',
    label: 'Midshop',
    biomeKey: 'P',
    kind: 'Shop',
    mode: { kind: 'authored', templateKey: 'Shop' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Shop',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 5 } },
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 7 } },
      ],
    },
  },
  {
    gameName: 'P_MiniBoss01',
    label: 'Talos',
    biomeKey: 'P',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'P_MiniBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['P_MiniBoss02'],
          range: { max: 0 },
        },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'P_MiniBoss02',
    label: 'Mega-Dracon',
    biomeKey: 'P',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: ['Indoor'],
    exits: [{ index: 1, type: 'OlympusOutdoorExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'P_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['P_MiniBoss01'],
          range: { max: 0 },
        },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'P_PreBoss01',
    label: 'Preboss',
    biomeKey: 'P',
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'ForkedPreboss' },
    structuralTags: ['Indoor', 'Outdoor'],
    exits: [{ index: 1, type: 'OlympusIndoorExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    entryOfferPolicy: {
      kind: 'shopThenFillRemainingExits',
      freeReward: {
        kind: 'countedChoice',
        storeKeys: ['RunProgress'],
        eligibleRewardTypes: [],
        ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
        producerLifecycleKey: 'RoomReward',
      },
      maxFreeRewards: 1,
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Preboss',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 9 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 9, deadline: 9 },
  },
  {
    gameName: 'P_Boss01',
    label: 'Prometheus',
    biomeKey: 'P',
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: ['Indoor', 'Outdoor'],
    exits: [{ index: 1, type: 'OlympusIndoorExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'P_Boss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_PostBoss01',
    label: 'Postboss',
    biomeKey: 'P',
    kind: 'PostBoss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: ['Indoor', 'Outdoor'],
    exits: [{ index: 1, type: 'OlympusOutdoorExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'P_PostBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
