import type { RawArcanaCardDeclaration, RawFearVowDeclaration } from './types';

const card = (
  key: string,
  label: string,
  traitKey: string,
  row: number,
  column: number,
  graspCost: number,
  activation: RawArcanaCardDeclaration['activation'] = { kind: 'manual' },
  postBossActivationCounts?: RawArcanaCardDeclaration['postBossActivationCounts'],
  fatedIncompatible = false,
  artificerCapacityByRarity?: RawArcanaCardDeclaration['artificerCapacityByRarity'],
  boonRarityContributions?: RawArcanaCardDeclaration['boonRarityContributions'],
): RawArcanaCardDeclaration => ({
  key,
  label,
  traitKey,
  row,
  column,
  graspCost,
  activation,
  permanentRank: 3,
  ...(postBossActivationCounts === undefined ? {} : { postBossActivationCounts }),
  fatedIncompatible,
  ...(artificerCapacityByRarity === undefined ? {} : { artificerCapacityByRarity }),
  ...(boonRarityContributions === undefined ? {} : { boonRarityContributions }),
});
const automatic = (
  rule: Exclude<RawArcanaCardDeclaration['activation'], { readonly kind: 'manual' }>['rule'],
) => ({ kind: 'automatic' as const, rule });

export const arcanaCards = [
  card('ChanneledCast', 'The Sorceress', 'ChannelSlowMetaUpgrade', 1, 1, 1),
  card('HealthRegen', 'The Wayward Son', 'DoorHealMetaUpgrade', 1, 2, 1),
  card('LowManaDamageBonus', 'The Huntress', 'LowManaDamageMetaupgrade', 1, 3, 2),
  card('CastCount', 'Eternity', 'CastDamageMetaUpgrade', 1, 4, 3),
  card(
    'SorceryRegenUpgrade',
    'The Moon',
    'SorceryRegenMetaUpgrade',
    1,
    5,
    0,
    automatic({ kind: 'adjacentActive' }),
  ),
  card('CastBuff', 'The Furies', 'InsideCastBuffMetaUpgrade', 2, 1, 2),
  card('BonusHealth', 'Persistence', 'HealthManaBonusMetaUpgrade', 2, 2, 2),
  card('BonusDodge', 'The Messenger', 'DodgeBonusMetaUpgrade', 2, 3, 1),
  card('ManaOverTime', 'The Unseen', 'ManaOverTimeMetaUpgrade', 2, 4, 5),
  card('MagicCrit', 'Night', 'MagicCritMetaUpgrade', 2, 5, 2),
  card('SprintShield', 'The Swift Runner', 'SprintShieldMetaUpgrade', 3, 1, 1),
  card('LastStand', 'Death', 'LastStandSlowTimeMetaUpgrade', 3, 2, 4),
  card(
    'MaxHealthPerRoom',
    'The Centaur',
    'ChamberHealthMetaUpgrade',
    3,
    3,
    0,
    automatic({ kind: 'manualCostsOneThroughFive' }),
  ),
  card('StatusVulnerability', 'Origination', 'EffectVulnerabilityMetaUpgrade', 3, 4, 5),
  card('ChanneledBlock', 'The Lovers', 'BossShieldMetaUpgrade', 3, 5, 3),
  card(
    'DoorReroll',
    'The Enchantress',
    'DoorRerollMetaUpgrade',
    4,
    1,
    3,
    { kind: 'manual' },
    undefined,
    true,
  ),
  card('StartingGold', 'The Boatman', 'StartingGoldMetaUpgrade', 4, 2, 5),
  card(
    'MetaToRunUpgrade',
    'The Artificer',
    'MetaToRunMetaUpgrade',
    4,
    3,
    3,
    { kind: 'manual' },
    undefined,
    false,
    { Common: 1, Rare: 2, Epic: 3, Heroic: 4 },
  ),
  card(
    'RarityBoost',
    'Excellence',
    'RarityBoostMetaUpgrade',
    4,
    4,
    5,
    { kind: 'manual' },
    undefined,
    false,
    undefined,
    {
      Common: { additive: { Rare: 0.3 }, multiplicative: { Legendary: 1.3 } },
      Rare: { additive: { Rare: 0.4 }, multiplicative: { Legendary: 1.4 } },
      Epic: { additive: { Rare: 0.5 }, multiplicative: { Legendary: 1.5 } },
      Heroic: { additive: { Rare: 0.6 }, multiplicative: { Legendary: 1.6 } },
    },
  ),
  card(
    'BonusRarity',
    'The Queen',
    'DuoRarityBoostMetaUpgrade',
    4,
    5,
    0,
    automatic({ kind: 'manualCostMultiplicityAtMost', maximum: 2 }),
    undefined,
    false,
    undefined,
    {
      Common: { additive: { Duo: 0.06 } },
      Rare: { additive: { Duo: 0.08 } },
      Epic: { additive: { Duo: 0.1 } },
      Heroic: { additive: { Duo: 0.12 } },
    },
  ),
  card(
    'TradeOff',
    'The Fates',
    'RerollTradeOffMetaUpgrade',
    5,
    1,
    0,
    automatic({ kind: 'surroundingCellsActive' }),
    undefined,
    true,
  ),
  card(
    'ScreenReroll',
    'The Champions',
    'PanelRerollMetaUpgrade',
    5,
    2,
    4,
    { kind: 'manual' },
    undefined,
    true,
  ),
  card('LowHealthBonus', 'Strength', 'LowHealthBuffMetaUpgrade', 5, 3, 4),
  card(
    'EpicRarityBoost',
    'Divinity',
    'EpicRarityBoostMetaUpgrade',
    5,
    4,
    0,
    automatic({ kind: 'completeOtherRowOrColumn' }),
    undefined,
    false,
    undefined,
    {
      Common: { additive: { Epic: 0.05 } },
      Rare: { additive: { Epic: 0.1 } },
      Epic: { additive: { Epic: 0.15 } },
      Heroic: { additive: { Epic: 0.2 } },
    },
  ),
  card(
    'CardDraw',
    'Judgment',
    'BossProgressionMetaUpgrade',
    5,
    5,
    0,
    automatic({ kind: 'manualCardCount', minimum: 1, maximum: 3 }),
    { Common: 3, Rare: 4, Epic: 5, Heroic: 6 },
  ),
] as const;

const vow = (
  key: string,
  label: string,
  incrementalFear: readonly number[],
  circeRemovable = true,
  effect?: RawFearVowDeclaration['effect'],
): RawFearVowDeclaration => ({
  key,
  label,
  incrementalFear,
  circeRemovable,
  ...(effect === undefined ? {} : { effect }),
});
export const fearVows = [
  vow('HealingReductionShrineUpgrade', 'Vow of Scars', [1, 1, 2]),
  vow('ShopPricesShrineUpgrade', 'Vow of Debt', [1, 1]),
  vow('EnemyHealthShrineUpgrade', 'Vow of Grit', [1, 1, 1]),
  vow('EnemyDamageShrineUpgrade', 'Vow of Pain', [1, 2, 2]),
  vow('EnemySpeedShrineUpgrade', 'Vow of Frenzy', [3, 3]),
  vow('EnemyShieldShrineUpgrade', 'Vow of Wards', [1, 1]),
  vow('EnemyCountShrineUpgrade', 'Vow of Hordes', [1, 1, 1]),
  vow('EnemyRespawnShrineUpgrade', 'Vow of Return', [1, 1]),
  vow('NextBiomeEnemyShrineUpgrade', 'Vow of Menace', [1, 2]),
  vow('BiomeSpeedShrineUpgrade', 'Vow of Time', [1, 2, 3]),
  vow('MinibossCountShrineUpgrade', 'Vow of Shadow', [2]),
  vow('BossDifficultyShrineUpgrade', 'Vow of Rivals', [2, 3, 3, 4], false),
  vow('BoonSkipShrineUpgrade', 'Vow of Forfeit', [3], true, {
    kind: 'preventOrdinaryRoomAcquisition',
    maximumPerBiome: 1,
    qualifyingRewardTypes: ['Boon', 'HermesUpgrade'],
  }),
  vow('BoonManaReserveShrineUpgrade', 'Vow of Hubris', [1, 1]),
  vow('BanUnpickedBoonsShrineUpgrade', 'Vow of Denial', [2], true, {
    kind: 'banUnselectedTraits',
    count: 2,
  }),
  vow('LimitGraspShrineUpgrade', 'Vow of Void', [1, 1, 1, 2], true, {
    kind: 'limitStartingGrasp',
    baseCapacity: 30,
    availablePercentByRank: [60, 40, 20, 0],
  }),
  vow('EnemyEliteShrineUpgrade', 'Vow of Fangs', [2, 3]),
] as const;
