import type { RawArcanaCardDeclaration, RawFearVowDeclaration } from './types';

const card = (
  key: string,
  label: string,
  traitKey: string,
  row: number,
  column: number,
  graspCost: number,
  activation: RawArcanaCardDeclaration['activation'] = { kind: 'manual' },
  postBossActivationCounts?: RawArcanaCardDeclaration['postBossActivationCounts'],
): RawArcanaCardDeclaration => ({
  key,
  label,
  traitKey,
  row,
  column,
  graspCost,
  activation,
  permanentRank: 3,
  ...(postBossActivationCounts === undefined ? {} : { postBossActivationCounts }),
});
const automatic = (
  rule: Exclude<RawArcanaCardDeclaration['activation'], { readonly kind: 'manual' }>['rule'],
) => ({ kind: 'automatic' as const, rule });

export const arcanaCards = [
  card('ChanneledCast', 'The Sorceress', 'ChannelSlowMetaUpgrade', 1, 1, 1),
  card('HealthRegen', 'The Wayward Son', 'DoorHealMetaUpgrade', 1, 2, 1),
  card('LowManaDamageBonus', 'The Huntress', 'LowManaDamageMetaupgrade', 1, 3, 2),
  card('CastCount', 'Eternity', 'CastDamageMetaUpgrade', 1, 4, 3),
  card(
    'SorceryRegenUpgrade',
    'The Moon',
    'SorceryRegenMetaUpgrade',
    1,
    5,
    0,
    automatic({ kind: 'adjacentActive' }),
  ),
  card('CastBuff', 'The Furies', 'InsideCastBuffMetaUpgrade', 2, 1, 2),
  card('BonusHealth', 'Persistence', 'HealthManaBonusMetaUpgrade', 2, 2, 2),
  card('BonusDodge', 'The Messenger', 'DodgeBonusMetaUpgrade', 2, 3, 1),
  card('ManaOverTime', 'The Unseen', 'ManaOverTimeMetaUpgrade', 2, 4, 5),
  card('MagicCrit', 'Night', 'MagicCritMetaUpgrade', 2, 5, 2),
  card('SprintShield', 'The Swift Runner', 'SprintShieldMetaUpgrade', 3, 1, 1),
  card('LastStand', 'Death', 'LastStandSlowTimeMetaUpgrade', 3, 2, 4),
  card(
    'MaxHealthPerRoom',
    'The Centaur',
    'ChamberHealthMetaUpgrade',
    3,
    3,
    0,
    automatic({ kind: 'manualCostsOneThroughFive' }),
  ),
  card('StatusVulnerability', 'Origination', 'EffectVulnerabilityMetaUpgrade', 3, 4, 5),
  card('ChanneledBlock', 'The Lovers', 'BossShieldMetaUpgrade', 3, 5, 3),
  card('DoorReroll', 'The Enchantress', 'DoorRerollMetaUpgrade', 4, 1, 3),
  card('StartingGold', 'The Boatman', 'StartingGoldMetaUpgrade', 4, 2, 5),
  card('MetaToRunUpgrade', 'The Artificer', 'MetaToRunMetaUpgrade', 4, 3, 3),
  card('RarityBoost', 'Excellence', 'RarityBoostMetaUpgrade', 4, 4, 5),
  card(
    'BonusRarity',
    'The Queen',
    'DuoRarityBoostMetaUpgrade',
    4,
    5,
    0,
    automatic({ kind: 'manualCostMultiplicityAtMost', maximum: 2 }),
  ),
  card(
    'TradeOff',
    'The Fates',
    'RerollTradeOffMetaUpgrade',
    5,
    1,
    0,
    automatic({ kind: 'surroundingCellsActive' }),
  ),
  card('ScreenReroll', 'The Champions', 'PanelRerollMetaUpgrade', 5, 2, 4),
  card('LowHealthBonus', 'Strength', 'LowHealthBuffMetaUpgrade', 5, 3, 4),
  card(
    'EpicRarityBoost',
    'Divinity',
    'EpicRarityBoostMetaUpgrade',
    5,
    4,
    0,
    automatic({ kind: 'completeOtherRowOrColumn' }),
  ),
  card(
    'CardDraw',
    'Judgment',
    'BossProgressionMetaUpgrade',
    5,
    5,
    0,
    automatic({ kind: 'manualCardCount', minimum: 1, maximum: 3 }),
    { Epic: 5, Heroic: 6 },
  ),
] as const;

const vow = (
  key: string,
  label: string,
  incrementalFear: readonly number[],
  circeRemovable = true,
): RawFearVowDeclaration => ({ key, label, incrementalFear, circeRemovable });
export const fearVows = [
  vow('HealingReductionShrineUpgrade', 'Vow of Scars', [1, 1, 2]),
  vow('ShopPricesShrineUpgrade', 'Vow of Debt', [1, 1]),
  vow('EnemyHealthShrineUpgrade', 'Vow of Grit', [1, 1, 1]),
  vow('EnemyDamageShrineUpgrade', 'Vow of Pain', [1, 2, 2]),
  vow('EnemySpeedShrineUpgrade', 'Vow of Frenzy', [3, 3]),
  vow('EnemyShieldShrineUpgrade', 'Vow of Wards', [1, 1]),
  vow('EnemyCountShrineUpgrade', 'Vow of Hordes', [1, 1, 1]),
  vow('EnemyRespawnShrineUpgrade', 'Vow of Return', [1, 1]),
  vow('NextBiomeEnemyShrineUpgrade', 'Vow of Menace', [1, 2]),
  vow('BiomeSpeedShrineUpgrade', 'Vow of Time', [1, 2, 3]),
  vow('MinibossCountShrineUpgrade', 'Vow of Shadow', [2]),
  vow('BossDifficultyShrineUpgrade', 'Vow of Rivals', [2, 3, 3, 4], false),
  vow('BoonSkipShrineUpgrade', 'Vow of Forfeit', [3]),
  vow('BoonManaReserveShrineUpgrade', 'Vow of Hubris', [1, 1]),
  vow('BanUnpickedBoonsShrineUpgrade', 'Vow of Denial', [2]),
  vow('LimitGraspShrineUpgrade', 'Vow of Void', [1, 1, 1, 2]),
  vow('EnemyEliteShrineUpgrade', 'Vow of Fangs', [2, 3]),
] as const;
