import type { RawKeepsakeDeclaration } from './keepsakes-types';

/** Ordinary rack inventory; player selection remains fixed at rank III. */
export const keepsakes: readonly RawKeepsakeDeclaration[] = [
  {
    key: 'ManaOverTimeRefundKeepsake',
    label: 'Silver Wheel',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'BossPreDamageKeepsake',
    label: 'Knuckle Bones',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'ReincarnationKeepsake',
    label: 'Luckier Tooth',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'DoorHealReserveKeepsake',
    label: 'Ghost Onion',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'DeathVengeanceKeepsake',
    label: 'Evil Eye',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'BonusMoneyKeepsake',
    label: 'Gold Purse',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'BlockDeathKeepsake',
    label: 'Engraved Pin',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'EscalatingKeepsake',
    label: 'Discordant Bell',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: { availability: 'excluded' },
  },
  {
    key: 'TimedBuffKeepsake',
    label: 'Metallic Droplet',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'LowHealthCritKeepsake',
    label: 'White Antler',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'SpellTalentKeepsake',
    label: 'Moon Beam',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'moonBeam', schedule: 'oneShotAfterUnequipped' },
    },
    effect: {
      kind: 'moonBeam',
      pathPointsByRank: { Common: 3, Rare: 4, Epic: 5, Heroic: 7 },
      priorityRewardTypes: ['SpellDrop', 'TalentDrop', 'TalentBigDrop'],
    },
  },
  {
    key: 'ForceZeusBoonKeepsake',
    label: 'Cloud Bangle',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Zeus',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceHeraBoonKeepsake',
    label: 'Iridescent Fan',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Hera',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForcePoseidonBoonKeepsake',
    label: 'Vivid Sea',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Poseidon',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceDemeterBoonKeepsake',
    label: 'Barley Sheaf',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Demeter',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceApolloBoonKeepsake',
    label: 'Harmonic Photon',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Apollo',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceAphroditeBoonKeepsake',
    label: 'Beautiful Mirror',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Aphrodite',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceHephaestusBoonKeepsake',
    label: 'Adamant Shard',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Hephaestus',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceHestiaBoonKeepsake',
    label: 'Everlasting Ember',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Hestia',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'ForceAresBoonKeepsake',
    label: 'Sword Hilt',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'olympianRewardPressure', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'olympianRewardPressure',
      priorityRewardType: 'Boon',
      providerKey: 'Ares',
      providerForceUses: 1,
      providerRarificationUses: 1,
      maximumSourceRarityLevelByRank: { Common: 1, Rare: 2, Epic: 3 },
    },
  },
  {
    key: 'AthenaEncounterKeepsake',
    label: 'Gorgon Amulet',
    rank: 'Epic',
    fatedDisposition: 'opposing',
    echoGift: { availability: 'excluded' },
    effect: {
      kind: 'gorgonAmulet',
      uses: 1,
      minimumBiomeDepth: 2,
      providerKey: 'Athena',
      rarityLevelByRank: { Common: 1, Rare: 2, Epic: 3, Heroic: 4 },
      naturalEncounterKey: 'AthenaCombatP',
    },
  },
  {
    key: 'SkipEncounterKeepsake',
    label: 'Fig Leaf',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: { availability: 'eligible', effect: { kind: 'figLeaf', schedule: 'oneShot' } },
    effect: { kind: 'figLeaf', biomeUsesByRank: { Common: 1, Rare: 2, Epic: 3, Heroic: 4 } },
  },
  {
    key: 'ArmorGainKeepsake',
    label: 'Silken Sash',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'FountainRarityKeepsake',
    label: 'Aromatic Phial',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: { availability: 'excluded' },
    effect: {
      kind: 'fountainRarity',
      uses: 1,
      targetRarityLevelByRank: { Common: 2, Rare: 3, Epic: 4 },
      sourceMaxRarityLevel: 1,
    },
  },
  {
    key: 'UnpickedBoonKeepsake',
    label: 'Concave Stone',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: { availability: 'eligible', effect: { kind: 'concaveStone', schedule: 'oneShot' } },
    effect: {
      kind: 'concaveStone',
      uses: 1,
      procSupportByRank: { Common: 25, Rare: 50, Epic: 75, Heroic: 100 },
    },
  },
  {
    key: 'DecayingBoostKeepsake',
    label: 'Lion Fang',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'DamagedDamageBoostKeepsake',
    label: 'Blackened Fleece',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'modeledNeutral', schedule: 'noModeledEffect' },
    },
  },
  {
    key: 'BossMetaUpgradeKeepsake',
    label: 'Crystal Figurine',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'crystalFigurine', schedule: 'everyBiome' },
    },
    effect: {
      kind: 'crystalFigurine',
      uses: 1,
      requestedCards: 2,
      rarityLevelByRank: { Common: 1, Rare: 2, Epic: 3, Heroic: 4 },
    },
  },
  {
    key: 'TempHammerKeepsake',
    label: 'Experimental Hammer',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'experimentalHammer', schedule: 'oneShotAfterUnequipped' },
    },
    effect: {
      kind: 'experimentalHammer',
      giverKey: 'WeaponUpgrade',
      qualifyingEncounterUsesByRank: { Common: 10, Rare: 15, Epic: 20, Heroic: 30 },
    },
  },
  {
    key: 'HadesAndPersephoneKeepsake',
    label: 'Jeweled Pom',
    rank: 'Epic',
    fatedDisposition: 'enabling',
    echoGift: { availability: 'excluded' },
    effect: {
      kind: 'jeweledPom',
      giverKey: 'Hades',
      subsequentEligibleTraitLevelsByRank: { Common: 1, Rare: 2, Epic: 3, Heroic: 4 },
    },
  },
  {
    key: 'RarifyKeepsake',
    label: 'Calling Card',
    rank: 'Epic',
    fatedDisposition: 'enabling',
    echoGift: { availability: 'eligible', effect: { kind: 'callingCard', schedule: 'everyBiome' } },
    effect: {
      kind: 'callingCard',
      rarificationChargesByRank: { Common: 2, Rare: 4, Epic: 6, Heroic: 8 },
    },
  },
  {
    key: 'GoldifyKeepsake',
    label: 'Time Piece',
    rank: 'Epic',
    fatedDisposition: 'enabling',
    echoGift: { availability: 'eligible', effect: { kind: 'timePiece', schedule: 'everyBiome' } },
    effect: {
      kind: 'timePiece',
      conversionChargesByRank: { Common: 2, Rare: 3, Epic: 4, Heroic: 5 },
    },
  },
  {
    key: 'RandomBlessingKeepsake',
    label: 'Transcendent Embryo',
    rank: 'Epic',
    fatedDisposition: 'neutral',
    echoGift: {
      availability: 'eligible',
      effect: { kind: 'transcendentEmbryo', schedule: 'oneShot' },
    },
    effect: {
      kind: 'transcendentEmbryo',
      source: 'Chaos',
      interval: 8,
      blessingRarityByRank: { Common: 'Common', Rare: 'Rare', Epic: 'Epic', Heroic: 'Heroic' },
    },
  },
];
