import type { RawRewardPrimitiveDeclaration } from '../types';

export const rewardPrimitives = [
  { gameName: 'AphroditeUpgrade', label: 'Aphrodite' },
  { gameName: 'ApolloUpgrade', label: 'Apollo' },
  { gameName: 'AresUpgrade', label: 'Ares' },
  { gameName: 'DemeterUpgrade', label: 'Demeter' },
  { gameName: 'HephaestusUpgrade', label: 'Hephaestus' },
  { gameName: 'HeraUpgrade', label: 'Hera' },
  { gameName: 'HestiaUpgrade', label: 'Hestia' },
  { gameName: 'PoseidonUpgrade', label: 'Poseidon' },
  { gameName: 'ZeusUpgrade', label: 'Zeus' },
  {
    gameName: 'Boon',
    label: 'Boon',
    payloadDomain: 'BoonSource',
    defaultPayload: { source: 'ApolloUpgrade' },
  },
  {
    gameName: 'Devotion',
    label: 'Trial',
    payloadDomain: 'DevotionPair',
    defaultPayload: { sources: ['ApolloUpgrade', 'ZeusUpgrade'] },
  },
  { gameName: 'Story', label: 'Story' },
  {
    gameName: 'RandomLoot',
    label: 'Boon',
    acquiredAs: 'Boon',
    payloadDomain: 'BoonSource',
    defaultPayload: { source: 'ApolloUpgrade' },
  },
  {
    gameName: 'BlindBoxLoot',
    label: 'Mystery Boon',
    acquiredAs: 'Boon',
    payloadDomain: 'BoonSource',
    defaultPayload: { source: 'ApolloUpgrade' },
  },
  { gameName: 'HermesUpgrade', label: 'Hermes' },
  {
    gameName: 'ShopHermesUpgrade',
    label: 'Hermes Boon',
    acquiredAs: 'HermesUpgrade',
  },
  { gameName: 'MaxHealthDrop', label: 'Max Health' },
  { gameName: 'MaxManaDrop', label: 'Max Magick' },
  { gameName: 'RoomMoneyDrop', label: 'Gold' },
  { gameName: 'StackUpgrade', label: 'Pom of Power' },
  { gameName: 'WeaponUpgrade', label: 'Hammer' },
  {
    gameName: 'WeaponUpgradeDrop',
    label: 'Hammer',
    acquiredAs: 'WeaponUpgrade',
  },
  { gameName: 'SpellDrop', label: "Selene's Gift" },
  { gameName: 'TalentDrop', label: 'Path of Stars' },
  {
    gameName: 'StoreRewardRandomStack',
    label: 'Pom Slice',
    acquiredAs: 'StackUpgrade',
  },
  { gameName: 'GiftDrop', label: 'Nectar' },
  { gameName: 'MetaCurrencyDrop', label: 'Bones' },
  {
    gameName: 'MetaCurrencyBigDrop',
    label: 'Big Bones',
    acquiredAs: 'MetaCurrencyDrop',
  },
  { gameName: 'MetaCardPointsCommonDrop', label: 'Ashes' },
  {
    gameName: 'MetaCardPointsCommonBigDrop',
    label: 'Big Ashes',
    acquiredAs: 'MetaCardPointsCommonDrop',
  },
  { gameName: 'RoomRewardHealDrop', label: 'Heal' },
  { gameName: 'ArmorBoost', label: 'Armor' },
] as const satisfies readonly RawRewardPrimitiveDeclaration[];
