import type { RawBiomeLayoutDeclaration } from '../types';

export const gBiomeLayout = {
  biomeKey: 'G',
  initialCounters: { biomeDepthCache: 1, biomeEncounterDepth: 1 },
  start: { kind: 'fixedAuthored', roomGameName: 'G_Intro' },
  progression: {
    kind: 'generated',
    progressionPolicy: { kind: 'eligibilityDriven' },
    batchPolicy: { kind: 'standard', fields: [] },
    rewardStorePolicy: {
      kind: 'authoredBaseStore',
      storeKeys: ['RunProgress', 'MetaProgress'],
      targetMetaRewardsRatio: 0.35,
      targetMetaRewardsAdjustSpeed: 10,
    },
    rewardStoreOverrides: [],
    bounds: { maxBatches: 7, maxTargets: 21 },
    anomalyReplacement: {
      kind: 'oceanusAnomaly',
      source: {
        minimumBiomeDepthCache: 3,
        excludedRoomGameNames: ['G_Shop01', 'G_Story01', 'G_PreBoss01', 'C_Boss01'],
        excludedSourceEncounterGameNames: ['ArtemisCombatG', 'NemesisRandomEvent'],
        maxEnteredReplacementsThisRoute: 0,
      },
      replaceableTargetRoomGameNames: [
        'G_Combat01',
        'G_Combat02',
        'G_Combat03',
        'G_Combat04',
        'G_Combat05',
        'G_Combat06',
        'G_Combat07',
        'G_Combat08',
        'G_Combat09',
        'G_Combat10',
        'G_Combat11',
        'G_Combat12',
        'G_Combat13',
        'G_Combat14',
        'G_Combat15',
        'G_Combat16',
        'G_Combat17',
        'G_Combat18',
        'G_Combat19',
        'G_Combat20',
      ],
      replacementRoomGameNames: [
        'B_Combat01',
        'B_Combat05',
        'B_Combat06',
        'B_Combat07',
        'B_Combat08',
        'B_Combat10',
        'B_Combat21',
      ],
      defaultReplacementRoomGameName: 'B_Combat01',
    },
  },
  completion: {
    rooms: [
      { role: 'boss', roomGameName: 'G_Boss01' },
      { role: 'postboss', roomGameName: 'G_PostBoss01' },
    ],
    transitionEffects: [
      { kind: 'resetCounter', axis: 'biomeDepthCache' },
      { kind: 'resetCounter', axis: 'biomeEncounterDepth' },
    ],
  },
  fields: [],
} as const satisfies RawBiomeLayoutDeclaration;
