import type { RawConcreteAcquisitionDeclaration } from './types';

export const acquisitions = [
  {
    gameName: 'AphroditeUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'ApolloUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'AresUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'DemeterUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'HephaestusUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'HeraUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'HestiaUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'PoseidonUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'ZeusUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'HermesUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'StackUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 1 },
    goldConversionEligible: true,
  },
  {
    gameName: 'StackUpgradeBig',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 2 },
    goldConversionEligible: true,
  },
  {
    gameName: 'StackUpgradeTriple',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 3 },
    goldConversionEligible: true,
  },
  {
    gameName: 'WeaponUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'SpellDrop',
    kind: 'loot',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxHealthDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxHealthDropBig',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxHealthDropSmall',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'EmptyMaxHealthSmallDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxManaDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxManaDropBig',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxManaDropSmall',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  { gameName: 'Currency', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'RoomMoneyDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'RoomMoneyTripleDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'RoomMoneyTinyDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'TalentDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'TalentBigDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MinorTalentDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'RoomRewardHealDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'HealBigDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'ArmorBoost',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'ArmorBigBoost',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  { gameName: 'AirBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'EarthBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'FireBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'WaterBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'ElementalBoost',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    elementContributions: { Earth: 1, Air: 1, Fire: 1, Water: 1 },
  },
  {
    gameName: 'StoreRewardRandomStack',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    levelResolutionEffect: { kind: 'randomTarget', levelCount: 1 },
  },
  {
    gameName: 'LastStandDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'ChaosWeaponUpgrade',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'InfernalContractBoon', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'TrialUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'BlindBoxLoot', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'GiftDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MetaCurrencyDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MetaCurrencyBigDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MetaCardPointsCommonDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MetaCardPointsCommonBigDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  { gameName: 'WeaponPointsRareDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'CardUpgradePointsDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'CharonPointsDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
] as const satisfies readonly RawConcreteAcquisitionDeclaration[];
