import type { RawConcreteAcquisitionDeclaration } from './types';

function lastReward(rewardType: string) {
  return Object.freeze({
    lastRewardRecreation: Object.freeze({
      rewardType,
      producerLifecycleKey: 'EchoLastReward' as const,
    }),
  });
}

export const acquisitions = [
  {
    gameName: 'AphroditeUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('AphroditeUpgrade'),
  },
  {
    gameName: 'ApolloUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('ApolloUpgrade'),
  },
  {
    gameName: 'AresUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('AresUpgrade'),
  },
  {
    gameName: 'DemeterUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('DemeterUpgrade'),
  },
  {
    gameName: 'HephaestusUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('HephaestusUpgrade'),
  },
  {
    gameName: 'HeraUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('HeraUpgrade'),
  },
  {
    gameName: 'HestiaUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('HestiaUpgrade'),
  },
  {
    gameName: 'PoseidonUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('PoseidonUpgrade'),
  },
  {
    gameName: 'ZeusUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('ZeusUpgrade'),
  },
  {
    gameName: 'HermesUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('HermesUpgrade'),
  },
  {
    gameName: 'StackUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 1 },
    goldConversionEligible: true,
    ...lastReward('StackUpgrade'),
  },
  {
    gameName: 'StackUpgradeBig',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 2 },
    goldConversionEligible: true,
    ...lastReward('StackUpgradeBig'),
  },
  {
    gameName: 'StackUpgradeTriple',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 3 },
    goldConversionEligible: true,
    ...lastReward('StackUpgradeTriple'),
  },
  {
    gameName: 'WeaponUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    goldConversionEligible: true,
    ...lastReward('WeaponUpgrade'),
  },
  {
    gameName: 'SpellDrop',
    kind: 'loot',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('SpellDrop'),
  },
  {
    gameName: 'MaxHealthDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MaxHealthDrop'),
  },
  {
    gameName: 'MaxHealthDropBig',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MaxHealthDropBig'),
  },
  {
    gameName: 'MaxHealthDropSmall',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'EmptyMaxHealthSmallDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'MaxManaDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MaxManaDrop'),
  },
  {
    gameName: 'MaxManaDropBig',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MaxManaDropBig'),
  },
  {
    gameName: 'MaxManaDropSmall',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  { gameName: 'Currency', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'RoomMoneyDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    ...lastReward('RoomMoneyDrop'),
  },
  {
    gameName: 'RoomMoneyTripleDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    ...lastReward('RoomMoneyTripleDrop'),
  },
  { gameName: 'RoomMoneyTinyDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'TalentDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('TalentDrop'),
  },
  {
    gameName: 'TalentBigDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('TalentBigDrop'),
  },
  {
    gameName: 'MinorTalentDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'RoomRewardHealDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'HealBigDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'ArmorBoost',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'ArmorBigBoost',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  { gameName: 'AirBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'EarthBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'FireBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'WaterBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'ElementalBoost',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    elementContributions: { Earth: 1, Air: 1, Fire: 1, Water: 1 },
  },
  {
    gameName: 'StoreRewardRandomStack',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    levelResolutionEffect: { kind: 'randomTarget', levelCount: 1 },
  },
  {
    gameName: 'LastStandDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
  },
  {
    gameName: 'ChaosWeaponUpgrade',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'InfernalContractBoon', kind: 'loot', historyProjection: 'lootAndUse' },
  {
    gameName: 'TrialUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    ...lastReward('TrialUpgrade'),
  },
  { gameName: 'BlindBoxLoot', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'GiftDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('GiftDrop'),
  },
  {
    gameName: 'MetaCurrencyDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MetaCurrencyDrop'),
  },
  {
    gameName: 'MetaCurrencyBigDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MetaCurrencyBigDrop'),
  },
  {
    gameName: 'MetaCardPointsCommonDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MetaCardPointsCommonDrop'),
  },
  {
    gameName: 'MetaCardPointsCommonBigDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
    goldConversionEligible: true,
    ...lastReward('MetaCardPointsCommonBigDrop'),
  },
  { gameName: 'WeaponPointsRareDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'CardUpgradePointsDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'CharonPointsDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
] as const satisfies readonly RawConcreteAcquisitionDeclaration[];
