import type { RawConcreteAcquisitionDeclaration } from './types';

export const acquisitions = [
  { gameName: 'AphroditeUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'ApolloUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'AresUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'DemeterUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'HephaestusUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'HeraUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'HestiaUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'PoseidonUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'ZeusUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'HermesUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  {
    gameName: 'StackUpgrade',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 1 },
  },
  {
    gameName: 'StackUpgradeBig',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 2 },
  },
  {
    gameName: 'StackUpgradeTriple',
    kind: 'loot',
    historyProjection: 'lootAndUse',
    levelResolutionEffect: { kind: 'visibleChoice', levelCount: 3 },
  },
  { gameName: 'WeaponUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'SpellDrop', kind: 'loot', historyProjection: 'consumableAndUse' },
  { gameName: 'MaxHealthDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'MaxHealthDropBig', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'MaxHealthDropSmall', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'EmptyMaxHealthSmallDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'MaxManaDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'MaxManaDropBig', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'MaxManaDropSmall', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'RoomMoneyDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'RoomMoneyTripleDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'RoomMoneyTinyDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'TalentDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'TalentBigDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'MinorTalentDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'RoomRewardHealDrop',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'HealBigDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'ArmorBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'ArmorBigBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'AirBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'EarthBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'FireBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'WaterBoost', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'StoreRewardRandomStack',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
    levelResolutionEffect: { kind: 'randomTarget', levelCount: 1 },
  },
  { gameName: 'LastStandDrop', kind: 'consumable', historyProjection: 'consumableAndUse' },
  {
    gameName: 'ChaosWeaponUpgrade',
    kind: 'consumable',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'InfernalContractBoon', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'TrialUpgrade', kind: 'loot', historyProjection: 'lootAndUse' },
  { gameName: 'BlindBoxLoot', kind: 'consumable', historyProjection: 'consumableAndUse' },
  { gameName: 'GiftDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'MetaCurrencyDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'MetaCurrencyBigDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  {
    gameName: 'MetaCardPointsCommonDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
  },
  {
    gameName: 'MetaCardPointsCommonBigDrop',
    kind: 'resource',
    historyProjection: 'consumableAndUse',
  },
  { gameName: 'WeaponPointsRareDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'CardUpgradePointsDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
  { gameName: 'CharonPointsDrop', kind: 'resource', historyProjection: 'consumableAndUse' },
] as const satisfies readonly RawConcreteAcquisitionDeclaration[];
