import type { RawRewardKernelInput } from './types';

const nemesisEventRewardTypes = [
  'EmptyMaxHealthDrop',
  'HealDrop',
  'LastStandDrop',
  'ArmorBoost',
  'MaxHealthDrop',
  'MaxHealthDropBig',
  'MaxManaDrop',
  'MaxManaDropBig',
  'StackUpgrade',
  'StackUpgradeBig',
  'WeaponUpgrade',
  'RoomMoneyDrop',
  'TalentDrop',
  'RoomMoneyTripleDrop',
  'RoomRewardConsolationPrize',
] as const;

export const producerLifecycles = [
  {
    key: 'RoomReward',
    rewardTypes: [
      'MaxHealthDrop',
      'MaxHealthDropBig',
      'MaxHealthDropSmall',
      'EmptyMaxHealthSmallDrop',
      'MaxManaDrop',
      'MaxManaDropBig',
      'MaxManaDropSmall',
      'RoomMoneyDrop',
      'RoomMoneySmallDrop',
      'RoomMoneyTripleDrop',
      'RoomMoneyTinyDrop',
      'StackUpgrade',
      'StackUpgradeBig',
      'StackUpgradeTriple',
      'WeaponUpgrade',
      'HermesUpgrade',
      'Devotion',
      'SpellDrop',
      'TalentDrop',
      'TalentBigDrop',
      'MinorTalentDrop',
      'RoomRewardHealDrop',
      'ArmorBoost',
      'Boon',
      'GiftDrop',
      'MetaCurrencyDrop',
      'MetaCardPointsCommonDrop',
      'MetaCurrencyBigDrop',
      'MetaCardPointsCommonBigDrop',
      'AirBoost',
      'EarthBoost',
      'FireBoost',
      'WaterBoost',
      'InfernalContractBoon',
      'TrialUpgrade',
      'Story',
      'Shop',
    ],
    defaultLifecyclePoint: 'roomRewardPickup',
    overrides: [
      {
        rewardType: 'Devotion',
        acquisitionLifecycle: [
          { role: 'chosenSource', lifecyclePoint: 'beforeCombat' },
          { role: 'spurnedSource', lifecyclePoint: 'afterCombat' },
        ],
      },
      {
        rewardType: 'GiftDrop',
        acquisitionLifecycle: [
          {
            role: 'self',
            lifecyclePoint: 'roomRewardPickup',
            levelResolutionEffect: { kind: 'randomTargetIfAvailable', levelCount: 1 },
          },
        ],
      },
    ],
  },
  // A Shrine purchase is paid, but its rush/matured object is a free room
  // pickup.  Keep that delivery lifecycle distinct from the menu profile:
  // the profile owns visible inventory while this declaration owns ordinary
  // pickup roles for every exact SurfaceShop item.
  {
    key: 'HermesShrineDelivery',
    rewardTypes: [
      'HealBigDrop',
      'RoomRewardHealDrop',
      'ArmorBigBoost',
      'ArmorBoost',
      'LastStandDrop',
      'GiftDrop',
      'SpellDrop',
      'ShopHermesUpgrade',
      'MaxHealthDrop',
      'MaxManaDrop',
      'BlindBoxLoot',
      'TalentDrop',
    ],
    defaultLifecyclePoint: 'roomRewardPickup',
    overrides: [
      {
        rewardType: 'GiftDrop',
        acquisitionLifecycle: [
          {
            role: 'self',
            lifecyclePoint: 'roomRewardPickup',
            levelResolutionEffect: { kind: 'randomTargetIfAvailable', levelCount: 1 },
          },
        ],
      },
      {
        rewardType: 'BlindBoxLoot',
        acquisitionLifecycle: [
          { role: 'box', lifecyclePoint: 'roomRewardPickup' },
          { role: 'hiddenSource', lifecyclePoint: 'afterUnwrap' },
        ],
      },
    ],
  },
  {
    key: 'EchoLastReward',
    rewardTypes: [
      'AphroditeUpgrade',
      'ApolloUpgrade',
      'AresUpgrade',
      'DemeterUpgrade',
      'HephaestusUpgrade',
      'HeraUpgrade',
      'HestiaUpgrade',
      'PoseidonUpgrade',
      'ZeusUpgrade',
      'HermesUpgrade',
      'StackUpgrade',
      'StackUpgradeBig',
      'StackUpgradeTriple',
      'WeaponUpgrade',
      'TrialUpgrade',
      'MaxHealthDrop',
      'MaxHealthDropBig',
      'MaxManaDrop',
      'MaxManaDropBig',
      'RoomMoneyDrop',
      'RoomMoneySmallDrop',
      'RoomMoneyTripleDrop',
      'TalentDrop',
      'TalentBigDrop',
      'GiftDrop',
      'MetaCurrencyDrop',
      'MetaCurrencyBigDrop',
      'MetaCardPointsCommonDrop',
      'MetaCardPointsCommonBigDrop',
      'MemPointsCommonDrop',
    ],
    defaultLifecyclePoint: 'echoReplay',
    overrides: [
      ...[
        'AphroditeUpgrade',
        'ApolloUpgrade',
        'AresUpgrade',
        'DemeterUpgrade',
        'HephaestusUpgrade',
        'HeraUpgrade',
        'HestiaUpgrade',
        'PoseidonUpgrade',
        'ZeusUpgrade',
        'HermesUpgrade',
        'StackUpgrade',
        'StackUpgradeBig',
        'StackUpgradeTriple',
        'WeaponUpgrade',
        'TrialUpgrade',
        'MaxHealthDrop',
        'MaxHealthDropBig',
        'MaxManaDrop',
        'MaxManaDropBig',
        'RoomMoneyDrop',
        'RoomMoneySmallDrop',
        'RoomMoneyTripleDrop',
        'TalentDrop',
        'TalentBigDrop',
        'MetaCurrencyDrop',
        'MetaCurrencyBigDrop',
        'MetaCardPointsCommonDrop',
        'MetaCardPointsCommonBigDrop',
        'MemPointsCommonDrop',
      ].map((rewardType) => ({
        rewardType,
        acquisitionLifecycle: [
          {
            role: 'self',
            lifecyclePoint: 'echoReplay' as const,
            blocksArtificerConversion: true as const,
          },
        ],
      })),
      {
        rewardType: 'GiftDrop',
        acquisitionLifecycle: [
          {
            role: 'self',
            lifecyclePoint: 'echoReplay',
            levelResolutionEffect: { kind: 'randomTargetIfAvailable', levelCount: 1 },
            blocksArtificerConversion: true,
          },
        ],
      },
    ],
  },
  {
    key: 'NarcissusPickup',
    rewardTypes: [
      'StoreRewardRandomStack',
      'MaxManaDrop',
      'MaxHealthDrop',
      'Currency',
      'LastStandDrop',
      'BlindBoxLoot',
      'ElementalBoost',
      'MetaCardPointsCommonDrop',
      'MemPointsCommonDrop',
      'MetaCurrencyDrop',
    ],
    defaultLifecyclePoint: 'roomExit',
  },
  {
    key: 'GeneratedTraitPickup',
    rewardTypes: [
      'RoomMoneyDrop',
      'RoomMoneySmallDrop',
      'RoomMoneyTinyDrop',
      'HealDropMinor',
      'MetaCurrencyDrop',
    ],
    defaultLifecyclePoint: 'roomRewardPickup',
    overrides: [
      {
        rewardType: 'MetaCurrencyDrop',
        acquisitionLifecycle: [
          {
            role: 'self',
            lifecyclePoint: 'roomRewardPickup',
            blocksArtificerConversion: true,
          },
        ],
      },
    ],
  },
  {
    key: 'NemesisEventPickup',
    rewardTypes: nemesisEventRewardTypes,
    defaultLifecyclePoint: 'roomRewardPickup',
    overrides: [
      ...nemesisEventRewardTypes.map((rewardType) => ({
        rewardType,
        acquisitionLifecycle: [
          {
            role: 'self',
            lifecyclePoint: 'roomRewardPickup' as const,
            blocksArtificerConversion: true as const,
          },
        ],
      })),
    ],
  },
  {
    key: 'ZagPedestal',
    rewardTypes: ['BlindBoxLoot', 'StackUpgradeBig', 'StackUpgrade', 'TalentBigDrop', 'TalentDrop'],
    defaultLifecyclePoint: 'roomExit',
    overrides: [
      {
        rewardType: 'BlindBoxLoot',
        acquisitionLifecycle: [
          { role: 'box', lifecyclePoint: 'roomExit' },
          { role: 'hiddenSource', lifecyclePoint: 'afterUnwrap' },
        ],
      },
    ],
  },
] as const satisfies RawRewardKernelInput['producerLifecycles'];
