import {
  devotionLegal,
  hammerEarly,
  hammerLate,
  hermesLootLegal,
  largeEnteredBiomes,
  ordinaryLootCount,
  routeTalentLegal,
  runDevotionLegal,
  smallEnteredBiomes,
  spellLegal,
  stackLegal,
  talentLegal,
} from './requirements';
import type { RawRewardKernelInput } from './types';

const runProgressEntries = [
  { rewardType: 'MaxHealthDrop' },
  { rewardType: 'MaxHealthDrop', requirement: ordinaryLootCount },
  { rewardType: 'MaxManaDrop' },
  { rewardType: 'MaxManaDrop', requirement: ordinaryLootCount },
  { rewardType: 'RoomMoneyDrop' },
  { rewardType: 'RoomMoneyDrop', requirement: ordinaryLootCount },
  { rewardType: 'StackUpgrade', requirement: stackLegal },
  {
    rewardType: 'StackUpgrade',
    requirement: { kind: 'all', requirements: [stackLegal, ordinaryLootCount] },
  },
  { rewardType: 'WeaponUpgrade', requirement: hammerEarly },
  { rewardType: 'WeaponUpgrade', requirement: hammerLate },
  { rewardType: 'HermesUpgrade', requirement: hermesLootLegal },
  { rewardType: 'Devotion', requirement: runDevotionLegal },
  { rewardType: 'SpellDrop', requirement: spellLegal },
  { rewardType: 'TalentDrop', requirement: routeTalentLegal },
  { rewardType: 'Boon', allowDuplicates: true },
  { rewardType: 'Boon', allowDuplicates: true },
  { rewardType: 'Boon', allowDuplicates: true },
  { rewardType: 'Boon', allowDuplicates: true },
] as const;

export const stores = [
  { key: 'RunProgress', defaultRewardType: 'Boon', entries: runProgressEntries },
  {
    key: 'MetaProgress',
    defaultRewardType: 'GiftDrop',
    entries: [
      { rewardType: 'GiftDrop' },
      { rewardType: 'MetaCurrencyDrop', requirement: smallEnteredBiomes },
      { rewardType: 'MetaCurrencyDrop', requirement: smallEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonDrop', requirement: smallEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonDrop', requirement: smallEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonDrop', requirement: smallEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonDrop', requirement: smallEnteredBiomes },
      { rewardType: 'MetaCurrencyBigDrop', requirement: largeEnteredBiomes },
      { rewardType: 'MetaCurrencyBigDrop', requirement: largeEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonBigDrop', requirement: largeEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonBigDrop', requirement: largeEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonBigDrop', requirement: largeEnteredBiomes },
      { rewardType: 'MetaCardPointsCommonBigDrop', requirement: largeEnteredBiomes },
    ],
  },
  {
    key: 'HubRewards',
    defaultRewardType: 'Boon',
    entries: [
      { rewardType: 'MaxHealthDropBig' },
      { rewardType: 'MaxManaDropBig' },
      { rewardType: 'WeaponUpgrade', requirement: hammerEarly },
      { rewardType: 'HermesUpgrade', requirement: hermesLootLegal },
      { rewardType: 'SpellDrop', requirement: spellLegal },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
    ],
  },
  {
    key: 'SubRoomRewards',
    defaultRewardType: 'MaxManaDropSmall',
    entries: [
      { rewardType: 'MaxManaDropSmall' },
      { rewardType: 'MaxHealthDropSmall' },
      { rewardType: 'EmptyMaxHealthSmallDrop' },
      { rewardType: 'RoomMoneyTinyDrop' },
      { rewardType: 'AirBoost' },
      { rewardType: 'EarthBoost' },
      { rewardType: 'FireBoost' },
      { rewardType: 'WaterBoost' },
      { rewardType: 'GiftDrop' },
      { rewardType: 'MetaCurrencyDrop' },
      { rewardType: 'MetaCurrencyDrop' },
      { rewardType: 'MetaCardPointsCommonDrop' },
      { rewardType: 'MetaCardPointsCommonDrop' },
      { rewardType: 'MaxHealthDrop' },
      { rewardType: 'MaxHealthDrop' },
      { rewardType: 'MaxManaDrop' },
      { rewardType: 'MaxManaDrop' },
      { rewardType: 'StackUpgrade', requirement: stackLegal },
      { rewardType: 'StackUpgrade', requirement: stackLegal },
      { rewardType: 'RoomMoneyDrop' },
      { rewardType: 'RoomMoneyDrop' },
      { rewardType: 'MinorTalentDrop', requirement: talentLegal },
      { rewardType: 'MinorTalentDrop', requirement: talentLegal },
    ],
  },
  {
    key: 'SubRoomRewardsHard',
    defaultRewardType: 'MaxHealthDrop',
    entries: [
      { rewardType: 'MaxHealthDrop' },
      { rewardType: 'MaxHealthDrop' },
      { rewardType: 'MaxManaDrop' },
      { rewardType: 'MaxManaDrop' },
      { rewardType: 'StackUpgrade', requirement: stackLegal },
      { rewardType: 'StackUpgrade', requirement: stackLegal },
      { rewardType: 'RoomMoneyDrop' },
      { rewardType: 'RoomMoneyDrop' },
    ],
  },
  {
    key: 'FieldsOptionalRewards',
    defaultRewardType: 'MaxManaDropSmall',
    entries: [
      { rewardType: 'MaxManaDropSmall' },
      { rewardType: 'MaxManaDropSmall' },
      { rewardType: 'MaxManaDropSmall' },
      { rewardType: 'MaxHealthDropSmall' },
      { rewardType: 'MaxHealthDropSmall' },
      { rewardType: 'MaxHealthDropSmall' },
      { rewardType: 'RoomMoneyTinyDrop' },
      { rewardType: 'RoomMoneyTinyDrop' },
      { rewardType: 'RoomMoneyTinyDrop' },
      { rewardType: 'RoomRewardHealDrop' },
      { rewardType: 'ArmorBoost' },
      { rewardType: 'GiftDrop' },
      { rewardType: 'MetaCurrencyDrop' },
      { rewardType: 'MetaCardPointsCommonDrop' },
      { rewardType: 'MetaCardPointsCommonDrop' },
      { rewardType: 'MetaCardPointsCommonDrop' },
      { rewardType: 'MetaCardPointsCommonDrop' },
      { rewardType: 'MinorTalentDrop', requirement: talentLegal },
      { rewardType: 'MinorTalentDrop', requirement: talentLegal },
    ],
  },
  {
    key: 'TartarusRewards',
    defaultRewardType: 'RoomMoneyTripleDrop',
    entries: [
      { rewardType: 'RoomMoneyTripleDrop' },
      { rewardType: 'StackUpgradeTriple', requirement: stackLegal },
      { rewardType: 'WeaponUpgrade', requirement: hammerEarly },
      { rewardType: 'WeaponUpgrade', requirement: hammerLate },
      { rewardType: 'Devotion', requirement: devotionLegal },
      { rewardType: 'TalentBigDrop', requirement: talentLegal },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
    ],
  },
  {
    key: 'TyphonBossRewards',
    defaultRewardType: 'Boon',
    entries: [
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'Boon', allowDuplicates: true },
      { rewardType: 'TalentBigDrop', requirement: talentLegal },
      { rewardType: 'StackUpgradeTriple', requirement: stackLegal },
      { rewardType: 'WeaponUpgrade', requirement: hammerEarly },
      { rewardType: 'WeaponUpgrade', requirement: hammerLate },
    ],
  },
] satisfies RawRewardKernelInput['stores'];
