import type { RawRoomDeclaration } from '../types';
import { nResourcePointSupport } from '../../resources';
import { surfaceShopHost } from './shared';

export const nCompletionRooms = [
  {
    gameName: 'N_PreBoss01',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Preboss',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
      additionalOptionRequirements: {
        WeaponUpgradeDropEarly: {
          kind: 'rewardLookupExcludes',
          lookupKey: 'hubRewardLookup',
          rewardType: 'WeaponUpgrade',
        },
        SpellDrop: {
          kind: 'rewardLookupExcludes',
          lookupKey: 'hubRewardLookup',
          rewardType: 'SpellDrop',
        },
      },
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: { kind: 'takeOverNormalDoors', remainingOffers: { kind: 'none' } },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Boss01',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Polyphemus',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    effectNeutralRequiredReward: true,
    mode: { kind: 'authored', templateKey: 'Boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossPolyphemus01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Boss02',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Polyphemus',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    effectNeutralRequiredReward: true,
    mode: { kind: 'authored', templateKey: 'Boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossPolyphemus02' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_PostBoss01',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Postboss',
    hasKeepsakeRack: true,
    hasRequiredFountain: true,
    ...surfaceShopHost(1, true),
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'authored', templateKey: 'PostBoss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] satisfies readonly RawRoomDeclaration[];
