import type { RawRoomDeclaration } from '../types';
import { nResourcePointSupport } from '../../resources';
import { surfaceShopHost } from './shared';

export const nSideRooms = [
  {
    gameName: 'N_Sub01',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 01',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub02',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 02',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoomLight' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub03',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 03',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub04',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 04',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub05',
    ...surfaceShopHost(0.08, false, 0),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 05',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub06',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 06',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub07',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 07',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub08',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 08',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub09',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 09',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub10',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 10',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub11',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 11',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub12',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 12',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub13',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 13',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub14',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 14',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub15',
    ...surfaceShopHost(0.08, false, 1),
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    blocksGorgon: true,
    ignoreEncounterUses: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 15',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    advancesHermesShrineDeliveryUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
] satisfies readonly RawRoomDeclaration[];
