import type { RawRoomDeclaration } from '../types';

/**
 * These maps are declared by the game's Anomaly room set even though their
 * names reuse Asphodel's B_Combat prefix. The host route context is supplied
 * by the G replacement declaration, never inferred from that prefix.
 */
export const anomalyRooms = [
  {
    gameName: 'B_Combat01',
    label: 'Anomaly 01',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
  {
    gameName: 'B_Combat05',
    label: 'Anomaly 05',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
  {
    gameName: 'B_Combat06',
    label: 'Anomaly 06',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
  {
    gameName: 'B_Combat07',
    label: 'Anomaly 07',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
  {
    gameName: 'B_Combat08',
    label: 'Anomaly 08',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
  {
    gameName: 'B_Combat10',
    label: 'Anomaly 10',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
  {
    gameName: 'B_Combat21',
    label: 'Anomaly 21',
    roomSetKey: 'Anomaly',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'Anomaly' },
    blockGiftBoons: true,
    structuralTags: [],
    exits: [{ index: 1, type: 'AnomalyAutoExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'SpellDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedAnomalyB' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: {},
  },
] as const satisfies readonly RawRoomDeclaration[];
