import type { RawRoomDeclaration } from '../types';
import { normalResourcePointSupport } from '../resources';

const naturalChaosExit = {
  kind: 'naturalChaos' as const,
  key: 'naturalChaos' as const,
  exitType: 'ChaosExitDoor',
};

const fRoomDeclarations: readonly RawRoomDeclaration[] = [
  {
    gameName: 'F_Opening01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Opening 01',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    lifecycleProfileKey: 'OpeningRewardRoom',
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'OpeningGeneratedF',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Opening02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Opening 02',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    lifecycleProfileKey: 'OpeningRewardRoom',
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'OpeningGeneratedF',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Opening03',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Opening 03',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    lifecycleProfileKey: 'OpeningRewardRoom',
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'OpeningGeneratedF',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 01',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedF' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 02',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat03',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 03',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat04',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 04',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat05',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 05',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat06',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 06',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat07',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 07',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat08',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 08',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat09',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 09',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 4 },
    },
  },
  {
    gameName: 'F_Combat10',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 10',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat11',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 11',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat12',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 12',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat13',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 13',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_Combat14',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 14',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat15',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 15',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat16',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 16',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat17',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 17',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat18',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 18',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat19',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 19',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat20',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 20',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 5 },
    },
  },
  {
    gameName: 'F_Combat21',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 21',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_Combat22',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 22',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'FEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 5 },
    },
  },
  {
    gameName: 'F_MiniBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.07, Legendary: 0.05 },
    label: 'Root-Stalker',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossTreant' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['F_MiniBoss02', 'F_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_MiniBoss02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.07, Legendary: 0.05 },
    label: 'Shadow-Spiller',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossFogEmitter' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['F_MiniBoss01', 'F_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_MiniBoss03',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.07, Legendary: 0.05 },
    label: 'Master-Slicer',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossAssassin' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['F_MiniBoss01', 'F_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_Story01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Arachne',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: { kind: 'fixed', rewardType: 'Story', producerLifecycleKey: 'RoomReward' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Arachne_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 8 },
    },
  },
  {
    gameName: 'F_Reprieve01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Fountain',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'HealthRestore' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 8 },
    },
  },
  {
    gameName: 'F_Shop01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Midshop',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Shop',
    mode: { kind: 'authored', templateKey: 'Shop' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'ErebusExitDoor' },
      { index: 2, type: 'ErebusExitDoor' },
    ],
    additionalExits: [
      naturalChaosExit,
      {
        kind: 'zagreusContract',
        key: 'zagreusContract',
        exitType: 'ZagContract',
        targetRoomGameName: 'C_Boss01',
        maxEnteredThisRoute: 0,
      },
    ],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4, max: 6 } },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 6 },
  },
  {
    gameName: 'F_PreBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Preboss',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: {
      kind: 'takeOverNormalDoors',
      remainingOffers: {
        kind: 'counted',
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
          producerLifecycleKey: 'RoomReward',
        },
      },
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 10 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 10, deadline: 10 },
  },
  {
    gameName: 'F_Boss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Hecate',
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'automatic', role: 'boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossHecate01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'F_PostBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Postboss',
    hasKeepsakeRack: true,
    hasRequiredFountain: true,
    purgingPool: { slotKeys: ['left', 'middle', 'right'] },
    roomSetKey: 'F',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'automatic', role: 'postboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ErebusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];

export const fRooms = fRoomDeclarations;
