import type { RawRoomDeclaration } from '../types';
import { normalResourcePointSupport } from '../resources';

const naturalChaosExit = {
  kind: 'naturalChaos' as const,
  key: 'naturalChaos' as const,
  exitType: 'ChaosExitDoor',
};

export const gRooms = [
  {
    gameName: 'G_Intro',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Entrance',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 0, deadline: 1 },
  },
  {
    gameName: 'G_Combat01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 01',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 02',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'G_Combat03',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 03',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat04',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 04',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat05',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 05',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat06',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 06',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat07',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 07',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat08',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 08',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat09',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 09',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat10',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 10',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat11',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 11',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat12',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 12',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat13',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 13',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat14',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 14',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat15',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 15',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat16',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 16',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat17',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 17',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'G_Combat18',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 18',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 3 } },
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { max: 2 } },
      ],
    },
  },
  {
    gameName: 'G_Combat19',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 19',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_Combat20',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 20',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
      { index: 3, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'GEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 3 },
    },
  },
  {
    gameName: 'G_MiniBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Deep Serpent',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossWaterUnit' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['G_MiniBoss02', 'G_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'G_MiniBoss02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'King Vermin',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'OceanusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossCrawler' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['G_MiniBoss01', 'G_MiniBoss03'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'G_MiniBoss03',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Hellifish',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossJellyfish' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['G_MiniBoss01', 'G_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'G_Story01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Narcissus',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    lifecycleProfileKey: 'StoryPickupRoom',
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'fixed', rewardType: 'Story', producerLifecycleKey: 'RoomReward' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Narcissus_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 3, max: 6 },
    },
  },
  {
    gameName: 'G_Reprieve01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Fountain',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'HealthRestore' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 6 },
    },
  },
  {
    gameName: 'G_Shop01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Midshop',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Shop',
    mode: { kind: 'authored', templateKey: 'Shop' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'OceanusExitDoor' },
      { index: 2, type: 'OceanusExitDoor' },
    ],
    additionalExits: [
      naturalChaosExit,
      {
        kind: 'zagreusContract',
        key: 'zagreusContract',
        exitType: 'ZagContract',
        targetRoomGameName: 'C_Boss01',
        maxEnteredThisRoute: 0,
      },
    ],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3, max: 5 } },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 6 },
  },
  {
    gameName: 'G_PreBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Preboss',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'OceanusExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: {
      kind: 'takeOverNormalDoors',
      remainingOffers: {
        kind: 'counted',
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
          producerLifecycleKey: 'RoomReward',
        },
      },
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 8 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 8, deadline: 8 },
  },
  {
    gameName: 'G_Boss01',
    resourcePointSupport: normalResourcePointSupport([]),
    label: 'Scylla and the Sirens',
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'automatic', role: 'boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossScylla01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'G_PostBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Postboss',
    hasKeepsakeRack: true,
    hasRequiredFountain: true,
    roomSetKey: 'G',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'automatic', role: 'postboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'OceanusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
