import type { RawRoomDeclaration } from '../types';

const fieldsOptionalRewardCapacities = {
  H_Combat01: 4,
  H_Combat02: 3,
  H_Combat03: 4,
  H_Combat04: 4,
  H_Combat05: 4,
  H_Combat06: 4,
  H_Combat07: 3,
  H_Combat08: 3,
  H_Combat09: 2,
  H_Combat10: 4,
  H_Combat11: 2,
  H_Combat12: 3,
  H_Combat13: 2,
  H_Combat14: 2,
  H_Combat15: 2,
} as const;

function fieldsOptionalRewards(gameName: keyof typeof fieldsOptionalRewardCapacities) {
  return {
    key: 'optionalRewards' as const,
    optionalRewardCapacity: fieldsOptionalRewardCapacities[gameName],
    reward: {
      kind: 'countedChoice' as const,
      storeKeys: ['FieldsOptionalRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
  };
}

export const hRooms = [
  {
    gameName: 'H_Intro',
    label: 'Entrance',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 0, deadline: 1 },
  },
  {
    gameName: 'H_Combat01',
    label: 'Combat 01',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat01'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat02',
    label: 'Combat 02',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat02'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassiveSmall' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat03',
    label: 'Combat 03',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat03'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat04',
    label: 'Combat 04',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat04'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 4,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat05',
    label: 'Combat 05',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat05'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat06',
    label: 'Combat 06',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat06'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat07',
    label: 'Combat 07',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat07'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat08',
    label: 'Combat 08',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat08'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat09',
    label: 'Combat 09',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat09'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassiveSmall' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 2,
        maxActiveSlots: 2,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat10',
    label: 'Combat 10',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat10'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat11',
    label: 'Combat 11',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat11'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat12',
    label: 'Combat 12',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat12'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassive' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat13',
    label: 'Combat 13',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat13'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassiveSmall' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 2,
        maxActiveSlots: 2,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat14',
    label: 'Combat 14',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat14'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassiveSmall' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 2,
        maxActiveSlots: 2,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat15',
    label: 'Combat 15',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    fieldsOptionalRewards: fieldsOptionalRewards('H_Combat15'),
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'FieldsEncounter',
    encounterSlotBindings: [
      { slotKey: 'Passive', kind: 'set', encounterSetKey: 'HEncountersPassiveSmall' },
      { slotKey: 'Cage01', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage02', kind: 'set', encounterSetKey: 'HEncountersDefault' },
      { slotKey: 'Cage03', kind: 'set', encounterSetKey: 'HEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_MiniBoss01',
    label: 'Phantom',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossVampire' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: ['H_MiniBoss02'],
      range: { max: 0 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 4 },
  },
  {
    gameName: 'H_MiniBoss02',
    label: 'Queen Lamia',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossLamia' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: ['H_MiniBoss01'],
      range: { max: 0 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 4 },
  },
  {
    gameName: 'H_Bridge01',
    label: 'Echo',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Echo_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: [
        'H_Combat01',
        'H_Combat02',
        'H_Combat03',
        'H_Combat04',
        'H_Combat05',
        'H_Combat06',
        'H_Combat07',
        'H_Combat08',
        'H_Combat09',
        'H_Combat10',
        'H_Combat11',
        'H_Combat12',
        'H_Combat13',
        'H_Combat14',
        'H_Combat15',
        'H_MiniBoss01',
        'H_MiniBoss02',
      ],
      range: { min: 2, max: 2 },
    },
    force: { kind: 'always' },
  },
  {
    gameName: 'H_PreBoss01',
    label: 'Preboss',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: {
      kind: 'takeOverNormalDoors',
      remainingOffers: {
        kind: 'counted',
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
          producerLifecycleKey: 'RoomReward',
        },
      },
    },
    forcedRewardStoreKey: 'RunProgress',
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: [
        'H_Combat01',
        'H_Combat02',
        'H_Combat03',
        'H_Combat04',
        'H_Combat05',
        'H_Combat06',
        'H_Combat07',
        'H_Combat08',
        'H_Combat09',
        'H_Combat10',
        'H_Combat11',
        'H_Combat12',
        'H_Combat13',
        'H_Combat14',
        'H_Combat15',
        'H_MiniBoss01',
        'H_MiniBoss02',
        'H_Bridge01',
      ],
      range: { min: 4 },
    },
    force: { kind: 'always' },
  },
  {
    gameName: 'H_Boss01',
    label: 'Cerberus',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossInfestedCerberus01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'H_PostBoss01',
    label: 'Postboss',
    roomSetKey: 'H',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
