import type { RawRoomDeclaration } from '../types';

export const hRooms = [
  {
    gameName: 'H_Intro',
    label: 'Entrance',
    biomeKey: 'H',
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'NoEncounter',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 0, deadline: 1 },
  },
  {
    gameName: 'H_Combat01',
    label: 'Combat 01',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat02',
    label: 'Combat 02',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat03',
    label: 'Combat 03',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat04',
    label: 'Combat 04',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 4,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat05',
    label: 'Combat 05',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat06',
    label: 'Combat 06',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat07',
    label: 'Combat 07',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat08',
    label: 'Combat 08',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat09',
    label: 'Combat 09',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage2',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 2,
        maxActiveSlots: 2,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat10',
    label: 'Combat 10',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat11',
    label: 'Combat 11',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 5,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat12',
    label: 'Combat 12',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat13',
    label: 'Combat 13',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage2',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 2,
        maxActiveSlots: 2,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat14',
    label: 'Combat 14',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage2',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 2,
        maxActiveSlots: 2,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_Combat15',
    label: 'Combat 15',
    biomeKey: 'H',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'FieldsCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_FieldsCombatCage3',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { max: 3 },
    },
    localChildren: [
      {
        key: 'cages',
        kind: 'boundedRewardSlots',
        slotKeys: ['cage1', 'cage2', 'cage3'],
        rawCapacity: 3,
        maxActiveSlots: 3,
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion'],
          producerLifecycleKey: 'RoomReward',
        },
        fields: [],
      },
    ],
  },
  {
    gameName: 'H_MiniBoss01',
    label: 'Phantom',
    biomeKey: 'H',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterProfileKey: 'H_MiniBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: ['H_MiniBoss02'],
      range: { max: 0 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 4 },
  },
  {
    gameName: 'H_MiniBoss02',
    label: 'Queen Lamia',
    biomeKey: 'H',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterProfileKey: 'H_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: ['H_MiniBoss01'],
      range: { max: 0 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 4 },
  },
  {
    gameName: 'H_Bridge01',
    label: 'Echo',
    biomeKey: 'H',
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'FieldsExitDoor' },
      { index: 2, type: 'FieldsExitDoor' },
    ],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterProfileKey: 'H_Bridge01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: [
        'H_Combat01',
        'H_Combat02',
        'H_Combat03',
        'H_Combat04',
        'H_Combat05',
        'H_Combat06',
        'H_Combat07',
        'H_Combat08',
        'H_Combat09',
        'H_Combat10',
        'H_Combat11',
        'H_Combat12',
        'H_Combat13',
        'H_Combat14',
        'H_Combat15',
        'H_MiniBoss01',
        'H_MiniBoss02',
      ],
      range: { min: 2, max: 2 },
    },
    force: { kind: 'always' },
  },
  {
    gameName: 'H_PreBoss01',
    label: 'Preboss',
    biomeKey: 'H',
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'ForkedPreboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    entryOfferPolicy: {
      kind: 'shopThenFillRemainingExits',
      freeReward: {
        kind: 'countedChoice',
        storeKeys: ['RunProgress'],
        eligibleRewardTypes: [],
        ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
        producerLifecycleKey: 'RoomReward',
      },
      maxFreeRewards: 1,
    },
    forcedRewardStoreKey: 'RunProgress',
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterProfileKey: 'Shop',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recordCount',
      record: 'roomsEntered',
      keys: [
        'H_Combat01',
        'H_Combat02',
        'H_Combat03',
        'H_Combat04',
        'H_Combat05',
        'H_Combat06',
        'H_Combat07',
        'H_Combat08',
        'H_Combat09',
        'H_Combat10',
        'H_Combat11',
        'H_Combat12',
        'H_Combat13',
        'H_Combat14',
        'H_Combat15',
        'H_MiniBoss01',
        'H_MiniBoss02',
        'H_Bridge01',
      ],
      range: { min: 4 },
    },
    force: { kind: 'always' },
  },
  {
    gameName: 'H_Boss01',
    label: 'Cerberus',
    biomeKey: 'H',
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    individualRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'fixed', storeKey: 'RunProgress' },
    encounterProfileKey: 'H_Boss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'H_PostBoss01',
    label: 'Postboss',
    biomeKey: 'H',
    kind: 'PostBoss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FieldsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'H_PostBoss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
