import type { RawRoomDeclaration } from '../types';

export const iRooms = [
  {
    gameName: 'I_Intro',
    label: 'Entrance',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 0, deadline: 1 },
  },
  {
    gameName: 'I_Story01',
    label: 'Hades',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'fixed', rewardType: 'Story', producerLifecycleKey: 'RoomReward' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Hades_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 4 },
  },
  {
    gameName: 'I_Combat01',
    label: 'Combat 01',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat02',
    label: 'Combat 02',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat03',
    label: 'Combat 03',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat04',
    label: 'Combat 04',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat05',
    label: 'Combat 05',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat06',
    label: 'Combat 06',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat07',
    label: 'Combat 07',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat08',
    label: 'Combat 08',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat09',
    label: 'Combat 09',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat10',
    label: 'Combat 10',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat11',
    label: 'Combat 11',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat12',
    label: 'Combat 12',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat13',
    label: 'Combat 13',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat14',
    label: 'Combat 14',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat15',
    label: 'Combat 15',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat16',
    label: 'Combat 16',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat17',
    label: 'Combat 17',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat18',
    label: 'Combat 18',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat19',
    label: 'Combat 19',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat20',
    label: 'Combat 20',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat21',
    label: 'Combat 21',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat22',
    label: 'Combat 22',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'clockworkNonGoalCapacity', reserve: 1 },
  },
  {
    gameName: 'I_Combat23',
    label: 'Combat 23',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_Combat24',
    label: 'Combat 24',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ClockworkCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Boon'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'IEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 5 } },
  },

  {
    gameName: 'I_Reprieve01',
    label: 'Fountain',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'HealthRestore' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        { kind: 'clockworkNonGoalCapacity', reserve: 1 },
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
  },
  {
    gameName: 'I_MiniBoss01',
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Duo: 0.2, Legendary: 0.2 },
    label: 'The Verminancer',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossRatCatcher' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['I_MiniBoss02'],
          range: { max: 0 },
        },
        { kind: 'clockworkNonGoalCapacity', reserve: 1 },
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 7 },
  },
  {
    gameName: 'I_MiniBoss02',
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Duo: 0.2, Legendary: 0.2 },
    label: 'Goldwrath',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TartarusExitDoor' },
      { index: 2, type: 'TartarusExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TartarusRewards'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TartarusRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossGoldElemental' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['I_MiniBoss01'],
          range: { max: 0 },
        },
        { kind: 'clockworkNonGoalCapacity', reserve: 1 },
        { kind: 'currentBatchTargetCount', range: { min: 1 } },
        {
          kind: 'currentBatchRoomCount',
          roomGameNames: ['I_Story01', 'I_Reprieve01', 'I_MiniBoss01', 'I_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 7 },
  },
  {
    gameName: 'I_PreBoss02',
    label: 'Preboss',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'I_WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: { kind: 'retainNormalPeers' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsPerRoom: 1 },
    eligibility: { kind: 'clockworkGoalsRemaining', range: { max: 0 } },
    force: { kind: 'always' },
  },
  {
    gameName: 'I_Boss01',
    label: 'Chronos',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'automatic', role: 'boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossChronos01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'I_PostBoss01',
    label: 'Postboss',
    roomSetKey: 'I',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'automatic', role: 'postboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TartarusExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
