import type { RawRoomDeclaration } from './types';
import { nResourcePointSupport } from '../resources';
import { soulPylon } from './n-shared';

export const nHubMainRooms = [
  {
    gameName: 'N_Hub',
    resourcePointSupport: nResourcePointSupport([]),
    label: 'Ephyra Hub',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Hub',
    mode: { kind: 'derived', classification: 'hub' },
    structuralTags: [],
    exits: [],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    unmodeledEncounterKeys: ['Empty'],
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Combat01',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 01',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat02',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 02',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub01',
            physicalDoorId: 558353,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub03',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat03',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 03',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub04',
            physicalDoorId: 558353,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat04',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 04',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub02',
            physicalDoorId: 558834,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub06',
            physicalDoorId: 558410,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat05',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 05',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub02',
            physicalDoorId: 558354,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub07',
            physicalDoorId: 558378,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub03',
            physicalDoorId: 558379,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat06',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 06',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub10',
            physicalDoorId: 558378,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub05',
            physicalDoorId: 560794,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat07',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 07',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat08',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Shovel']),
    label: 'Combat 08',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat09',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 09',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub11',
            physicalDoorId: 566392,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub08',
            physicalDoorId: 566536,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub14',
            physicalDoorId: 566394,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat10',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 10',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub05',
            physicalDoorId: 558352,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub09',
            physicalDoorId: 567015,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat11',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 11',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub01',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat12',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 12',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['WeaponUpgrade', 'HermesUpgrade'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub09',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub10',
            physicalDoorId: 566544,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub07',
            physicalDoorId: 566545,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat13',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 13',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat14',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 14',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat15',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 15',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub03',
            physicalDoorId: 657623,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat16',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 16',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub04',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat17',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 17',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['WeaponUpgrade', 'HermesUpgrade'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub11',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat18',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 18',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub12',
            physicalDoorId: 658853,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat19',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 19',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat20',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 20',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub06',
            physicalDoorId: 659508,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat21',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 21',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat22',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 22',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub14',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub02',
            physicalDoorId: 661338,
            availabilityRank: 2,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat23',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 23',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub12',
            physicalDoorId: 755971,
            availabilityRank: 3,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub13',
            physicalDoorId: 755184,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub15',
            physicalDoorId: 755185,
            availabilityRank: 2,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_MiniBoss01',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Satyr Champion',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossSatyrCrossbow' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_MiniBoss02',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Erymanthian Boar',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossBoar' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Story01',
    resourcePointSupport: nResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Medea',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Medea_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
] satisfies readonly RawRoomDeclaration[];
