import type { RawRoomDeclaration } from '../types';

const naturalChaosExit = {
  kind: 'naturalChaos' as const,
  key: 'naturalChaos' as const,
  exitType: 'ChaosExitDoor',
};

const soulPylon = {
  key: 'SoulPylon',
  spawnTiming: 'roomEntry',
  completionRequirement: 'destroyBeforeExit',
} as const;

export const nRooms = [
  {
    gameName: 'N_Opening01',
    label: 'Opening',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Opening',
    mode: { kind: 'authored', templateKey: 'FixedOpening' },
    lifecycleProfileKey: 'OpeningRewardRoom',
    additionalExits: [naturalChaosExit],
    structuralTags: [],
    exits: [{ index: 1, type: 'N_OpeningDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'OpeningGeneratedN',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_PreHub01',
    label: 'Pre-Hub',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'PreHub',
    mode: { kind: 'authored', templateKey: 'FixedPreHub' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop', 'MaxHealthDrop', 'MaxManaDrop'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'PreHubGeneratedN',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
  },
  {
    gameName: 'N_Hub',
    label: 'Ephyra Hub',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Hub',
    mode: { kind: 'derived', classification: 'hub' },
    structuralTags: [],
    exits: [],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Combat01',
    label: 'Combat 01',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat02',
    label: 'Combat 02',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub01',
            physicalDoorId: 558353,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub03',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat03',
    label: 'Combat 03',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub04',
            physicalDoorId: 558353,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat04',
    label: 'Combat 04',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub02',
            physicalDoorId: 558834,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub06',
            physicalDoorId: 558410,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat05',
    label: 'Combat 05',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub02',
            physicalDoorId: 558354,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub07',
            physicalDoorId: 558378,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub03',
            physicalDoorId: 558379,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat06',
    label: 'Combat 06',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub10',
            physicalDoorId: 558378,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub05',
            physicalDoorId: 560794,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat07',
    label: 'Combat 07',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat08',
    label: 'Combat 08',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat09',
    label: 'Combat 09',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub11',
            physicalDoorId: 566392,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub08',
            physicalDoorId: 566536,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub14',
            physicalDoorId: 566394,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat10',
    label: 'Combat 10',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub05',
            physicalDoorId: 558352,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub09',
            physicalDoorId: 567015,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat11',
    label: 'Combat 11',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub01',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat12',
    label: 'Combat 12',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['WeaponUpgrade', 'HermesUpgrade'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub09',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub10',
            physicalDoorId: 566544,
            availabilityRank: 2,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub07',
            physicalDoorId: 566545,
            availabilityRank: 3,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat13',
    label: 'Combat 13',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat14',
    label: 'Combat 14',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat15',
    label: 'Combat 15',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub03',
            physicalDoorId: 657623,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat16',
    label: 'Combat 16',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub04',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat17',
    label: 'Combat 17',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['WeaponUpgrade', 'HermesUpgrade'],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSmaller' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub11',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat18',
    label: 'Combat 18',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub12',
            physicalDoorId: 658853,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat19',
    label: 'Combat 19',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat20',
    label: 'Combat 20',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub06',
            physicalDoorId: 659508,
            availabilityRank: 1,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat21',
    label: 'Combat 21',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersBigger' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Combat22',
    label: 'Combat 22',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub14',
            physicalDoorId: 558352,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub02',
            physicalDoorId: 661338,
            availabilityRank: 2,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_Combat23',
    label: 'Combat 23',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['HubRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'HubRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    requiredObjects: [soulPylon],
    localChildren: [
      {
        key: 'sideRooms',
        kind: 'fixedRoomSlots',
        slots: [
          {
            slotKey: 'sideDoor1',
            roomGameName: 'N_Sub12',
            physicalDoorId: 755971,
            availabilityRank: 3,
          },
          {
            slotKey: 'sideDoor2',
            roomGameName: 'N_Sub13',
            physicalDoorId: 755184,
            availabilityRank: 1,
          },
          {
            slotKey: 'sideDoor3',
            roomGameName: 'N_Sub15',
            physicalDoorId: 755185,
            availabilityRank: 2,
          },
        ],
        rewardGeneration: 'jointUnordered',
        fields: [],
      },
    ],
  },
  {
    gameName: 'N_MiniBoss01',
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Satyr Champion',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossSatyrCrossbow' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_MiniBoss02',
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Erymanthian Boar',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossBoar' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Story01',
    label: 'Medea',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Medea_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxCreationsThisRun: 1 },
    requiredObjects: [soulPylon],
  },
  {
    gameName: 'N_Sub01',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 01',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub02',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 02',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoomLight' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub03',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 03',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub04',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 04',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub05',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 05',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub06',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 06',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub07',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 07',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub08',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 08',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub09',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 09',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: false,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub10',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 10',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub11',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 11',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub12',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 12',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub13',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 13',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub14',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 14',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewardsHard'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewardsHard',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Encounter',
        kind: 'fixed',
        encounterDefinitionKey: 'GeneratedNSubRoom_Bigger',
      },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_Sub15',
    blocksGorgon: true,
    skipRoomsPerUpgrade: true,
    label: 'Side Room 15',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'EphyraSideRoom' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['SubRoomRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    individualRewardStoreKey: 'SubRoomRewards',
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'NEncountersSubRoom' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 999 },
  },
  {
    gameName: 'N_PreBoss01',
    label: 'Preboss',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
      additionalOptionRequirements: {
        WeaponUpgradeDropEarly: {
          kind: 'rewardLookupExcludes',
          lookupKey: 'hubRewardLookup',
          rewardType: 'WeaponUpgrade',
        },
        SpellDrop: {
          kind: 'rewardLookupExcludes',
          lookupKey: 'hubRewardLookup',
          rewardType: 'SpellDrop',
        },
      },
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: { kind: 'takeOverNormalDoors', remainingOffers: { kind: 'none' } },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_Boss01',
    label: 'Polyphemus',
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'automatic', role: 'boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'EphyraExitDoorReturn' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossPolyphemus01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'N_PostBoss01',
    label: 'Postboss',
    hasKeepsakeRack: true,
    hasRequiredFountain: true,
    roomSetKey: 'N',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'automatic', role: 'postboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] satisfies readonly RawRoomDeclaration[];
