import type { RawRoomDeclaration } from '../types';
import { normalResourcePointSupport } from '../resources';

const surfaceShopHost = (spawnChance: number, forced = false, challengeSwitchAnchorCount = 1) => ({
  challengeSwitchAnchorCount,
  surfaceShop: {
    profileKey: 'SurfaceShop' as const,
    spawnChance,
    ...(forced ? { forced: true as const } : {}),
  },
});

export const oRooms = [
  {
    gameName: 'O_Intro',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Entrance',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 0, deadline: 1 },
  },
  {
    gameName: 'O_Combat01',
    ...surfaceShopHost(0.125, false, 0),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 01',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat02',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 02',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat03',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 03',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat04',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 04',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 3 } },
  },
  {
    gameName: 'O_Combat05',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 05',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat06',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 06',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat07',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 07',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 3 } },
  },
  {
    gameName: 'O_Combat08',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 08',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat09',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 09',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat10',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 10',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat11',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 11',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 3 } },
  },
  {
    gameName: 'O_Combat12',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 12',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat13',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 13',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 6 } },
        {
          kind: 'recentEnvelopeSlotCount',
          envelopeKey: 'ShipEncounter',
          slotKey: 'Intro',
          roomWindow: 3,
          range: { min: 3 },
        },
      ],
    },
  },
  {
    gameName: 'O_Combat14',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 14',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'recentEnvelopeSlotCount',
      envelopeKey: 'ShipEncounter',
      slotKey: 'Intro',
      roomWindow: 3,
      range: { max: 2 },
    },
  },
  {
    gameName: 'O_Combat15',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 15',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'ShipCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'ShipEncounter',
    encounterSlotBindings: [
      { slotKey: 'Intro', kind: 'set', encounterSetKey: 'OEncountersIntros' },
      { slotKey: 'Combat1', kind: 'set', encounterSetKey: 'OEncountersDefault' },
      { slotKey: 'Combat2', kind: 'set', encounterSetKey: 'OEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 3 } },
  },
  {
    gameName: 'O_MiniBoss01',
    ...surfaceShopHost(0.125, false, 0),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'Charybdis',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossCharybdis' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3, max: 5 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['O_MiniBoss02'],
          range: { max: 0 },
        },
      ],
    },
  },
  {
    gameName: 'O_MiniBoss02',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Legendary: 0.05 },
    label: 'The Yargonaut',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossCaptain' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 3, max: 5 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['O_MiniBoss01'],
          range: { max: 0 },
        },
      ],
    },
  },
  {
    gameName: 'O_Shop01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Midshop',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Shop',
    mode: { kind: 'authored', templateKey: 'Shop' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    additionalExits: [
      {
        kind: 'zagreusContract',
        key: 'zagreusContract',
        exitType: 'ZagContract',
        targetRoomGameName: 'C_Boss01',
        maxEnteredThisRoute: 0,
      },
    ],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 4 } },
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 5 } },
      ],
    },
    force: {
      kind: 'requirement',
      requirement: {
        kind: 'all',
        requirements: [
          { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 5, max: 5 } },
          {
            kind: 'recordCount',
            record: 'roomsEntered',
            keys: ['O_Shop01', 'O_Story01'],
            range: { max: 0 },
          },
        ],
      },
    },
  },
  {
    gameName: 'O_Reprieve01',
    ...surfaceShopHost(1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Fountain',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'HealthRestore' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 3, max: 5 },
    },
  },
  {
    gameName: 'O_Story01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing'], {
      ignoresBiomeLimit: true,
    }),
    label: 'Circe',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Circe_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 4 } },
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 5 } },
      ],
    },
    force: {
      kind: 'requirement',
      requirement: {
        kind: 'all',
        requirements: [
          { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 5, max: 5 } },
          {
            kind: 'recordCount',
            record: 'roomsEntered',
            keys: ['O_Shop01', 'O_Story01'],
            range: { max: 0 },
          },
        ],
      },
    },
  },
  {
    gameName: 'O_Devotion01',
    ...surfaceShopHost(0.125, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Trial',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Devotion',
    mode: { kind: 'authored', templateKey: 'Devotion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Devotion',
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'DevotionTestO' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 2 } },
        {
          kind: 'distinctRecordKeyCount',
          record: 'lootTypeHistory',
          keys: [
            'AphroditeUpgrade',
            'ApolloUpgrade',
            'DemeterUpgrade',
            'HephaestusUpgrade',
            'HeraUpgrade',
            'HestiaUpgrade',
            'PoseidonUpgrade',
            'ZeusUpgrade',
          ],
          range: { min: 2 },
        },
      ],
    },
  },
  {
    gameName: 'O_PreBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Preboss',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: { kind: 'takeOverNormalDoors', remainingOffers: { kind: 'none' } },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 7 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 7, deadline: 7 },
  },
  {
    gameName: 'O_Boss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Eris',
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'authored', templateKey: 'Boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossEris01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'O_PostBoss01',
    resourcePointSupport: normalResourcePointSupport([]),
    label: 'Postboss',
    hasKeepsakeRack: true,
    hasRequiredFountain: true,
    ...surfaceShopHost(1, true),
    roomSetKey: 'O',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'authored', templateKey: 'PostBoss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'ShipsExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
