import type { RawRoomDeclaration } from '../types';
import { normalResourcePointSupport } from '../resources';

const surfaceShopHost = (spawnChance: number, forced = false, challengeSwitchAnchorCount = 1) => ({
  challengeSwitchAnchorCount,
  surfaceShop: { profileKey: 'SurfaceShop' as const, spawnChance, ...(forced ? { forced: true as const } : {}) },
});

const naturalChaosExit = {
  kind: 'naturalChaos' as const,
  key: 'naturalChaos' as const,
  exitType: 'ChaosExitDoor',
  requirement: {
    kind: 'counterRange' as const,
    axis: 'biomeDepthCache' as const,
    range: { max: 5 },
  },
};

export const pRooms = [
  {
    gameName: 'P_Intro',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Entrance',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusOutdoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'set', encounterSetKey: 'POpeningEncounters' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat01',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 01',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat01IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'P_Combat02',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 02',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat02IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat03',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 03',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat03IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { max: 4 },
    },
  },
  {
    gameName: 'P_Combat04',
    ...surfaceShopHost(.13, false, 0),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 04',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat04IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat05',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 05',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat05IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat06',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 06',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat06IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat07',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 07',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat07IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat08',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 08',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat08IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat09',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Shovel']),
    label: 'Combat 09',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat09IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat10',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 10',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat10IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat11',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 11',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat11IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat12',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 12',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat12IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat13',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 13',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat13IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat14',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 14',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat14IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat15',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 15',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat15IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat16',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 16',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PCombat16IntroEncounters',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Combat17',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 17',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PEncountersIntros',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'P_Combat18',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 18',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PEncountersIntros',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeEncounterDepth',
      range: { min: 3 },
    },
  },
  {
    gameName: 'P_Combat19',
    ...surfaceShopHost(.13, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 19',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'StandardCombat' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'PEncounter',
    encounterSlotBindings: [
      {
        slotKey: 'Intro',
        kind: 'set',
        encounterSetKey: 'PEncountersIntros',
      },
      { slotKey: 'Combat', kind: 'set', encounterSetKey: 'PEncountersDefault' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_Story01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Dionysus',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Story',
    mode: { kind: 'authored', templateKey: 'Story' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    incomingReward: {
      kind: 'fixed',
      rewardType: 'Story',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Story_Dionysus_01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 3 } },
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 7 } },
      ],
    },
  },
  {
    gameName: 'P_Reprieve01',
    ...surfaceShopHost(1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Fountain',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Reprieve',
    mode: { kind: 'authored', templateKey: 'Fountain' },
    additionalExits: [naturalChaosExit],
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress', 'MetaProgress'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: ['Devotion'],
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'HealthRestore' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4, max: 7 },
    },
  },
  {
    gameName: 'P_Shop01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Midshop',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Shop',
    mode: { kind: 'authored', templateKey: 'Shop' },
    structuralTags: ['Outdoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusOutdoorExitDoor' },
    ],
    additionalExits: [
      naturalChaosExit,
      {
        kind: 'zagreusContract',
        key: 'zagreusContract',
        exitType: 'ZagContract',
        targetRoomGameName: 'C_Boss01',
        maxEnteredThisRoute: 0,
      },
    ],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeEncounterDepth', range: { min: 5 } },
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { max: 7 } },
      ],
    },
  },
  {
    gameName: 'P_MiniBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Duo: 0.2, Legendary: 0.2 },
    label: 'Talos',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: ['Indoor'],
    exits: [
      { index: 1, type: 'OlympusIndoorExitDoor' },
      { index: 2, type: 'OlympusIndoorExitDoor' },
    ],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossTalos' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['P_MiniBoss02'],
          range: { max: 0 },
        },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'P_MiniBoss02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    boonRarityOverride: { Rare: 0.9, Epic: 0.1, Duo: 0.2, Legendary: 0.2 },
    label: 'Mega-Dracon',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: ['Indoor'],
    exits: [{ index: 1, type: 'OlympusOutdoorExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['RunProgress'],
      eligibleRewardTypes: ['Boon'],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossDragon' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1, maxCreationsThisRun: 1 },
    eligibility: {
      kind: 'all',
      requirements: [
        { kind: 'counterRange', axis: 'biomeDepthCache', range: { min: 4 } },
        {
          kind: 'recordCount',
          record: 'roomsEntered',
          keys: ['P_MiniBoss01'],
          range: { max: 0 },
        },
        { kind: 'minExits', count: 2 },
      ],
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 4, deadline: 7 },
  },
  {
    gameName: 'P_PreBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Preboss',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: ['Indoor', 'Outdoor'],
    exits: [{ index: 1, type: 'OlympusIndoorExitDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: {
      kind: 'takeOverNormalDoors',
      remainingOffers: {
        kind: 'counted',
        reward: {
          kind: 'countedChoice',
          storeKeys: ['RunProgress'],
          eligibleRewardTypes: [],
          ineligibleRewardTypes: ['Devotion', 'RoomMoneyDrop'],
          producerLifecycleKey: 'RoomReward',
        },
      },
    },
    forcedRewardStoreKey: 'RunProgress',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 9 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 9, deadline: 9 },
  },
  {
    gameName: 'P_Boss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Prometheus',
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'automatic', role: 'boss' },
    structuralTags: ['Indoor', 'Outdoor'],
    exits: [{ index: 1, type: 'OlympusIndoorExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossPrometheus01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'P_PostBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Postboss',
    hasKeepsakeRack: true,
    hasRequiredFountain: true,
    ...surfaceShopHost(1, true),
    roomSetKey: 'P',
    advancesExperimentalHammerUses: true,
    kind: 'PostBoss',
    mode: { kind: 'automatic', role: 'postboss' },
    structuralTags: ['Indoor', 'Outdoor'],
    exits: [{ index: 1, type: 'OlympusOutdoorExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Empty' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
