import type { RawRoomDeclaration } from '../types';
import { normalResourcePointSupport } from '../resources';

const surfaceShopHost = (spawnChance: number, forced = false, challengeSwitchAnchorCount = 1) => ({
  challengeSwitchAnchorCount,
  surfaceShop: {
    profileKey: 'SurfaceShop' as const,
    spawnChance,
    ...(forced ? { forced: true as const } : {}),
  },
});

export const qRooms = [
  {
    gameName: 'Q_Intro',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Entrance',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: ['Outdoor'],
    exits: [{ index: 1, type: 'FortressMainDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'EmptyEncounter',
    encounterSlotBindings: [],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 1, deadline: 1 },
  },
  {
    gameName: 'Q_Combat01',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 01',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat02',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 02',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat03',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 03',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ_Islands' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 2 },
  },
  {
    gameName: 'Q_Combat04',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 04',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat05',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 05',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ_Islands' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 2 },
  },
  {
    gameName: 'Q_Combat06',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 06',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4 },
    },
  },
  {
    gameName: 'Q_Combat07',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 07',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
  },
  {
    gameName: 'Q_Combat08',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel']),
    label: 'Combat 08',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat09',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 09',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4 },
    },
  },
  {
    gameName: 'Q_Combat10',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 10',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ_Large' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
  },
  {
    gameName: 'Q_Combat11',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 11',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ_Large' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
  },
  {
    gameName: 'Q_Combat12',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 12',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 5, deadline: 5 },
  },
  {
    gameName: 'Q_Combat13',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 13',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 5, deadline: 5 },
  },
  {
    gameName: 'Q_Combat14',
    ...surfaceShopHost(0.1, false, 0),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 14',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 5, deadline: 5 },
  },
  {
    gameName: 'Q_Combat15',
    ...surfaceShopHost(0.1, false, 0),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 15',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 2 },
  },
  {
    gameName: 'Q_Combat16',
    ...surfaceShopHost(0.1, false, 1),
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Combat 16',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'GeneratedQ' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
  },
  {
    gameName: 'Q_MiniBoss02',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 1, Epic: 0.7, Duo: 0.2, Legendary: 0.2 },
    label: 'Brute',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossBrute' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 3 },
  },
  {
    gameName: 'Q_MiniBoss05',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 1, Epic: 0.7, Duo: 0.2, Legendary: 0.2 },
    label: 'Stalker',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'MiniBossStalker' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 3 },
  },
  {
    gameName: 'Q_MiniBoss03',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 1, Epic: 0.7, Duo: 0.2, Legendary: 0.2 },
    label: 'Tail',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossTyphonTail01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 6, deadline: 6 },
  },
  {
    gameName: 'Q_MiniBoss04',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    boonRarityOverride: { Rare: 1, Epic: 0.7, Duo: 0.2, Legendary: 0.2 },
    label: 'Eye',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossTyphonEye01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 6, deadline: 6 },
  },
  {
    gameName: 'Q_PreBoss01',
    resourcePointSupport: normalResourcePointSupport(['Pickaxe', 'Exorcism', 'Shovel', 'Fishing']),
    label: 'Preboss',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'Preboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FortressMainDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'Q_WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    infernalContractReward: {
      entryKey: 'infernalContractReward',
      producerLifecycleKey: 'ZagPedestal',
      rewardTypes: [
        'BlindBoxLoot',
        'StackUpgradeBig',
        'StackUpgrade',
        'TalentBigDrop',
        'TalentDrop',
      ],
    },
    prebossBatchPolicy: { kind: 'takeOverNormalDoors', remainingOffers: { kind: 'none' } },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'Shop' },
    ],
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 7 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 7, deadline: 7 },
  },
  {
    gameName: 'Q_Boss01',
    resourcePointSupport: normalResourcePointSupport([]),
    label: 'Typhon',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'authored', templateKey: 'Boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossTyphonHead01' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
  {
    gameName: 'Q_Boss02',
    resourcePointSupport: normalResourcePointSupport([]),
    label: 'Typhon',
    roomSetKey: 'Q',
    advancesExperimentalHammerUses: true,
    kind: 'Boss',
    mode: { kind: 'authored', templateKey: 'Boss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterEnvelopeKey: 'SingleEncounter',
    encounterSlotBindings: [
      { slotKey: 'Encounter', kind: 'fixed', encounterDefinitionKey: 'BossTyphonHead02' },
    ],
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
