import type { RawRoomDeclaration } from '../types';

export const qRooms = [
  {
    gameName: 'Q_Intro',
    label: 'Entrance',
    biomeKey: 'Q',
    kind: 'Intro',
    mode: { kind: 'authored', templateKey: 'FixedIntro' },
    structuralTags: ['Outdoor'],
    exits: [{ index: 1, type: 'FortressMainDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'NoEncounter',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 1, deadline: 1 },
  },
  {
    gameName: 'Q_Combat01',
    label: 'Combat 01',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat02',
    label: 'Combat 02',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat03',
    label: 'Combat 03',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 2 },
  },
  {
    gameName: 'Q_Combat04',
    label: 'Combat 04',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat05',
    label: 'Combat 05',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 2 },
  },
  {
    gameName: 'Q_Combat06',
    label: 'Combat 06',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4 },
    },
  },
  {
    gameName: 'Q_Combat07',
    label: 'Combat 07',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
  },
  {
    gameName: 'Q_Combat08',
    label: 'Combat 08',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2, max: 6 },
    },
  },
  {
    gameName: 'Q_Combat09',
    label: 'Combat 09',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 4 },
    },
  },
  {
    gameName: 'Q_Combat10',
    label: 'Combat 10',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
  },
  {
    gameName: 'Q_Combat11',
    label: 'Combat 11',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 1, max: 1 },
    },
  },
  {
    gameName: 'Q_Combat12',
    label: 'Combat 12',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 5, deadline: 5 },
  },
  {
    gameName: 'Q_Combat13',
    label: 'Combat 13',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 5, deadline: 5 },
  },
  {
    gameName: 'Q_Combat14',
    label: 'Combat 14',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 5, deadline: 5 },
  },
  {
    gameName: 'Q_Combat15',
    label: 'Combat 15',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [
      { index: 1, type: 'TyphonExitDoor' },
      { index: 2, type: 'TyphonExitDoor' },
    ],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 2, deadline: 2 },
  },
  {
    gameName: 'Q_Combat16',
    label: 'Combat 16',
    biomeKey: 'Q',
    kind: 'Combat',
    mode: { kind: 'authored', templateKey: 'RewardlessCombat' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'SingleCountedCombat',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 2 },
    },
  },
  {
    gameName: 'Q_MiniBoss02',
    label: 'Brute',
    biomeKey: 'Q',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Q_MiniBoss02',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 3 },
  },
  {
    gameName: 'Q_MiniBoss05',
    label: 'Stalker',
    biomeKey: 'Q',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Q_MiniBoss05',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 3, deadline: 3 },
  },
  {
    gameName: 'Q_MiniBoss03',
    label: 'Tail',
    biomeKey: 'Q',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Q_MiniBoss03',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 6, deadline: 6 },
  },
  {
    gameName: 'Q_MiniBoss04',
    label: 'Eye',
    biomeKey: 'Q',
    kind: 'Miniboss',
    mode: { kind: 'authored', templateKey: 'Miniboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: {
      kind: 'countedChoice',
      storeKeys: ['TyphonBossRewards'],
      eligibleRewardTypes: [],
      ineligibleRewardTypes: [],
      producerLifecycleKey: 'RoomReward',
    },
    forcedRewardStoreKey: 'TyphonBossRewards',
    enteredRewardStoreHistory: { kind: 'resolvedOffer' },
    encounterProfileKey: 'Q_MiniBoss04',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 6, deadline: 6 },
  },
  {
    gameName: 'Q_PreBoss01',
    label: 'Preboss',
    biomeKey: 'Q',
    kind: 'Preboss',
    mode: { kind: 'authored', templateKey: 'ShopPreboss' },
    structuralTags: [],
    exits: [{ index: 1, type: 'FortressMainDoor' }],
    incomingReward: {
      kind: 'shop',
      rewardType: 'Shop',
      shopProfileKey: 'Q_WorldShop',
      producerLifecycleKey: 'RoomReward',
    },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'Shop',
    counters: { biomeDepthCache: 0, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
    eligibility: {
      kind: 'counterRange',
      axis: 'biomeDepthCache',
      range: { min: 7 },
    },
    force: { kind: 'depthWindow', axis: 'biomeDepthCache', start: 7, deadline: 7 },
  },
  {
    gameName: 'Q_Boss01',
    label: 'Typhon',
    biomeKey: 'Q',
    kind: 'Boss',
    mode: { kind: 'derived', classification: 'completion' },
    structuralTags: [],
    exits: [{ index: 1, type: 'TyphonExitDoor' }],
    incomingReward: { kind: 'none' },
    enteredRewardStoreHistory: { kind: 'none' },
    encounterProfileKey: 'Q_Boss01',
    counters: { biomeDepthCache: 1, roomHistoryOrdinal: 1 },
    caps: { maxAppearancesThisBiome: 1 },
  },
] as const satisfies readonly RawRoomDeclaration[];
