/**
 * Stable application and React entry point for the structured editor
 * workspace. Construction and contract implementation remain private to this
 * directory so consumers depend on one deliberate projection boundary.
 */
export {
  StructuredWorkspaceProjectionContractError,
  requireWorkspaceInteraction,
  workspaceInteractionKey,
  workspaceSideRoomEntryOrderKey,
} from './contract';
export type {
  StructuredWorkspaceContextualServices,
  StructuredWorkspaceProjection,
  StructuredWorkspaceProjectionService,
  WorkspaceAssessment,
  WorkspaceAuthoredLeafInteractionKind,
  WorkspaceAuthoredLeafInteractionRequirement,
  WorkspaceAuthoredLeafRequirement,
  WorkspaceAuthoringFrontier,
  WorkspaceBatchRepairScope,
  WorkspaceBiome,
  WorkspaceBiomeField,
  WorkspaceCandidateInteraction,
  WorkspaceCandidateTakeoverBatchInteraction,
  WorkspaceCompletedHubHandoffInteraction,
  WorkspaceCompletionNode,
  WorkspaceCountedRewardControl,
  WorkspaceDefaultInspectorDestination,
  WorkspaceEphyraSideRoomDescriptor,
  WorkspaceEphyraSideRoomEntryOption,
  WorkspaceEphyraSideRoomEntryOrderControl,
  WorkspaceEphyraSideRoomGroup,
  WorkspaceEphyraSideRoomSurface,
  WorkspaceExitFrontierCapabilities,
  WorkspaceExitSelectionInteraction,
  WorkspaceExplicitRewardControl,
  WorkspaceFieldsBatchContext,
  WorkspaceFieldsCageDescriptor,
  WorkspaceFixedWidthOneTakeoverActionResult,
  WorkspaceFixedWidthOneTakeoverInteraction,
  WorkspaceHubDecisionNode,
  WorkspaceHubRailEntry,
  WorkspaceHubSlot,
  WorkspaceHubSlotInteraction,
  WorkspaceHubVisit,
  WorkspaceHubVisitRailEntry,
  WorkspaceHubVisitState,
  WorkspaceInspectorDestination,
  WorkspaceInspectorSubject,
  WorkspaceInteractionCatalog,
  WorkspaceInteractionChoice,
  WorkspaceLinkedExitNode,
  WorkspaceMarker,
  WorkspaceMissingPhysicalTarget,
  WorkspaceMissingTargetAuthoring,
  WorkspaceMixedBatchNode,
  WorkspaceNode,
  WorkspaceOccurrenceWorkbenchNode,
  WorkspaceOrdinaryBatchNode,
  WorkspacePhysicalTarget,
  WorkspaceProjectionSource,
  WorkspaceRailEntry,
  WorkspaceRewardControl,
  WorkspaceRewardInteraction,
  WorkspaceRewardWheelDescriptor,
  WorkspaceRewardWheelOfferDescriptor,
  WorkspaceRoomInteraction,
  WorkspaceRoomLocal,
  WorkspaceRoomPickerControl,
  WorkspaceRoomSummary,
  WorkspaceRoute,
  WorkspaceRouteRailBiome,
  WorkspaceShopOfferDescriptor,
  WorkspaceShopPurchaseDescriptor,
  WorkspaceStageDecisionRemoval,
  WorkspaceStartInteraction,
  WorkspaceStatus,
  WorkspaceStructuralInteraction,
  WorkspaceTakeoverBatchInteraction,
  WorkspaceTakeoverBatchNode,
  WorkspaceTakeoverCandidate,
  WorkspaceTakeoverRepairInteraction,
  WorkspaceTakeoverReplacementImpact,
  WorkspaceTopologyRemovalInteraction,
  WorkspaceTopologyRemovalScope,
} from './contract';
export {
  assertAuthoredWorkspaceLeafInteractionClosure,
  assertAuthoredWorkspaceLeafProjectionClosure,
  assertWorkspaceInteractionClosure,
  authoredWorkspaceLeafRequirements,
  createStructuredWorkspaceProjection,
} from './projector';
