/**
 * Stable application and React entry point for the structured editor
 * workspace. Construction and contract implementation remain private to this
 * directory so consumers depend on one deliberate projection boundary.
 */
export { requireWorkspaceInteraction, workspaceInteractionKey } from './contract';
export {
  dropRankedPrefixItem,
  moveRankedPrefixItem,
  reconcileRankedPrefix,
} from './presentation/hub-ranking';
export {
  echoLastRunOptionControl,
  findingControlKey,
  findingRepairTarget,
} from './navigation/finding-highlights';
export type {
  WorkspaceDefaultInspectorDestination,
  WorkspaceFindingControl,
  WorkspaceHubTab,
  WorkspaceInspectorDestination,
  WorkspaceMarker,
  WorkspaceRoomTab,
} from './contracts/navigation';
export type {
  WorkspaceRunStateBagSection,
  WorkspaceRunStateLauncher,
  WorkspaceRunStatePresentation,
  WorkspaceRunStateRow,
  WorkspaceRunStateSection,
} from './contracts/run-state';
export type {
  StructuredWorkspaceProjection,
  StructuredWorkspaceProjectionService,
  WorkspaceAuthoringFrontier,
  WorkspaceBatchRepairIntent,
  WorkspaceBiome,
  WorkspaceBiomeField,
  WorkspaceDoorContract,
  WorkspaceDoorReward,
  WorkspaceHubDecisionNode,
  WorkspaceHubFountain,
  WorkspaceHubRequirements,
  WorkspaceHubSlot,
  WorkspaceHubVisit,
  WorkspaceInheritedRewardStore,
  WorkspaceMissingPhysicalTarget,
  WorkspaceMixedBatchNode,
  WorkspaceNode,
  WorkspaceOccurrenceStage,
  WorkspaceOccurrenceStageOutgoing,
  WorkspaceOccurrenceWorkbenchNode,
  WorkspaceOrdinaryBatchNode,
  WorkspacePhysicalTarget,
  WorkspaceRailEntry,
  WorkspaceRailReward,
  WorkspaceRailSelectedTarget,
  WorkspaceRoute,
  WorkspaceTakeoverBatchNode,
} from './contracts/structure';
export type {
  WorkspaceCandidateInteraction,
  WorkspaceNativeCandidateInteraction,
  WorkspacePickerCandidateInteraction,
  WorkspaceCompletedHubHandoffInteraction,
  WorkspaceCommandIntent,
  WorkspaceEncounterInteraction,
  WorkspaceEncounterCustomizationInteraction,
  WorkspaceGeneratedEncounterAssessment,
  WorkspaceEncounterComposition,
  WorkspaceGeneratedWaveDraftChoice,
  WorkspaceGeneratedFangsDraftChoice,
  WorkspaceInfiniteRosterDraftChoice,
  WorkspaceNemesisEventInteraction,
  WorkspaceNemesisEventDomain,
  WorkspaceNemesisFeatureInteraction,
  WorkspaceEncounterPhase,
  WorkspaceLocalVisitDecision,
  WorkspaceLocalVisitGenerationInteraction,
  WorkspaceLocalVisitOrderInteraction,
  WorkspaceLocalVisitOrderControl,
  WorkspaceLocalVisitOrderOption,
  WorkspaceLocalVisitSlot,
  WorkspaceExitSelectionInteraction,
  WorkspaceRoomActionInteraction,
  WorkspaceRoomActionProposal,
  WorkspaceRoomActionRow,
  WorkspaceRoomFeature,
  WorkspaceRoomWorkbenchPresentation,
  WorkspaceShipPhasePresentation,
  WorkspaceShipStructurePhase,
  WorkspaceRoomActions,
  WorkspaceFieldsCageLabel,
  WorkspaceFieldsCageOrderControl,
  WorkspaceFieldsSpatialControl,
  WorkspaceFieldsSpatialPointInteraction,
  WorkspaceRoomLifecycleTimeline,
  WorkspaceRoomLifecycleTimelineEntry,
  WorkspaceRoomLifecycleBoundary,
  WorkspaceHubSlotCloseInteraction,
  WorkspaceHubSlotInteraction,
  WorkspaceHubSlotOpeningAttempt,
  WorkspaceHubActionOrderInteraction,
  WorkspaceHubActionOrderProposal,
  WorkspaceInteractionCatalog,
  WorkspaceStartInteraction,
  WorkspaceAcquisitionConversionInteraction,
  WorkspaceHermesShrineOfferInteraction,
  WorkspacePurgingPoolSlotInteraction,
  WorkspaceStygianWellOfferInteraction,
  WorkspaceStygianWellTwistResultInteraction,
  WorkspaceHermesShrinePurchaseInteraction,
  WorkspaceKeepsakeSelectionInteraction,
  WorkspaceKeepsakeEquipResultInteraction,
  WorkspaceTranscendentEmbryoEquipResultInteraction,
  WorkspaceChaosExitControl,
  WorkspaceChaosExitInteraction,
  WorkspaceChaosSpawnControl,
  WorkspaceChaosSpawnInteraction,
  WorkspaceRewardControl,
  WorkspaceRewardWheelDescriptor,
  WorkspaceSteadyGrowthControl,
  WorkspaceSteadyGrowthDomain,
  WorkspaceSteadyGrowthInteraction,
  WorkspaceTranscendentEmbryoControl,
  WorkspaceTranscendentEmbryoDomain,
  WorkspaceTranscendentEmbryoInteraction,
  WorkspaceFountainRarityControl,
  WorkspaceFountainRarityDomain,
  WorkspaceFountainRarityInteraction,
  WorkspaceRoomPickerControl,
  WorkspaceRoomInteraction,
  WorkspaceBossDoorRewardStoreControl,
  WorkspaceRoomSummary,
  WorkspaceTakeoverBatchInteraction,
  WorkspaceTakeoverRepairInteraction,
  WorkspaceTopologyRemovalInteraction,
  WorkspaceZagreusContractControl,
  WorkspaceZagreusContractInteraction,
  WorkspaceZagreusSpawnControl,
  WorkspaceZagreusSpawnInteraction,
} from './contract';
export type {
  WorkspaceTraitOfferControl,
  WorkspaceLauncherPresentation,
  WorkspaceAspectHexTreeControl,
  WorkspaceTraitCarrierChildControl,
  WorkspaceTraitCarrierChildInteraction,
  WorkspaceTraitAcquisitionTargetDomain,
  WorkspaceLatestModelTargetsDomain,
  WorkspaceCirceResolutionDomain,
  WorkspaceEchoPomTargetDomain,
  WorkspaceEchoLastRunBoonDomain,
  WorkspaceMaxHealthRoll,
  WorkspaceEchoLastRunBoonCarrierDomain,
  WorkspaceEchoLastRunBoonDraftRow,
  WorkspaceEchoLastRunBoonDraftSupport,
  WorkspaceEchoLastRunBoonTraitIdentity,
  WorkspaceAllTogetherSetDomain,
  WorkspaceNaturalSelectionDomain,
  WorkspaceConcaveStoneDomain,
  WorkspaceConcaveStoneInteraction,
  WorkspaceRansomAssessment,
  WorkspaceLevelResolutionControl,
  WorkspaceTraitOfferInteraction,
  WorkspaceTraitOfferFeedback,
  WorkspaceChaosOfferDomain,
  WorkspaceChaosOfferInteraction,
  WorkspaceChaosOfferOptionDomain,
  WorkspaceLevelResolutionInteraction,
  WorkspaceTraitOptionDomainInteraction,
  WorkspaceHexDeckTable,
  WorkspaceHexTreeDomain,
  WorkspaceHexTreeNode,
  WorkspaceHexBoardNode,
  WorkspaceHexActivationBoard,
  WorkspaceHexActivationInteraction,
  WorkspaceHexActivationNode,
} from './contracts/traits';
export type {
  RankedPrefix,
  RankedPrefixDropTarget,
  RankedPrefixMove,
  RankedPrefixMoveResult,
} from './presentation/hub-ranking';
export { createStructuredWorkspaceProjection } from './projector';
export type {
  WorkspaceJudgmentArcanaInteraction,
  WorkspaceFigurineArcanaInteraction,
} from './contracts/timeline';
