/**
 * Stable application and React entry point for the structured editor
 * workspace. Construction and contract implementation remain private to this
 * directory so consumers depend on one deliberate projection boundary.
 */
export { requireWorkspaceInteraction, workspaceInteractionKey } from './contract';
export type {
  StructuredWorkspaceProjection,
  StructuredWorkspaceProjectionService,
  WorkspaceAuthoringFrontier,
  WorkspaceBatchRepairIntent,
  WorkspaceBiome,
  WorkspaceBiomeField,
  WorkspaceCandidateInteraction,
  WorkspaceCompletedHubHandoffInteraction,
  WorkspaceCommandIntent,
  WorkspaceCompletionNode,
  WorkspaceDefaultInspectorDestination,
  WorkspaceEphyraSideRoomDescriptor,
  WorkspaceEphyraSideRoomGroup,
  WorkspaceExitSelectionInteraction,
  WorkspaceHubDecisionNode,
  WorkspaceHubTakeoverControl,
  WorkspaceHubTakeoverInteraction,
  WorkspaceHubSlot,
  WorkspaceHubSlotCloseInteraction,
  WorkspaceHubSlotInteraction,
  WorkspaceHubSlotOpeningAttempt,
  WorkspaceHubVisit,
  WorkspaceHubVisitInteraction,
  WorkspaceInspectorDestination,
  WorkspaceInteractionCatalog,
  WorkspaceMarker,
  WorkspaceMissingPhysicalTarget,
  WorkspaceMixedBatchNode,
  WorkspaceNode,
  WorkspaceOccurrenceWorkbenchNode,
  WorkspaceOrdinaryBatchNode,
  WorkspacePhysicalTarget,
  WorkspaceRailReward,
  WorkspaceRailEntry,
  WorkspaceRailSelectedTarget,
  WorkspaceRewardControl,
  WorkspaceRoomPickerControl,
  WorkspaceRoomInteraction,
  WorkspaceRoomSummary,
  WorkspaceShopPurchaseOrderOption,
  WorkspaceRoute,
  WorkspaceTakeoverBatchInteraction,
  WorkspaceTakeoverBatchNode,
  WorkspaceTakeoverRepairInteraction,
  WorkspaceTopologyRemovalInteraction,
} from './contract';
export { createStructuredWorkspaceProjection } from './projector';
