import type { RawTraitDeclaration } from '../types';

export const daggerWeaponUpgradeTraits = [
  {
    key: 'DaggerBlinkAoETrait',
    label: 'Sweeping Ambush',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialJumpTrait',
    label: 'Dancing Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialLineTrait',
    label: 'Sureshot Flurry',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerRapidAttackTrait',
    label: 'Rapid Onslaught',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialConsecutiveTrait',
    label: 'Melting Sickle',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerBackstabTrait',
    label: 'Skulking Onslaught',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialReturnTrait',
    label: 'Reaper Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerSpecialFanTrait',
    label: 'Hidden Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerAttackFinisherTrait',
    label: 'Final Slice',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerFinalHitTrait',
    label: 'Wicked Onslaught',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerChargeStageSkipTrait',
    label: 'Sudden Flurry',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: [
        'DaggerBackstabAspect',
        'DaggerHomingThrowAspect',
        'DaggerBlockAspect',
        'DaggerTripleAspect',
      ],
    },
  },
  {
    key: 'DaggerDashAttackTripleTrait',
    label: 'Trick Knives',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerBackstabAspect', 'DaggerHomingThrowAspect', 'DaggerBlockAspect'],
    },
  },
  {
    key: 'DaggerTripleBuffTrait',
    label: 'Phantom Brand',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerTripleAspect'],
    },
  },
  {
    key: 'DaggerTripleRepeatWomboTrait',
    label: 'Banshee Brand',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerTripleAspect'],
    },
  },
  {
    key: 'DaggerTripleHomingSpecialTrait',
    label: 'Sinister Pinion',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponDagger',
      aspectKeys: ['DaggerTripleAspect'],
    },
  },
] satisfies readonly RawTraitDeclaration[];
