import type { RawTraitDeclaration } from '../types';

export const lobWeaponUpgradeTraits = [
  {
    key: 'LobAmmoTrait',
    label: 'Bolstered Array',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobAmmoMagnetismTrait',
    label: 'Fetching Array',
    linkedBoonRequirements: [],
    eligibilityRequirements: [
      {
        kind: 'notEquippedTrait',
        traitKeys: ['LobPulseAmmoTrait'],
      },
    ],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobRushArmorTrait',
    label: 'Melting Break',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobSpreadShotTrait',
    label: 'Wide Grin',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobSpecialSpeedTrait',
    label: 'Rapid Driver',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobSturdySpecialTrait',
    label: 'Colossus Driver',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobOneSideTrait',
    label: 'Mega Driver',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobInOutSpecialExTrait',
    label: 'Twisting Crash',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: [
        'LobAmmoBoostAspect',
        'LobCloseAttackAspect',
        'LobImpulseAspect',
        'LobGunAspect',
      ],
    },
  },
  {
    key: 'LobStraightShotTrait',
    label: 'Boosted Ignition',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobPulseAmmoTrait',
    label: 'Volatile Array',
    linkedBoonRequirements: [],
    eligibilityRequirements: [
      {
        kind: 'notEquippedTrait',
        traitKeys: ['LobAmmoMagnetismTrait'],
      },
    ],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobPulseAmmoCollectTrait',
    label: 'Possessed Array',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobGrowthTrait',
    label: 'Looming Ignition',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobAmmoBoostAspect', 'LobCloseAttackAspect', 'LobImpulseAspect'],
    },
  },
  {
    key: 'LobGunOverheatTrait',
    label: 'Venerated Relic',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunBounceTrait',
    label: 'Leering Glance',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunSpecialBounceTrait',
    label: 'Runic Driver',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunAttackRangeTrait',
    label: 'Garmr Gaze',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
  {
    key: 'LobGunAttackDoublerTrait',
    label: 'Helheim Charge',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponLob',
      aspectKeys: ['LobGunAspect'],
    },
  },
] satisfies readonly RawTraitDeclaration[];
