import type { RawTraitDeclaration } from '../types';

export const staffWeaponUpgradeTraits = [
  {
    key: 'StaffDoubleAttackTrait',
    label: 'Wicked Thrasher',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffLongAttackTrait',
    label: 'Extending Wallop',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffDashAttackTrait',
    label: 'Melting Swipe',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffTripleShotTrait',
    label: 'Dual Moonshot',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffJumpSpecialTrait',
    label: 'Shimmering Moonshot',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffExAoETrait',
    label: 'Cross Cataclysm',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffAttackRecoveryTrait',
    label: 'Rapid Thrasher',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffFastSpecialTrait',
    label: 'Rapid Moonshot',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffExHealTrait',
    label: 'Vampiric Cataclysm',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffSecondStageTrait',
    label: 'Giga Moonburst',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffPowershotTrait',
    label: 'Aetheric Moonburst',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: [
        'BaseStaffAspect',
        'StaffClearCastAspect',
        'StaffSelfHitAspect',
        'StaffRaiseDeadAspect',
      ],
    },
  },
  {
    key: 'StaffOneWayAttackTrait',
    label: 'Mirrored Thrasher',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['BaseStaffAspect', 'StaffClearCastAspect', 'StaffSelfHitAspect'],
    },
  },
  {
    key: 'StaffRaiseDeadBigTrait',
    label: 'Soulfilled Ankh',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'StaffRaiseDeadDoubleTrait',
    label: 'Mirrored Ankh',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'StaffLoneShadeRespawnTrait',
    label: 'Scarab Etchings',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
  {
    key: 'StaffLoneShadeRallyTrait',
    label: 'Pharaoh Etchings',
    linkedBoonRequirements: [],
    eligibilityRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponStaffSwing',
      aspectKeys: ['StaffRaiseDeadAspect'],
    },
  },
] satisfies readonly RawTraitDeclaration[];
