import type { RawTraitDeclaration } from '../types';

export const suitWeaponUpgradeTraits = [
  {
    key: 'SuitArmorTrait',
    label: 'Melting Cross',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitAttackSpeedTrait',
    label: 'Rapid Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitAttackSizeTrait',
    label: 'Reaper Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitAttackRangeTrait',
    label: 'Siege Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitFullChargeTrait',
    label: 'World Collider',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect', 'SuitComboAspect'],
    },
  },
  {
    key: 'SuitDashAttackTrait',
    label: 'Exhaust Riser',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialJumpTrait',
    label: 'Shimmering Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialStartUpTrait',
    label: 'Furious Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialAutoTrait',
    label: 'Launcher Frame',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialBlockTrait',
    label: 'Counter Barrage',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialDiscountTrait',
    label: 'Sudden Salvo',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitSpecialConsecutiveHitTrait',
    label: 'Ripper Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['BaseSuitAspect', 'SuitMarkCritAspect', 'SuitHexAspect'],
    },
  },
  {
    key: 'SuitComboForwardRocketTrait',
    label: 'Elephant Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitComboBlockBuffTrait',
    label: 'Counter Supreme',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitComboDoubleSpecialTrait',
    label: 'Awakened Rockets',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitComboDashAttackTrait',
    label: 'Mooncrest Riser',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
  {
    key: 'SuitPowershotTrait',
    label: 'Chakra Collider',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponSuit',
      aspectKeys: ['SuitComboAspect'],
    },
  },
] satisfies readonly RawTraitDeclaration[];
