import type { RawTraitDeclaration } from '../types';

export const torchWeaponUpgradeTraits = [
  {
    key: 'TorchExSpecialCountTrait',
    label: 'Hidden Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchDetonateAspect', 'TorchAutofireAspect'],
    },
  },
  {
    key: 'TorchSpecialSpeedTrait',
    label: 'Clean Coil',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchAttackSpeedTrait',
    label: 'Furious Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchSprintRecallAspect', 'TorchDetonateAspect'],
    },
  },
  {
    key: 'TorchSpecialLineTrait',
    label: 'Melting Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchSpecialImpactTrait',
    label: 'Enduring Coil',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchMoveSpeedTrait',
    label: 'Mega Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchSplitAttackTrait',
    label: 'Dividing Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchAutofireAspect'],
    },
  },
  {
    key: 'TorchEnhancedAttackTrait',
    label: 'Inverted Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchDiscountExAttackTrait',
    label: 'Sudden Burst',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchSprintRecallAspect', 'TorchDetonateAspect'],
    },
  },
  {
    key: 'TorchLongevityTrait',
    label: 'Rising Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchSpecialDurationAspect', 'TorchSprintRecallAspect', 'TorchDetonateAspect'],
    },
  },
  {
    key: 'TorchOrbitPointTrait',
    label: 'Whirling Helix',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchSpinAttackTrait',
    label: 'Leaden Blaze',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: [
        'TorchSpecialDurationAspect',
        'TorchSprintRecallAspect',
        'TorchDetonateAspect',
        'TorchAutofireAspect',
      ],
    },
  },
  {
    key: 'TorchAutofireSprintTrait',
    label: 'Demonic Cell',
    offerRequirements: [],
    elementContributions: {},
    usesBoonRarity: false,
    blockStacking: false,
    blockInRunRarify: false,
    excludeFromRarityCount: false,
    hammerCompatibility: {
      weaponKey: 'WeaponTorch',
      aspectKeys: ['TorchAutofireAspect'],
    },
  },
] satisfies readonly RawTraitDeclaration[];
